1D Heat Transfer Benchmark
==========================
:author: Christophe Prud'homme <christophe.prudhomme@feelpp.org>
:toc:


> **Note** This benchmark applies to both link:HeatTransfer[Heat Transfer] and link:ReducedBasis[Reduced Basis].

= Description

We consider a 1D heat diffusion problem. It is described by two geometrical domains in $$\mathbb{R}$$ :
$$\Omega_1 =[-0.5~,~0]$$ and $$\Omega_2=[0~,~0.5]$$.
The temperature $$T$$ of the domain $$\Omega = \cup_{i=1}^2 \Omega_i$$ is then solution of
the following steady heat diffusion equation :
$$
    -  k ~ \Delta T  = \varphi
$$
where $$\varphi$$ is the source term and $$k$$ is thermal conductivity defined as
$$k=0.1+k_1$$ if $$x \leq 0$$ and by $$k=0.1+k_2$$ if $$x>0$$.

This problem has been proposed to validate the implementation of CRB methods and especially the Successive Constraint Method (SCM) algorithm.

== Boundary Conditions

We set

. at $$x=-0.5$$, a non-homogeneous Neumann condition
$$
  k  \frac{\partial T}{\partial x}  = \delta;
$$
. at $$x=0.5$$, a Robin condition
  $$
    -k \ \frac{\partial T}{\partial x}  =  T .
  $$

== Inputs

As inputs, We define the parameter set $$\mu$$  by
$$
  \mu=(k_1,k_2,\delta,\varphi)~\in~[0.2~,~50]^2 \times [-1~,~5] \times [0.1~,~5]
$$

== Outputs

The output $$s(\mu)$$ is the mean temperature on the central part of domain $$\Omega$$, defined by
$$
  s(\mu) = \frac{1}{0.2} \int_{-0.1}^{0.1} T
$$
This output depends on the solution of the equation above and is dependent on
the parameter set $$\mu$$.
