= Computational Fluid Dynamics
// Don't put authors here! (see CONTRIBUTING)
//*******************************************
:page-layout: manual 
:page-permalink: /toolbox/cfd/model
:page-root: ../../../../
:title: Computational Fluid Dynamics
:doctype: book
:docinfo: shared
:imagesdir: /images/
:sources: ../../../
// Keep this include header at the end! (see CONTRIBUTING)
include::../../../includes/header.adoc[]
//*******************************************

TIP: Benchmarks are available at link:/benchmarks/cfd[CFD Benchmarks].

== Notations and units

|===
| Notation | Quantity | Unit

|stem:[\rho_f]|fluid density|stem:[kg \cdot m^{-3}]
|stem:[\boldsymbol{u}_f]|fluid velocity|stem:[m \cdot s^{-1}]
|stem:[\boldsymbol{\sigma}_f]|fluid stress tensor|stem:[N \cdot m^{-2}]
|stem:[\boldsymbol{f}^t_f]| source term | stem:[kg \cdot m^{-3} \cdot s^{-1}]
|stem:[p_f]|pressure fields|stem:[kg \cdot m^{-1} \cdot s^{-2}]
|stem:[\mu_f]| dynamic viscosity|stem:[kg \cdot m^{-1} \cdot s^{-1}]
|stem:[\bar{U}]|characteristic inflow velocity|stem:[m \cdot s^{-1}]
|stem:[\nu]|kinematic viscosity|stem:[m^2 \cdot s^{-1}]
|stem:[L]| characteristic length|stem:[m]
|===


== Equations

Navier-Stokes model is used to model incompressible Newtonian fluid.
It can be described by these conservative laws :

[stem]
.Momentum conservation equation
++++
\rho_{f} \left. \frac{\partial\mathbf{u}_f}{\partial t} \right|_\mathrm{x}
+ \rho_{f} \left( \boldsymbol{u}_{f} \cdot \nabla_{\mathrm{x}} \right) \boldsymbol{u}_{f}
- \nabla_{\mathrm{x}} \cdot \boldsymbol{\sigma}_{f} = \boldsymbol{f}^t_f , \quad \text{ in } \Omega^t_f \times \left[t_i,t_f \right]
++++

[env.equation]
[stem]
.Mass conservation equation
++++
\nabla_{\mathrm{x}} \cdot \boldsymbol{u}_{f} = 0, \quad \text{ in } \Omega^t_f \times \left[t_i,t_f \right]
++++

we complete this set of equations with the fluid constitutive law

[env.equation]
.Material constitutive equation
--
\boldsymbol{\sigma}_{f} = -p_f \boldsymbol{I} + 2\mu_f D(\boldsymbol{u}_{f})
--

with strain tensor stem:[D(\boldsymbol{u}_{f})] defined by :

[env.equation]
.Strain tensor
--
D(\boldsymbol{u}_{f}) = \frac{1}{2} (\nabla_\mathrm{x} \boldsymbol{u}_f + (\nabla_\mathrm{x} \boldsymbol{u}_f)^T)
--

An alternative model is the Stokes model. It is valid in the case of small Reynolds number. It corresponds to the same formulation than Navier-Stokes equations but without the convective term stem:[\left( \boldsymbol{u}_{f} \cdot \nabla_{\mathrm{x}} \right) \boldsymbol{u}_{f}] .

= Multifluid flows

We introduce here the methodology associated to multifluid flows.

== Introduction

Let's define a bounded domain stem:[\Omega \subset \mathbb{R}^p] (stem:[p=2,3]) decomposed
into two subdomains stem:[\Omega_1] and stem:[\Omega_2]. We denote stem:[\Gamma] the interface
between the two partitions. The goal of the level set method is to track
implicitly the interface stem:[\Gamma(t)] moving at a velocity stem:[\mathbf{u}]. The level
set method has been described in <<osher>> and
its main ingredient is a continuous scalar function stem:[\phi] (the /level
set/ function) defined on the whole domain. This function is chosen to be
positive in stem:[\Omega_1], negative in stem:[\Omega_2] and zero on stem:[\Gamma]. The motion
of the interface is then described by the advection of the level set function
with a divergence free velocity field stem:[\mathbf{u}]:

[stem]
++++
   \frac{\partial \phi}{\partial t} + \mathbf{u} \cdot \nabla \phi = 0,\quad \nabla
   \cdot \mathbf{u} = 0.
++++
A convenient choice for stem:[\phi] is a signed distance function to the interface. Indeed, the property stem:[|\nabla \phi| = 1] of distance functions  eases the numerical solution and gives a convenient support for delta and Heaviside functions).

Nevertheless, it is known that the advection equation \eqref{eq:advection} does not conserve
the property stem:[|\nabla \phi|=1]. Thus, when stem:[|\nabla \phi|] is far from stem:[1] we have to reset stem:[\phi] as a distance function without moving the interface. To do so we can either use an Hamilton-Jacobi method or the fast marching method (see \cite{Winkelmann2007} for details about the fast marching method).

== Interface related quantities


In two-fluid flow simulations, we need to define some quantities related to the
interface such as the density, the viscosity, or some interface forces. To this end,
we introduce the smoothed Heaviside and delta functions:

[stem]
++++
    H_{\varepsilon}(\phi) = \left\{ \begin{array}{cc}
      0, & \phi \leq - \varepsilon,\\
      \displaystyle\frac{1}{2} \left(1+\frac{\phi}{\varepsilon}+\frac{\sin(\frac{\pi \phi}{\varepsilon})}{\pi}\right),  & -\varepsilon \leq \phi \leq \varepsilon, \\
      1, & \phi \geq \varepsilon. \end{array} \right.
++++
      
[stem]
++++
    \delta_{\varepsilon}(\phi) = \left\{ \begin{array}{cc}
      0, & \phi \leq - \varepsilon,\\
      \displaystyle\frac{1}{2 \varepsilon} \left(1+\cos(\frac{\pi \phi}{\varepsilon})\right),  & -\varepsilon \leq \phi \leq \varepsilon, \\
      0, & \phi \geq \varepsilon. \end{array} \right.
++++


where stem:[\varepsilon] is a parameter defining a ``numerical thickness'' of the interface. A
typical value of stem:[\varepsilon] is stem:[1.5 h] where stem:[h] is the mesh size of elements
crossed by the iso-value stem:[0] of the level set function.

The Heaviside function is used to define parameters having different values on
each subdomains. For example, we define the density of two-fluid flow as
stem:[\rho = \rho_2 + (\rho_1-\rho_2) H_{\varepsilon}(\phi)] (we use a similar expression for the viscosity stem:[\nu]). Regarding the delta function, it is used to define
quantities on the interface. In particular, in the variational formulations, we
replace integrals over the interface stem:[\Gamma] by integrals over the entire
domain stem:[\Omega] using
the smoothed delta function. If stem:[\phi] is a signed distance function, we have :
stem:[\int_{\Gamma} 1 \simeq \int_{\Omega} \delta_{\varepsilon}(\phi)].  If stem:[\phi] is
not close enough to a distance function, then stem:[\int_{\Gamma} 1 \simeq
\int_{\Omega} |\nabla \phi| \delta_{\varepsilon}(\phi)] which still tends to the
measure of stem:[\Gamma] as stem:[\varepsilon] vanishes. However, if stem:[\phi] is not a
distance function, the support of stem:[\delta_{\varepsilon}] can have a different
size on each side of the interface. More precisely, the support of
stem:[\delta_{\varepsilon}] is narrowed on the side where stem:[|\nabla \phi|>1] and
enlarged on regions where stem:[|\nabla \phi|<1].  It has been shown in
<<cottet>> that replacing stem:[\phi] by stem:[\frac{\phi}{|\nabla \phi|}] has the
property that stem:[|\nabla \frac{\phi}{|\nabla \phi|}| \simeq 1] near the interface
and has the same iso-value stem:[0] as stem:[\phi]. Thus, replacing stem:[\phi] by
stem:[\frac{\phi}{|\nabla \phi|}] as support of the delta function does not move the
interface. Moreover, the spread interface has the same size on each part of the
level-set stem:[\phi=0]. It reads stem:[\int_{\Gamma} 1 \simeq \int_{\Omega}
\delta_{\varepsilon}(\frac{\phi}{| \nabla \phi|})].  The same technique is used for
the Heaviside function.

== Numerical implementation and coupling with the fluid solver

We use {feelpp} to discretize and solve the problem.
Equation \eqref{eq:advection} is solved using
a stabilized finite element method. We have implemented several stabilization
methods such as Streamline Upwind Diffusion (SUPG), Galerkin Least Square (GLS)
and Subgrid Scale (SGS). A general review of these methods is available in <<Franca92>>. Other available methods include the Continuous Interior
Penalty method (CIP) are described in \cite{Burman2006}.  The variational
formulation at the semi-discrete level for the stabilized equation \eqref{eq:advection} reads, find stem:[\phi_h
\in {\mathbb R}_h^k] such that stem:[\forall \psi_h \in {\mathbb R}_h^k] :

[stem]
++++
  \left(\int_{\Omega} \frac{\partial \phi_h}{\partial t}  \psi_h + \int_{\Omega} (\mathbf{u}_h \cdot \nabla \phi_h) \psi_h\right) +  S(\phi_h, \psi_h) = 0,
++++
where stem:[S(\cdot, \cdot)] stands for the stabilization bilinear form (see section
\ref{sec:membr-inext} for description of stem:[{\mathbb R}_h^k] and stem:[\mathbf{u}_h]).
In our case, we use a BDF2 scheme which needs the solution at the two previous time step to compute the one at present time. For the first time step computation or after a reinitialization we use an Euler scheme.

== Two-fluid flow
The two-fluid flow problem can be expressed by 

[stem]
++++
\begin{align}
    \frac{D( \rho_\phi \boldsymbol{u} )}{Dt} - \boldsymbol{\nabla} \cdot ( 2 \mu_\phi \boldsymbol{D}({\boldsymbol{u}}) ) + \boldsymbol{\nabla} p  = \boldsymbol{f}_\phi \\
    \nabla \cdot \boldsymbol{u} = 0 \\
    \partial_t \phi + \boldsymbol{u} \cdot \boldsymbol{\nabla} \phi =0
\end{align}
++++

Where stem:[\boldsymbol{f}_\phi] is the force obtain by projection of the density of interfacial forces on the domain stem:[\Omega]

[stem]
++++
\boldsymbol{f}_{\phi} = \boldsymbol{g}(\phi, \boldsymbol{ n }, \kappa) \delta_\varepsilon(\phi)
++++



include::../../../man/03-modeling/Fluid/README.adoc[]

