= Compiling {feelpp} from sources
include::{partialsdir}/header-macros.adoc[]

NOTE: {lvl_advanced}

TIP: For beginners, you can skip this section and go directly to <<containers,containers>> section.

Before starting compiling {feelpp}, you need first to

* [x] understand the xref:install:prerequisites-dev.adoc[{feelpp} programming environment].
* [x] install the required and suggested compilers, libraries and tools for xref:install:linux.adoc[Linux] or xref:install:mac.adoc[MacOsX] to build {feelpp} for these architectures.

== For the impatient

To follow these steps, make sure that you first follow xref:install:prerequisites-dev.adoc[programming environment prerequisites] steps.

First retrieve the source
[source,bash]
----
$ git clone https://github.com/feelpp/feelpp.git
----

{feelpp} does not allow in-source `cmake`, the build must be done in separate directory.

[source,bash]
.Create a build directory
----
$ mkdir build
$ cd build
----


[source,bash]
.Configure {feelpp}
----
$ CXX=clang++ ../feelpp/configure -r
----


[source,bash]
.Compile the {feelpp} library, its tools and a few examples
----
$ make  <1>
$ make install <2>
----
<1> compile {feelpp}:  library, tools and quickstart examples
<2> install {feelpp}

TIP: you can speed up the make process by passing the option `-j<N>` where `N` is the number of concurrent `make` sub-processes. It compiles `N` files at a time and respect dependencies. For example `-j4` compiles 4 C++ files at a time.

WARNING: Be aware that {feelpp} consumes memory. The {feelpp} library compile with 2Go of RAM. But to be more comfortable, 4Go or more would be best.


[source,sh]
.Execute your first {feelpp} application in sequential
----
$ ./feelpp_qs_laplacian_2d --case laplacian/feelpp2d
----

[source,sh]
.Execute your first {feelpp} application using 4 mpi processes
----
$ cd feelpp/quickstart
$ mpirun -np 4 feelpp_qs_laplacian_2d --case laplacian/feelpp2d
----

== Downloading sources

[[tarballs]]
=== Using Tarballs

{feelpp} is distributed as tarballs following each major release. The tarballs are available on the  link:https://github.com/feelpp/feelpp/releases[{feelpp} Releases] web page.

Download the latest tarball, then uncompress it with:

[source,sh]
----
$ tar -xzf feelpp-X.YY.0.tar.gz
$ cd feelpp-X.YY.0
----

You can now move to the section <<cmake>>.

[[git]]
=== Using Git

Alternatively, you can download the sources of {feelpp} directly from link:https://github.com/feelpp/feelpp[the Git repository].

[source,sh]
----
$ git clone  https://github.com/feelpp/feelpp.git
----

You should read something like
[source,sh]
----
Cloning into 'feelpp'...
remote: Counting objects: 129304, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 129304 (delta 6), reused 0 (delta 0), pack-reused 129283
Receiving objects: 100% (129304/129304), 150.52 MiB | 1.69 MiB/s, done.
Resolving deltas: 100% (94184/94184), done.
Checking out files: 100% (7237/7237), done.
----

[source,sh]
----
$ cd feelpp
----

The first level directory tree is as follows
[source,sh]
----
$ tree -L 1 -d
.
├── benchmarks
├── cmake
├── data
├── databases
├── doc
├── feelpp
├── mor
├── ports
├── research
├── testsuite
└── toolboxes
----


== Configuring {feelpp}

For now on, we assume that `clang++` has been installed in `/usr/bin`. Yor mileage
may vary depending on your installation of course.

WARNING: It is not allowed to build the library in the top source directory.

[TIP]
====
It is recommended  to have a directory (e.g. `FEEL`) in which you have
both the sources and build directories, as follows
[source,sh]
----
$ ls FEEL
feelpp/ # Sources
feel.opt/ # Build directory
----
`feelpp` is the top directory where the source have been downloaded, using git or tarballs.
====

WARNING: the components {feelpp} toolboxes and mor are not configured and compiled by default, you have to enable them either using `cmake` or convenience script `configure`

[[cmake]]
=== Using cmake

The configuration step with `cmake` is as follows

[source,sh]
----
$ cd FEEL/feel.opt
$ cmake ../feelpp <1>
----
<1> Run `cmake` with default configuration flags from toplevel {feelpp} source directory in `../feelpp`

TIP: Use `ccmake` to configure {feelpp} using a graphical or text interface.

[source,sh]
----
$ cd FEEL/feel.opt
$ cmake ../feelpp
 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-4.0  <1>
 -DCMAKE_C_COMPILER=/usr/bin/clang-4.0  <2>
 -DCMAKE_BUILD_TYPE=RelWithDebInfo <3>
----
<1> set the {cpp} compiler to `/usr/bin/clang++-4.0`
<2> set the C compiler to `/usr/bin/clang-4.0`
<3> set the cmake build type to `RelWithDebInfo`

[NOTE]
====
CMake supports different build type that you can set with `-DCMAKE_BUILD_TYPE` (case insensitive) :

 * None
 * Debug : typically `-g`
 * Release : typically `-O3 -DNDEBUG`
 * MinSizeRel : typically `-Os`
 * RelWithDebInfo :  typically `-g -O2 -DNDEBUG`
====

.Enable {feelpp} toolboxes and mor using `cmake
[source,sh]
----
cmake ../feelpp ... -DFEELPP_ENABLE_TOOLBOXES=ON -DFEELPP_ENABLE_MOR=ON
----

=== Using `configure`

Alternatively you can use the `configure` script which calls `cmake`.
`configure --help` provides the following help.
[source,sh]
.Listing Configure help
----
./configure [options...]
Options:
 -b, --build                         build type: Debug, Release, RelWithDebInfo
 -d, --debug                         debug mode
-rd, --relwithdebinfo                relwithdebinfo mode
 -r, --release                       release mode
     --std=c++xx                     c++ standard c++14, c++1z (default: c++14)
     --stdlib=libxx                  c++ standard library libstdc++, libc++ (default: libstdc++)
     --max-order=x                   maximum polynomial order to instantiate(default: 3)
     --cxxflags                      override cxxflags
     --cmakeflags                    add extra cmake flags
     --prefix=PATH                   define install path
     --root=PATH                     define root path
     --enable-pch                    enable precompiled headers (default)
     --disable-pch                   disable precompiled headers
     --enable-python                 enable python
     --enable-cling                  enable cling
     --disable-cling                 disable cling (default)
     --enable-toolboxes              enable Feel++ toolboxes and PyFeel++ toolboxes
     --disable-toolboxes             disable Feel++ toolboxes and PyFeel++ toolboxes (by default)
     --enable-mor                    enable Feel++ mor and PyFeel++ mor
     --disable-mor                   disable Feel++ mor and PyFeel++ mor (by default)
 -v, --verbose                       enable verbose output
 -h, --help                          help page
     --<package>-dir=PACKAGE_PATH    define <package> install directory
     --disable-<package>             disable <package>
     --generator=GENERATOR           cmake generator
----

We display below a set of possible configurations:

Compile using Release build type, default c++ compiler and libstdc++::
+
[source,sh]
.Listing compiling using default compilers
----
$ ../feelpp/configure -r
----

Setup and compile {feelpp}, the {feelpp} toolboxes and {feelpp} mor::
+
[source,sh]
.Listing to compile {feelpp}, the {feelpp} toolboxes and {feelpp} mor
----
../feelpp/configure -r --enable-toolboxes --enable-mor
----

Compile using Release build type, clang++ compiler and libstdc++::
+
[source,sh]
.Listing compiling using clang++
----
$ CXX=clang++ ../feelpp/configure -r
----

Compile using Debug build type, clang++ compiler and libc++::
+
[source,sh]
.Listing compiling using clang++/libc++ in Debug mode
----
CXX=clang++ ../feelpp/configure -d -stdlib=c++
----



== Compiling {feelpp}

Once `cmake` or `configure` have done their work successfully, you are ready to compile {feelpp}

[source,bash]
----
$ make
$ make install
----

[TIP]
.Parallel compilation
====
You can speed up the compilation process, if you have a multicore processor by specifying the number of parallel jobs `make` will be allowed to spawn  using the `-j` flag:

[source,bash]
.Listing build {feelpp} library using 4 concurrent jobs
----
$ make -j4 feelpp
----
====

NOTE: From now on, all commands should be typed in build directory (e.g `feel.opt`) or its subdirectories.
