= Install {feelpp} from Containers
include::{partialsdir}/header-macros.adoc[]


The recommended way to start learning {feelpp} consists in using container technologies.
Containers provide an all-in one programming environment to start directly using {feelpp}.
{feelpp} is provided with two containers solutions currently:

. link:https://www.docker.com/what-docker[Docker]
. link:http://singularity.lbl.gov/about[Singularity]

Depending on your usage and your operating system, you might prefer using one of these previous solutions.
On a laptop or workstation Docker and Singularity are preferred while on a cluster Singularity is preferred.

The next sub-sections describe how to obtain {feelpp} images to begin with {feelpp} programming.

TIP: {feelpp} images provide either a compiling environment with all dependencies,
executables or both.

IMPORTANT: Before going further you might want to install one of the previous
solution.
link:https://docs.docker.com/install:linux/docker-ce/ubuntu/[install docker] or
link:http://singularity.lbl.gov/install-linux[install singularity].



== Docker

Using {feelpp} inside <<what-is-docker,Docker>> is the recommended and fastest way to use {feelpp}.
The <<Docker,Docker chapter>> is dedicated to Docker and <<feelpp-containers,{feelpp} containers chapter>> is dedicated to {feelpp} in Docker.
We strongly encourage you to follow these steps if you begin with {feelpp} in particular as an end-user.
Users who would like to develop with and in {feelpp} should read through the remaining sections of this chapter.

To begin with {feelpp} using docker, you need first to link:https://docs.docker.com/install:linux/docker-ce/ubuntu/[install docker] to have a working docker environment on your machine following the official documentation with respect to your operating system.
Then choose one of the {feelpp} images available on the official repository
link:https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=feelpp&starCount=0[dockerhub].

We provide currently two main images:

.Table of the current components of the FCS
|===
| Component | Description | Built From

| `feelpp`  | Feel++ libraries and tools |
| `feelpp-toolboxes` | {feelpptb}   | `feelpp`

|===

=== Usage example

Via the command line and using the {feelpp} toolboxes below, we get the image and create a new container.

[source, bash]
----
docker pull feelpp/feelpp-toolboxes <1>
docker run -it -v ${HOME}/feel:/feel feelpp/feelpp-toolboxes <2>
----
<1> fetch the latest `feelpp/feelpp-toolboxes` image
<2> create a container associated to `feelpp/feelpp-toolboxes`, execute in interactive mode and mount `$HOME/feel` on `/feel` in Docker in order to access the simulation results outside the Docker image.

The `-it` option is used to place yourself inside the container in an interactive mode.
You can start using {feelpp} commands directly.
Note that the `-v` option is used to share a folder between the host and the container.

TIP: Each container can be seen as an instance for the choosen image.
You can create as many instance as you desire!

It is also possible to execute a {feelpp} application or a command embedded in the container
from the outside. For example

[source, bash]
----
docker run feelpp/feelpp-toolboxes echo "Hello World!"
----

TIP: To keep your data in the container, you can use `docker [start|stop] -i <container name>`.

Many examples are available in the {feelpp} tools and toolboxes.
For example, once you are in Docker,
[source, bash]
.Run the CFD toolbox on the TurekHron benchmark
----
mpirun --bind-to core -np 10 feelpp_toolbox_fluid --case "github:{path:toolboxes/fluid/TurekHron}"
----

== Singularity

singularity is another container technology initially developed to work with
HPC infrastructure and solve some security problems in multi-users environment.
Latest link:https://girder.math.unistra.fr/#collections[{feelpp} singularity
images] can be found on link:https://girder.math.unistra.fr/#collections[our
data management server] (recommended) in the {feelpp} collection.  Future
public {feelpp} images will also be available on the official
link:https://singularity-hub.org/[singularity hub] website.  We provide
currently the same main images as for docker, but the suffix naming might vary
depending on the image version.

Singularity works in a similar way as for docker.  For example, you can
download one of the image available on
link:https://girder.math.unistra.fr/#collections[girder] under the collection
`feelpp` -> `singularity_images` -> `ci` -> `feelpp_feelpp-toolboxes-latest.simg`
click on download button.


Once downloaded you can place yourself in the container in interactive as for docker
using the commandline

[source, bash]
----
singularity shell -B ${HOME}/feel:/feel feelpp_feelpp-toolboxes-latest.simg
----

TIP: You can retrieve an image from singularity hub directly
`singularity pull shub://feelpp/singularity:feelpp-toolboxes-latest` instead of girder
and as for docker.
Be aware that current images are currently older than the ones on girder!
