= Get {feelpp}

{feelpp} can be installed on Windows 10, Debian/Ubuntu systems.

We created two delivery channels: `stable` and `latest`.

`stable`:: Docker and Debian/Ubuntu packages with latest {feelpp} release following the `master` branch.

`latest`:: Docker and Debian/Ubuntu packages with latest {feelpp} development following the `develop` branch.

[blockMacroTemplate,par,'flavor,dist,channel']
----
.Command lines to install the {channel} {feelpp} channel on {flavor}/{dist}
[source,bash]
--
wget -qO - http://apt.feelpp.org/apt.gpg | sudo apt-key add
echo "deb http://apt.feelpp.org/{flavor}/{dist} {dist} {channel}" | sudo tee -a /etc/apt/sources.list.d/feelpp.list
sudo apt update
--
----

[tabs]
====
Ubuntu::
+
--
Ubuntu LTS distributions jammy(22.04-preferred) is supported.

We may support short term distributions.

[[jammy]]
[discrete]
=== Jammy LTS (22.04)

par::[ubuntu,jammy,latest]

[[lunar]]
[discrete]
=== Lunar (23.04)

par::[ubuntu,lunar,latest]

[[kinetic]]
[discrete]
=== Kinetic (22.10)

par::[ubuntu,kinetic,latest]

[[focal]]
[discrete]
=== Focal LTS (20.04)

par::[ubuntu,focal,latest]


The supported systems are described below
[cols="1,1,1,1,2", options="header"]
.Table {feelpp} Ubuntu distributions
|===
|Distribution | Release | Version | Supported Channels | Comment

|ubuntu | jammy | 22.04 | latest | LTS
|ubuntu | lunar | 23.04 | latest |
|ubuntu | kinetic | 22.10 | latest |
|ubuntu | focal | 20.04 | latest | LTS


|===

include::partial$install-deb.adoc[]
--
Debian::
+
--
Debian LTS distributions bookworm(12) and bullseye(11) are supported.

//Debian Sid packages are also available.

The supported systems are described below
[cols="1,1,1,1,2", options="header"]
.Table {feelpp} Debian distributions
|===
|Distribution | Release | Version | Supported Channels | Comment

|debian |bookworm | 12 | latest | LTS
|debian |bullseye | 11 | latest | LTS
|debian |testing| - | latest | testing
|debian |sid| - | latest | unstable

|===


[discrete]
=== Bullseye (11)

par::[debian,bullseye,latest]

[discrete]
=== Testing (testing)

par::[debian,testing,latest]

[discrete]
=== Sid (unstable)

par::[debian,sid,latest]


include::partial$install-deb.adoc[]
--
Fedora::
+
--

{feelpp} is not yet packaged for Fedora. 
However 
 
- [x] it is possible to compile it from source for Fedora:36 and Fedora:37
- [x] a docker image containing {feelpp} development environment is available for both systems

.Fedora 36(stable) 
 $ docker run --rm -it ghcr.io/feelpp/feelpp-env:fedora-36 

or 

.Fedora 37(beta)
 $ docker run --rm -it ghcr.io/feelpp/feelpp-env:fedora-37 

see xref:compile.adoc[how to build {feelpp} from sources].

--
Windows 10::
+
--
To use {feelpp} on Windows 10, follow these steps:

 * [x] install https://docs.microsoft.com/fr-fr/windows/wsl/install-win10:[WSL (Windows Subsystem for Linux)]
 * [x] install https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions[Ubuntu focal (20.04) Ubuntu jammy(22.04) or Debian bullseye(11)]
 * [x] follow the corresponding Ubuntu or Debian {feelpp} installation steps

include::partial$install-deb.adoc[]
--
Docker::
+
--
A docker image is generated with the deb packages.
The image is based on the LTS distribution Ubuntu Focal 20.04.

To download and execute it, follow the steps described below

.Download and run  the feelpp docker image: contains feelpp, feelpp-toolboxes, feelpp-mor and feelpp-python
----
docker pull ghcr.io/feelpp/feelpp:jammy
docker run --rm -it -v $HOME/feel:/feel ghcr.io/feelpp/feelpp:jammy
----

.Download and run  the feelpp docker image including the development kit: contains feelpp, feelpp-toolboxes, feelpp-mor and feelpp-python
----
docker pull ghcr.io/feelpp/feelpp-dev:jammy
docker run --rm -it -v $HOME/feel:/feel ghcr.io/feelpp/feelpp-dev:jammy
----
--
// MacOSX::
// +
// --
// 
// * [x] install https://brew.sh/[Homebrew] 
// * [x] install {feelpp} Homebrew tap
// [source,bash]
// ----
// brew tap feelpp/homebrew-feelpp
// ----
// * [x] install {feelpp}
// [source,bash]
// ----
// brew install feelpp
// ----
// 
// --

====

