= Get {feelpp}

{feelpp} can be installed on Windows 10, Debian/Ubuntu systems and MacOSX.

We created two delivery channels: `stable` and `latest`.

`stable`:: Docker and Debian/Ubuntu packages with latest {feelpp} release following the `master` branch.

`latest`:: Docker and Debian/Ubuntu packages with latest {feelpp} development following the `develop` branch.

[blockMacroTemplate,par,'flavor,dist,channel']
----
.Command lines to install the {channel} {feelpp} channel on {flavor}/{dist}
[source,bash]
--
wget -qO - http://apt.feelpp.org/apt.gpg | sudo apt-key add
echo "deb http://apt.feelpp.org/{flavor}/{dist} {dist} {channel}" | sudo tee -a /etc/apt/sources.list.d/feelpp.list
sudo apt update
--
----

[tabs]
====
Ubuntu::
+
--
// Ubuntu LTS distributions focal(20.04-preferred) bionic (18.04) are supported.
Ubuntu LTS distributions focal(20.04-preferred) is supported.

We may support short term distributions.

[discrete]
=== Focal (20.04)

par::[ubuntu,focal,latest]

[discrete]
=== Jammy (22.04)

par::[ubuntu,jammy,latest]


The supported systems are described below
[cols="1,1,1,1,2", options="header"]
.Table {feelpp} Ubuntu distributions
|===
|Distribution | Release | Version | Supported Channels | Comment

|ubuntu | focal | 20.04 | latest | LTS
|ubuntu | jammy | 22.04 | latest | LTS

|===

include::partial$install-deb.adoc[]
--
Debian::
+
--
Debian LTS distributions bullseye(11) is supported.

//Debian Sid packages are also available.

The supported systems are described below
[cols="1,1,1,1,2", options="header"]
.Table {feelpp} Debian distributions
|===
|Distribution | Release | Version | Supported Channels | Comment

|debian |bullseye | 11 | latest | LTS
// |debian |sid|  | latest | unstable

|===


[discrete]
=== Bullseye (11)

par::[debian,buster,latest]

//par::[debian,buster,stable]

[discrete]
=== Sid (unstable)

par::[debian,sid,latest]





include::partial$install-deb.adoc[]
--
Windows 10::
+
--
To use {feelpp} on Windows 10, follow these steps:

 * [x] install https://docs.microsoft.com/fr-fr/windows/wsl/install-win10:[WSL (Windows Subsystem for Linux)]
 * [x] install https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions[Ubuntu focal (20.04) or Debian buster(10)]
 * [x] follow the corresponding Ubuntu or Debian {feelpp} installation steps

--
Docker::
+
--
A docker image is generated with the deb packages.
The image is based on the LTS distribution Ubuntu Focal 20.04.

To download and execute it, follow the steps described below

.Download and run  the feelpp docker image: contains feelpp, feelpp-toolboxes, feelpp-mor and feelpp-python
----
docker pull feelpp/feelpp:focal
docker run --rm -it -v $HOME/feel:/feel feelpp/feelpp:focal
----

.Download and run  the feelpp docker image including the development kit: contains feelpp, feelpp-toolboxes, feelpp-mor and feelpp-python
----
docker pull feelpp/feelpp-dev:focal
docker run --rm -it -v $HOME/feel:/feel feelpp/feelpp-dev:focal
----
--
// MacOSX::
// +
// --
// 
// * [x] install https://brew.sh/[Homebrew] 
// * [x] install {feelpp} Homebrew tap
// [source,bash]
// ----
// brew tap feelpp/homebrew-feelpp
// ----
// * [x] install {feelpp}
// [source,bash]
// ----
// brew install feelpp
// ----
// 
// --

====

