= Ubuntu packages

{feelpp} can be installed on Ubuntu systems.

== Add {feelpp} Ubuntu repository

The supported systems are
[cols="1,1,1,2", options="header"]
.Table {feelpp} Ubuntu distributions
|===
|Distribution | Version | Component | Comment

|focal| 20.04 | main | next lts (to be released on April 23, 2020
|eoan| 19.10 | main |
|bionic| 18.04 | main | LTS

|===

Using the command line, add the following to your /etc/apt/sources.list system config file:
----
echo "deb https://dl.bintray.com/feelpp/ubuntu {distribution} {components}" | sudo tee -a /etc/apt/sources.list
----
for example
----
echo "deb https://dl.bintray.com/feelpp/ubuntu eoan main" | sudo tee -a /etc/apt/sources.list
----
Or, add the repository URLs using the "Software Sources" admin UI:
----
deb https://dl.bintray.com/feelpp/ubuntu {distribution} {components}
----

You now download the Bintray public GPG key as follows: 
----
wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add - 
----

You should then update the database
----
sudo apt update
----

== Install {feelpp} packages

[cols="1,2", options="header"]
.Table {feelpp} Ubuntu packages
|===
|Name | Description

|libfeelpp1| shared libraries
|libfeelpp-dev| development headers and libraries
|feelpp-tools| mesh partitioners and remote data upload/download
|feelpp-quickstart| quickstart applications (laplacian cg an hdg), stokes, elasticity(cg and hdg)
|feelpp-data| data files (geometry and config files) for {feelpp} applications (e.g. feelpp-quickstart)
|===


.Install the library
----
sudo apt install libfeelpp1
----

.Install the tools
----
sudo apt install feelpp-tools
----

.Install the quickstart applications and associated data
----
sudo apt install feelpp-tools feelpp-data
----
