= Ubuntu packages

{feelpp} can be installed on Ubuntu systems.

== Add {feelpp} Ubuntu repository

The supported systems are
[cols="1,1,1,2", options="header"]
.Table {feelpp} Ubuntu distributions
|===
|Distribution | Version | Channels | Comment

|focal| 20.04 | stable,latest | next LTS (to be released on April 23, 2020)
|eoan| 19.10 | stable,latest |
|bionic| 18.04 |  | LTS

|===

Using the command line, add the following to your /etc/apt/sources.list system config file:
----
echo "deb https://dl.bintray.com/feelpp/ubuntu {distribution} {channel}" | sudo tee -a /etc/apt/sources.list
----
for example install the eoan `stable` channel
----
echo "deb https://dl.bintray.com/feelpp/ubuntu eoan stable" | sudo tee -a /etc/apt/sources.list
----
or the eoan `latest` channel
----
echo "deb https://dl.bintray.com/feelpp/ubuntu eoan latest" | sudo tee -a /etc/apt/sources.list
----

NOTE: installing both the `stable` and the `latest` channels will result in having the `stable` being superseded by the `latest` channel.

TIP: add the repository URLs using the "Software Sources" admin UI:
----
deb https://dl.bintray.com/feelpp/ubuntu {distribution} {components}
----

You now download the Bintray public GPG key as follows:
----
wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
----

You should then update the database
----
sudo apt update
----

== Install {feelpp} packages

[cols="1,2", options="header"]
.Table {feelpp} Ubuntu packages
|===
|Name | Description

|libfeelpp1| shared libraries
|libfeelpp-dev| development headers and libraries
|feelpp-tools| mesh partitioners and remote data upload/download
|feelpp-quickstart| quickstart applications (laplacian cg an hdg), stokes, elasticity(cg and hdg)
|feelpp-data| data files (geometry and config files) for {feelpp} applications (e.g. feelpp-quickstart)
|===


.Install the library
----
sudo apt install libfeelpp1
----

.Install the tools
----
sudo apt install feelpp-tools
----

.Install the quickstart applications and associated data
----
sudo apt install feelpp-quicktart feelpp-data
----
