= Initializing {feelpp}
include::{partialsdir}/header-macros.adoc[]

The `core` module provides the basic data structures to

* setup and run {feelpp} application in a parallel environment.
* handle the command line options
* download and upload data from and to Github and/or Girder

== Setting up the {feelpp} Environment

.Start the {feelpp} environment, `test_core.py`
[source,python]
----
include::{uri-pyfeelpp-raw}tests/test_core.py[]
----
//include::{uri-pyfeelpp-raw}core/test_core.py[]

To execute the previous example

.Execute the script above on 4 parallel processes
[source,sh]
----
mpiexec -n 4 python3 test_core.py
----

Command line options can be passed to the python script

.get the version of pyfeelpp and {feelpp}
[source,sh]
----
mpiexec -n 4 python3 test_core.py --version
----

== Downloading data

[source,python]
----
include::{uri-pyfeelpp-raw}tests/test_remotedata.py[]
----

To execute the previous example

.Execute the script above on 4 parallel processes
[source,sh]
----
mpiexec -n 4 python3 test_remotedata.py
----

and get the file `README.adoc` from the toplevel {feelpp} github directory downloaded

.Download remote file on {uri-github-feelpp} repository
----
Welcome to PyFeel++
version: 0.106.0-beta.2
[ Starting Feel++ ] application test_remotedata.py version 0.1 date 2018-Sep-18
 . test_remotedata.py files are stored in /feel/test_remotedata.py/np_1
 .. logfiles :/feel/test_remotedata.py/np_1/logs
download data in  /feel/test_remotedata.py/downloads
downloaded data: ['/feel/test_remotedata.py/downloads/README.adoc']
[env] Time : 1.39421s
[ Stopping Feel++ ] application test_remotedata.py execution time 1.39421s
----
