= Initializing {feelpp}
include::user:ROOT:partial$header-macros.adoc[]
:page-jupyter: true
:page-plotly: true

The `core` module provides the basic data structures to

* setup and run {feelpp} application in a parallel environment.
* handle the command line options
* download and upload data from and to GitHub and/or Girder

== Setting up the {feelpp} Environment

To set {feelpp} environment, we create an environment and set the associated repository for the results.
A {feelpp} environment can be created only once.
The repository can be global with respect to `$HOME/.feelppconfig` `globalroot` setting  or local with respect to the current directory.

.Set the {feelpp} environment with local repository
[%dynamic,python]
----
import feelpp as fpp
import sys
app = fpp.Environment(["myapp"],config=fpp.localRepository(""))
----

.Query the app about the current environment
[%dynamic,python]
----
print("pid:",app.worldComm().localRank() )
print("isMasterRank:",app.isMasterRank() )
print("is parallel: ",app.isParallel() )
----

== Downloading data

{feelpp} can query data on GitHub and Girder.

[%dynamic,python]
----
readme=fpp.download( "github:{repo:feelpp,path:README.adoc}", worldComm=app.worldCommPtr() )[0]

print("downloaded Feel++ README.adoc from Github: ",readme)
----

The code will get the file `README.adoc` from the toplevel {feelpp} github directory downloaded

A bit more interesting example: the following code will download a csv file from the {feelpp} github repository and plot the data using the `plotly` library.

[%dynamic,python]
----
acsv=fpp.download( "github:{repo:feelpp,path:toolboxes/fluid/cases/moving_body/gravity/cylinder_under_gravity/curve_comparison.csv}", worldComm=app.worldCommPtr() )[0] # <1>
import pandas as pd # <2>
df = pd.read_csv(acsv, sep=",") # <3>
df.columns = df.columns.str.replace(' ', '')
print(df.head())
----
<1> download the file `curve_comparison.csv` from the {feelpp} github repository `toolboxes/fluid/cases/moving_body/gravity/cylinder_under_gravity/curve_comparison.csv`
<2> use the `pandas` library to read the csv file
<3> read the csv file and remove the spaces in the column names

We can now use plotly to plot the data

[%dynamic%raw,python]
----
import plotly.express as px
fig = px.scatter(df,x="TIME", y="Y_CM", title="y-displacement of the center of mass(CM) of the cylinder",labels={"TIME":"t (s)","Y_CM":r'y-displacement (m)'})
fig.show()
----

=== Next steps

- [x] xref:pyfeelpp/expr.adoc[Manipulate expressions]
- [x] xref:pyfeelpp/mesh.adoc[Manipulate meshes]
