= Initializing {feelpp}
include::user:ROOT:partial$header-macros.adoc[]
:page-jupyter: true

The `core` module provides the basic data structures to

* setup and run {feelpp} application in a parallel environment.
* handle the command line options
* download and upload data from and to Github and/or Girder

== Setting up the {feelpp} Environment

To set {feelpp} environment, we create an environment and set the associated repository for the results. 
A {feelpp} environment can be created only once. 
The repository can be global with respect to `$HOME/.feelppconfig` `globalroot` setting  or local with respect to the current directory.

.Set the {feelpp} environment with local repository
[source,python]
----
import feelpp as fpp
import sys
app = fpp.Environment(["myapp"],config=fpp.localRepository(""))
----

.Results
[%collapsible.result]
====
----
[ Starting Feel++ ] application myapp version 0.1 date 2022-Nov-04
[feelpp] create Feel++ root repository: /scratch/jupyter/feelppdb

[feelpp] create Feel++ geo repository: /scratch/jupyter/feelppdb/geo

[feelpp] create Feel++ results directory: /scratch/jupyter/feelppdb/np_1

[feelpp] create Feel++ expressions directory: /scratch/jupyter/feelppdb/exprs

[feelpp] create Feel++ logs directory: /scratch/jupyter/feelppdb/np_1/logs

 . myapp files are stored in /scratch/jupyter/feelppdb/np_1
 .. logfiles :/scratch/jupyter/feelppdb/np_1/logs
----
====


.Query the app about the current environment
[source,python]
----
print("pid:",app.worldComm().localRank() )
print("isMasterRank:",app.isMasterRank() )
print("is parallel: ",app.isParallel() )
----

== Downloading data

{feelpp} can query data on GitHub and Girder.

[source,python]
----
readme=fpp.download( "github:{repo:feelpp,path:README.adoc}", worldComm=app.worldCommPtr() )[0]

print("downloaded Feel++ README.adoc from Github: ",readme)
----

The code will get the file `README.adoc` from the toplevel {feelpp} github directory downloaded

A bit more interesting example 

[source,python]
----
acsv=fpp.download( "github:{repo:feelpp,path:toolboxes/fluid/cases/moving_body/gravity/cylinder_under_gravity/curve_comparison.csv}", worldComm=app.worldCommPtr() )[0]
import pandas as pd
df = pd.read_csv(acsv, sep=",")
df.columns = df.columns.str.replace(' ', '')
print(df.head())

# prepare for plotting
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=df["TIME"], y=df["Y_CM"], name="y displacement"))
fig.update_layout(legend_title_text='y-displacement over time of a falling disk in a fluid')
fig.show()
----

The code will download a csv file from the {feelpp} github repository and plot the data using the `plotly` library.

