= The Feel++ Book
:page-layout: default
// URIs:
:uri-org: https://github.com/feelpp
:uri-repo: {uri-org}/feelpp
:uri-www: http://www.feelpp.org
:uri-project: http://book.feelpp.org
ifdef::env-site[:uri-project: link:]
:uri-docs: {uri-project}/docs
:uri-news: {uri-project}/news
:uri-manpage: {uri-project}/man/asciidoctor
:uri-issues: {uri-repo}/issues
:uri-contributors: {uri-repo}/graphs/contributors
:uri-rel-file-base: link:
:uri-rel-tree-base: link:
:uri-rel-file-base: link:
:uri-rel-tree-base: link:
ifdef::env-site[]
:uri-rel-file-base: {uri-repo}/blob/master/
:uri-rel-tree-base: {uri-repo}/tree/master/
endif::[]
:uri-changelog: {uri-rel-file-base}CHANGELOG.adoc
:uri-contribute: {uri-rel-file-base}CONTRIBUTING.adoc
:uri-license: {uri-rel-file-base}LICENSE.adoc
:uri-freesoftware: https://www.gnu.org/philosophy/free-sw.html
:docinfo: shared
:feelpp: Feel++

{feelpp} is a unified {cpp} implementation of Galerkin methods (finite and
spectral element methods) in 1D, 2D and 3D to solve partial differential
equations.

.Key documentation
[.compact]
--
link:/user-manual/[{feelpp} User Manual]::
The A to Z guide to {feelpp}.

link:/math[The Mathematics of {feelpp}]::
The mathematics used and developed in {feelpp}

Modeling With {feelpp} Toolboxes::
Solving PDEs with {feelpp} Toolboxes.
** link:/toolbox/cfd[Computational Fluid Dynamics]
** link:/toolbox/heat[Heat Transfer]
** link:/toolbox/csm[Computational Solid Mechanics]
** link:/toolbox/fsi[Fluid Structure Interaction]
** link:/toolbox/thermoelectric[ThermoElectric]
** link:/toolbox/maxwell[ElectroMagnetism]

link:/programming[Programming With {feelpp}]::
The first step into Programming with {feelpp}

link:/reference[Reference]::
Reference on various Mathematical concepts in {feelpp}

link:/quickref[Quick Reference]::
Quick reference cards for {feelpp} expressions that you can use in
variational formulations.
--

== Contributing

In the spirit of {uri-freesoftware}[free software], _everyone_ is encouraged to help improve this project.
If you discover errors or omissions in the source code, documentation, or website content, please don't hesitate to submit an issue or open a pull request with a fix.
New contributors are always welcome!

Here are some ways *you* can contribute:

* by using develop versions
* by {uri-issues}[reporting bugs]
* by {uri-issues}[suggesting new features]
* by writing or editing documentation
* by writing specifications
* by writing code -- _No patch is too small._
** fix typos
** add comments
** write examples!
** write tests!
* by refactoring code
* by fixing {uri-issues}[issues]
* by reviewing Pull Requests

The {uri-contribute}[Contributing] guide provides information on how to create, style, and submit issues, feature requests, code, and documentation to the {feelpp} Project.

== Getting Help

The {feelpp} project is developed to help you easily do _(i)_ modelisation simulation and optimisation and _(ii)_ high performance computing.
But we can't do it without your feedback!
We encourage you to ask questions and discuss any aspects of the project on the discussion list, on Twitter or in the chat room.

Twitter:: #feelpp hashtag or @feelpp mention
Chat (Gitter):: image:https://badges.gitter.im/Join%20In.svg[Gitter, link=https://gitter.im/feelpp/feelpp]

ifdef::env-github[]
Further information and documentation about {feelpp} can be found on the project's website.

{uri-project}/[Home] | {uri-news}[News] | {uri-docs}[Docs]
endif::[]

The {feelpp} organization on GitHub hosts the project's source code, issue tracker, and sub-projects.

Source repository (git):: {uri-repo}
Issue tracker:: {uri-issues}
{feelpp} organization on GitHub:: {uri-org}

== Copyright and Licensing

Copyright (C) 2011-2017 {feelpp} Consortium.
Free use of this software is granted under the terms of the GPL License.

See the {uri-license}[LICENSE] file for details.

== Authors

{feelpp} is led by https://github.com/prudhomm[Christophe Prud'homme] and has received contributions from {uri-contributors}[many other individuals].
The project was initiated in 2006 by https://github.com/prudhomm[Christophe Prud'homme] and based initially on link:https://cmcsforge.epfl.ch/projects/lifev/[lifeV] and completely re-written since then.

++++
      <footer class="site-footer">
        <span class="site-footer-owner"><a href="https://github.com/feelpp/feelpp/doc/book">Feel++ Book</a> is open-sourced by <a href="https://github.com/feelpp">Feel++ Consortium </a>.</span>

      </footer>

    </section>


  </body>
</html>
++++
