[preface]
= Preface

== Discussion Forum

We're always happy to help out with {feelpp} or any other questions you might
have. You can ask a question or signal an issue at the Gitter {feelpp} salon.

.Join the {feelpp} chat 
image:https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/feelpp/feelpp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

This book is available on Github. We use Gitter to discuss the changes in the book.

.Join the {feelpp} book chat
image:https://badges.gitter.im/Join%20Chat.svg[link=https://gitter.im/feelpp/feelpp-book?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge]

== Conventions used in this book


The following typographical conventions are used in the book

_Italic_ indicates new terms

`typewriter` is used on program listings as well as when referring to
programming elements, _e.g._ functions, variables, statements, data types,
environment variables or keywords.

`\$ typewriter` or `> typewriter` displays commands that the user types literally without the `\$` or `>`.

NOTE: this is a general note.

WARNING: this is a general warning.

CAUTION: be cautious

include::00-preface/notations.adoc[leveloffset=+1]
