site:
  title: Feel++ Docs
  url: https://docs.feelpp.org/
  start_page: home::index.adoc
  robots: allow
  keys:
    google_analytics: 'UA-65761593-1'
content:
  sources:
  - url: https://github.com/feelpp/book.feelpp.org
    branches: [develop]
    start_path: docs/feelppdocs
    tags:
    - v0.110
    - v0.109
  - url: https://github.com/feelpp/book.feelpp.org
    branches: develop
    start_path: docs/user
    tags:
    - v0.110
    - v0.109
#    - v0.108
#    - v0.107
#    - v0.106
#    - v0.105
  - url: https://github.com/feelpp/book.feelpp.org
    branches: develop
    start_path: docs/dev
    tags:
    - v0.110
    - v0.109
#    - v0.108
#    - v0.107
#    - v0.106
#    - v0.105
  - url: https://github.com/feelpp/feelpp-tutorial-dev
    branches: master
    start_path: docs/
  - url: https://github.com/feelpp/feelpp-project
    branches: master
    start_path: docs/
  - url: https://github.com/feelpp/book.feelpp.org
    branches: develop
    start_path: docs/data
    tags:
    - v0.110
    - v0.109
  - url: https://github.com/feelpp/book.feelpp.org
    branches: develop
    start_path: docs/math
  - url: https://github.com/feelpp/book.feelpp.org
    branches: develop
    start_path: docs/toolboxes
    tags:
    - v0.110
    - v0.109
#    - v0.108
#    - v0.107
#    - v0.106
#    - v0.105
  - url: https://github.com/feelpp/toolbox
    branches: [develop]
    tags:
    - v0.110
    - v0.109
#    - v0.108
#    - v0.107
#    - v0.106
#    - v0.105
    start_path: examples
  # - url: https://github.com/feelpp/toolbox
  #   branches: master
  #   tags:
  #   - v*
  #   start_path: benchmarks
  - url: https://github.com/feelpp/toolbox
    branches: master
    start_path: contribute
  - url: https://github.com/feelpp/book.feelpp.org
    branches: develop
    start_path: docs/mor
    tags:
    - v0.110
    - v0.109
  - url: https://github.com/feelpp/angiotk
    branches: master
    start_path: docs
#  - url: https://github.com/feelpp/book.hifimagnet
#    branches: master
#    start_path: docs/mso4sc
  - url: https://github.com/feelpp/book.feelpp.org
    branches: develop
    start_path: docs/salome/
#  - url: https://github.com/feelpp/book.feelpp.org
#    branches: mor-module
#    start_path: docs/mor/
urls:
  latest_version_segment: stable
  latest_version_segment_strategy: redirect:to
ui:
  bundle:
    url: https://github.com/feelpp/antora-ui/releases/latest/download/ui-bundle.zip # https://gitlab.com/feelpp/antora-ui-default/-/jobs/artifacts/feelpp/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: supplemental-ui
antora:
  extensions:
  - '@antora/collector-extension'
asciidoc:
  attributes:
    page-component-order: '!home, !ROOT, user, dev, data, math, toolboxes, cases, *'
    page-pagination: ''
    kroki-fetch-diagram: true
    feelpp-git-tag: develop
    deploymentRoot: ""
    numbered: true
    hide-uri-scheme: true
    uri-github: https://github.com/
    uri-org-feelpp: https://github.com/feelpp/
    uri-github-feelpp: https://github.com/feelpp/feelpp/
    uri-github-feelpp-raw: https://raw.githubusercontent.com/feelpp/feelpp
    uri-paraview-www: https://www.paraview.org/
    uri-ensight-www: Ensight
    uri-msoportal-www: http://portal.mso4sc.eu/
    uri-msoportal-visu-www: http://portal.mso4sc.eu/
    uri-gmsh-www: https://gmsh.info
    uri-gmsh-manual: https://gmsh.info
    uri-benchmarks: http://docs.feelpp.org/cases/{toolboxes_cases_manual_version}
    python: Python
    slepc: SLEPc
    petsc: PETSc
    lustre: Lustre
    feelpp: Feel++
    feelpptb: Feel++ Toolboxes
    feelppmor: Feel++ Model Order Reduction
    pyfeelpp: pyFeel++
    pyfeelpptb: pyFeel++ Toolboxes
    pyfeelppmor: pyFeel++ MOR
    angiotk: AngioTK
    4fastsim: 4FastSim
    stem: latexmath
    hemotumpp: Hemotum++
    eye2brain: Eye2Brain
    vivabrain: Vivabrain
    vtkjs: Vtkjs
    plotly: Plot.ly
    hifimagnet: HiFiMagnet
    magnettools: MagnetTools
    meshgems: MeshGems
    salome: Salome
    singularity: Singularity
    sregistry: Sregistry
    cpp: C++
    cpp14: C++14
    cmake: CMake
    paraview: ParaView
    paraview-url: https://paraview.org
    paraview-website: link:{paraview-url}[{paraview}]
    ensight: EnSight
    girder: Girder
    plantuml-server-url: http://www.plantuml.com/plantuml
  extensions:
    - "@feelpp/asciidoctor-remote-include-processor"
    - ./lib/plotly.js
    - asciidoctor-kroki
    - asciidoctor-emoji
    - ./lib/tabs-block-extension
    - "@djencks/asciidoctor-template"
    - ./lib/vtkjs.js
    - ./lib/mpirun.js

