= Advection-diffusion


On s’intéresse au problème suivant:

[[prob:10]]
.Problème
****
On cherche stem:[u : \Omega \rightarrow \RR] telle que
[[eq:30]]
[stem]
++++
    \begin{split}
      -\nabla \cdot ( \mathbf{\alpha} \nabla u  ) + \mathbf{\beta} \cdot \nabla u + \mu u &= f
      \mbox{ dans } \Omega\\
      \mathcal{B} u &= 0 \mbox{ sur } \partial \Omega\\
    \end{split}
++++
****

où stem:[\mathcal{B}] est l'opérateur prenant en compte les conditions aux limites.
La variation sur les conditions aux limites de la section [sec:cond-aux-limit] s’appliquent.

* stem:[\mathcal{B}u=u] condition de Dirichlet
* stem:[\mathcal{B}u=(\mathbf{\alpha}\nabla{u}) \cdot n] condition de Neumann
* stem:[\mathcal{B}u=\gamma u + (\mathbf{\alpha} \nabla u )\cdot n] condition de Robin

Les différents termes de l'opérateur ont une interprétation physique

* stem:[-\nabla \cdot ( \mathbf{\alpha} \nabla u  )] est un terme de link:https://en.wikipedia.org/wiki/Diffusion[diffusion],

* stem:[\mathbf{\beta} \cdot \nabla u] est un terme d'link:https://en.wikipedia.org/wiki/Advection[advection],

* stem:[\mu u] est un terme de réaction (production ou destruction).

Ce type d’équation est très fréquente en ingéniérie, biologie ou encore finance.


[NOTE]
.Transfert de chaleur
====
stem:[u] is the temperature, stem:[\alpha=\kappa \mathcal{I}] où stem:[\kappa] est la link:https://fr.wikipedia.org/wiki/Conductivité_thermique[_conductivité thermique_], stem:[\beta] est le champ d'écoulement, stem:[\mu = 0] et stem:[f] est chaleur apportée exterieurement par unité de volume.
====

[NOTE]
.Advection Diffusion
====
stem:[u] est la concentration d'un link:https://en.wikipedia.org/wiki/Solution[soluté] transportée dans un champ d'écoulement stem:[\beta].
La matrice stem:[\alpha] modélise la diffusivité du soluté soit de la link:https://en.wikipedia.org/wiki/Molecular_diffusion[diffusion moléculaire] soit du link:https://en.wikipedia.org/wiki/Turbulence[mélange turbulent] du fluide transporteur.
La production ou destruction par réaction chimique is pris en compte par le terme linéaire stem:[\mu u].
Le second membre stem:[f] modélise les sources ou puits.

====

On suppose que stem:[\mathbf{\alpha} \in [L^{\infty}(\Omega)^{d\times d}], stem:[\mathbf{\beta} \in [L^{\infty}(\Omega)^d], stem:[\nabla \cdot \mathbf{\beta} \in L^{\infty}(\Omega)] et stem:[\mu \in L^\infty(\Omega)].

On suppose que l’opérateur stem:[\mathcal{L}] tel que stem:[\mathcal{L} u = -\nabla \cdot ( \alpha \nabla u ) + \beta \cdot \nabla u + \mu u] est _elliptique_ au sens suivant:


[[def:39]]
.Définition
****
L’opérateur stem:[\mathcal{L}] est _elliptique_ si il existe une constante stem:[\alpha_0] telle que presque pour tout stem:[x\in\Omega]
[[eq:88]]
[stem]
++++
    \forall \xi=(\xi_1, \ldots , \xi_n)\in\RR^n,\quad { \sum_{i,j=1}^n  \alpha_{ij}(x) \, \xi_i \, \xi_j  \ge \alpha_0 \, \| \xi \|^2 }
++++
****

[[rem:29]]
TIP: Le Laplacien est dans la catégorie des opérateurs elliptiques, il correspond à stem:[\mathbf{\beta} = 0], stem:[\mu = 0] et stem:[\mathbf{\alpha}=\mathcal{I}_d] avec stem:[\mathcal{I}_d] la matrice identité de stem:[\RR^{d\times d}].

== Condition de Dirichlet homogène

Nous imposons stem:[u=0] sur stem:[\partial \Omega].

Nous multiplions stem:[\mathcal{L} u = f] par une fonction test (suffisamment régulière) s'annulant au bord et on intègre sur stem:[\Omega].
En intégrant par parties (formule de Green) nous avons

[[eq:adr-green]]
.Relation de Green
[stem]
++++
\int_\Omega \nabla \cdot (\mathbf{\alpha} \nabla u )  v  = \int_\Omega (\mathbf{\alpha} \nabla u ) \cdot \nabla v -\int_{\partial \Omega} ((\alpha \nabla u)\cdot n) v
++++
ce qui donne
[stem]
++++
\int_\Omega (\mathbf{\alpha} \nabla u ) \cdot \nabla v + (\mathbf{\beta} \cdot
    \nabla u) v + \mu u v = \int_\Omega f v
++++

Afin que les intégrales sur stem:[\Omega] aient un sens, nous demandons par exemple que stem:[u] et stem:[v] aient la régularité suivante:
[stem]
++++
u\in H^1(\Omega)\quad\text{et}\quad v\in H^1(\Omega).
++++

Comme stem:[u\in H^1(\Omega)], le théorème <<toto>> implique que stem:[u] ait une _trace_ sur le bord.
Comme stem:[u_{|\partial \Omega} = 0], on cherche en fait stem:[u] dans stem:[H^1_0(\Omega)].
Les fonctions tests sont également prises dans stem:[H^1_0(\Omega)] ce qui donne la formulation faible suivante

[[problem_dirichlet]]
.Problème de Dirichlet homogène
****
On cherche stem:[u \in H^1_0(\Omega)] telle que
[[eq:89]]
[stem]
++++
    a(u,v) = \ell(v) \quad \forall v \in H^1_0(\Omega)
++++
avec
[[eq:90]]
[stem]
++++
    a(u,v)=\int_\Omega (\mathbf{\alpha} \nabla u ) \cdot \nabla v + (\mathbf{\beta} \cdot
    \nabla u) v + \mu u v
++++
et
[[eq:91]]
[stem]
++++
    \ell(v) = \int_\Omega f v
++++
****

Nous avons le résultat suivant

[[proposition_dirichlet]]
.Une solution du problème faible est solution du problème fort
****
Si stem:[u] résout <<eq:89>>, alors stem:[\mathcal{L}u=f] presque partout dans stem:[\Omega] et stem:[u=0] presque partout sur stem:[\partial \Omega].
****
.Preuve
****
Soit stem:[\phi\in \mathcal{D}(\Omega)] et stem:[u] une solution du <<problem_dirichlet>>.
On a
[stem]
++++
\begin{split}
\left\langle-\nabla \cdot (\alpha \nabla u), \phi \right\rangle_{\mathcal{D}',\mathcal{D}} &= \left\langle (\alpha \nabla u), \nabla \phi \right\rangle_{\mathcal{D}',\mathcal{D}} = \int_\Omega \alpha \nabla u \cdot \nabla \phi \\
 & = \int_\Omega (f - \beta \cdot \nabla u - \mu u ) \phi,
\end{split}
++++
ce qui donne stem:[\langle\mathcal{L}u,\phi\rangle_{\mathcal{D}',\mathcal{D}} = \int_\Omega f \phi].
Or stem:[\mathcal{D}(\Omega)] est _dense_ dans stem:[L^2(\Omega)], nous avons donc que stem:[\mathcal{L}u=f] dans stem:[L^2(\Omega)].
C'est à dire que stem:[\mathcal{L}u=f] presque partout dans stem:[\Omega].
Enfin stem:[u=0] presque partout sur stem:[\partial \Omega] par définition de stem:[H^1_0(\Omega)] d'après le théorème <<toto>> stem:[\blacksquare]
****

== Conditions de Dirichlet Non homogène

Nous imposons stem:[u=0] sur stem:[\partial \Omega] où stem:[g : \partial \Omega \rightarrow \RR] est une fonction donnée.

Nous supposons que stem:[g] soit suffisamment régulière telle qu'il existe un relèvement stem:[u_g] de stem:[g] dans stem:[H^1(\Omega)], c'est à dire qu'il existe une fonction stem:[u_g] de stem:[H^1(\Omega)] telle que stem:[u_g=g] sur stem:[\partial \Omega].

[[problem_dirichlet_non_homogene]]
.Problème de Dirichlet non homogène
****
On cherche stem:[u \in H^1(\Omega)] telle que
[stem]
++++
u=u_g+\phi,\quad \phi \in H^1_0(\Omega)
++++
où stem:[\phi] est solution de
[[eq:89_1]]
[stem]
++++
    a(\phi,v) = \ell(v) - a(u_g,v) \quad \forall v \in H^1_0(\Omega)
++++
avec
[[eq:90_1]]
[stem]
++++
    a(u,v)=\int_\Omega (\mathbf{\alpha} \nabla u ) \cdot \nabla v + (\mathbf{\beta} \cdot
    \nabla u) v + \mu u v
++++
et
[[eq:91_1]]
[stem]
++++
    \ell(v) = \int_\Omega f v
++++
****

[[proposition_dirichlet_non_homogene]]
.Proposition pour le problème de Dirichlet non homogène
****
Soit stem:[g\in H^{\frac{1}{2}}(\partial \Omega)], si stem:[u] résout le <<problem_dirichlet_non_homogene>>, alors stem:[\mathcal{L}u=f] presque partout dans stem:[\Omega] et stem:[u=g] presque partout sur stem:[\partial \Omega].
****

.Preuve
****
La preuve est similaire à celle du <<problem_dirichlet>>.
****

NOTE: Lorsque l'opérateur stem:[\mathcal{L}] est le Laplacien, <<problem_dirichlet>> est appelé un _problème de Poisson_.


== Conditions de Neumann

Soit une fonction stem:[g:\partial \Omega \rightarrow \RR], nous voulons imposer stem:[\mathcal{B}u=(\alpha \nabla u)\cdot n = g]  sur stem:[\partial \Omega].

NOTE: Dans le cas où stem:[\alpha = \mathcal{I}], la condition de Neumann correspond à spécifier la dérivée normale de stem:[u] car stem:[\nabla u \cdot n = \partial_n u = \frac{\partial u}{\partial n}].

Nous procédons de la même façon que précédemment et en utilisant la condition de Neumann dans l'intégrale de surface, on obtient la formulation faible suivante:

[[problem_neumann]]
.Problème de Neumann
****
On cherche stem:[u \in H^1(\Omega)] telle que

[[eq:89_2]]
[stem]
++++
a(u,v) = \ell(v) \quad \forall v \in H^1(\Omega)
++++
avec
[[eq:90_2]]
[stem]
++++
a(u,v)=\int_\Omega (\mathbf{\alpha} \nabla u ) \cdot \nabla v + (\mathbf{\beta} \cdot
\nabla u) v + \mu u v
++++
et
[[eq:91_2]]
[stem]
++++
\ell(v) = \int_\Omega f v + \int_{\partial \Omega} g v
++++
****

[[proposition_neumann]]
.Proposition pour le problème de Neumann
****
Soit stem:[g\in L^2(\partial \Omega)], si stem:[u] résout le <<problem_neumann>>, alors stem:[\mathcal{L}u=f] presque partout dans stem:[\Omega] et stem:[\alpha \nabla u \cdot n = g] presque partout sur stem:[\partial \Omega].
****
.Preuve
****
En prenant les fonctions tests dans stem:[\mathcal{D}(\Omega)] , on a immediatement que stem:[\mathcal{L}u = f] presque partout dans stem:[\Omega].
Nous avons donc que stem:[-\nabla \cdot (\alpha \nabla u ) \in L^2(\Omega)].
Le corollaire <<B59>> implique que stem:[\alpha \nabla u \cdot n \in H^{\frac{1}{2}}(\partial \Omega)' = H^{-\frac{1}{2}}(\partial \Omega)] du fait que
[stem]
++++
\forall \phi \in H^{\frac{1}{2}}(\partial \Omega), \quad \left\langle\alpha \nabla u \cdot n, \phi\right\rangle_{H^{-\frac{1}{2}},H^{\frac{1}{2}}} = \int_{\Omega} -\nabla \cdot (\alpha \cdot \nabla u) u_\phi + \int_\Omega \alpha \nabla u \cdot \nabla u_\phi
++++
où stem:[u_\phi \in H^1(\Omega)] est un relèvement de stem:[\phi] dans stem:[H^1(\Omega)].
On a alors que le <<problem_neumann>> donne
[stem]
++++
\forall \phi \in H^{\frac{1}{2}}(\partial \Omega), \quad \left\langle\alpha \nabla u \cdot n, \phi\right\rangle_{H^{-\frac{1}{2}},H^{\frac{1}{2}}} = \int_{\partial \Omega} g \phi
++++
montrant que stem:[\alpha \nabla u \cdot n = g] dans stem:[H^{-\frac{1}{2}}(\partial \Omega)] et donc, par conséquent, dans stem:[L^2(\Omega)] du fait que stem:[g] soit dans stem:[L^2(\Omega)].stem:[\blacksquare]
****


== Conditions mixtes Dirichlet-Neumann

NOTE: documentation en cours


== Conditions de Robin

Soient deux fonctions stem:[g,\gamma : \partial \Omega \rightarrow \RR], nous voulons imposer stem:[\gamma u + (\alpha \nabla u)\cdot n = g] sur stem:[\partial \Omega].
En utilisant la relation sur l'intégrale de surface <<eq:adr-green>>, nous avons la formulation faible suivante


[[problem_robin]]
.Problème
****
On cherche stem:[u \in H^1(\Omega)] telle que

[[eq:89_4]]
[stem]
++++
    a(u,v) + \int_{\partial \Omega} \gamma u v = \ell(v) \quad \forall v \in H^1(\Omega)
++++
avec
[[eq:90_4]]
[stem]
++++
    a(u,v)=\int_\Omega (\mathbf{\alpha} \nabla u ) \cdot \nabla v + (\mathbf{\beta} \cdot
    \nabla u) v + \mu u v
++++
et
[[eq:91_4]]
[stem]
++++
    \ell(v) = \int_\Omega f v + \int_{\partial \Omega} g v
++++
****

[[proposition_robin]]
.Proposition pour le problème de Robin
****
Soit stem:[g\in L^2(\partial \Omega)] et stem:[\gamma \in L^\infty(\partial \Omega].
Si stem:[u] résout le <<problem_robin>>, alors stem:[\mathcal{L}u=f] presque partout dans stem:[\Omega] et stem:[\gamma u + \alpha \nabla u \cdot n = g] presque partout sur stem:[\partial \Omega].
****
.Preuve
****
On procède de manière similaire aux preuves précédentes. stem:[\blacksquare]
****

Nous récapitulons dans la table suivante les différentes formulations

.Formulation faible pour différentes conditions aux limites
|===
| Problème | Espace | Forme bilinéaire | Forme linéaire

|Dirichlet homogène
| stem:[H^1_0(\Omega)]
| stem:[a(u,v)]
| stem:[\int_\Omega f v]

| Neumann
| stem:[H^1(\Omega)]
| stem:[a(u,v)]
| stem:[\int_\Omega f v + \int_{\partial \Omega} g v]

|Dirichlet Neumann
| stem:[H^1_{\partial \Omega_D}(\Omega)]
| stem:[a(u,v)]
| stem:[\int_\Omega f v + \int_{\partial \Omega_N} g v]

| Robin (Fourier)
| stem:[H^1(\Omega)]
| stem:[a(u,v) + \int_{\partial \Omega} \gamma uv]
| stem:[\int_\Omega f v + \int_{\partial \Omega} g v]

|===

[[resume-formulation]]
.Résumé
[NOTE]
====
Les problèmes considérés précédents se mettent tous sous la forme suivante, sauf le problème de Dirichlet non homogène
[[eqpbadr]]
[stem]
++++
\left\{\begin{array}{l}
\text{ Chercher } u \in V \text{ telle que}\\
a(u,v)=f(v), \quad \forall v \in V
\end{array}\right.
++++
où stem:[V] est un espace de _Hilbert_ satisfaisant
[stem]
++++
H^1_0(\Omega) \subset V \subset H^1(\Omega)
++++

Dans le cas de conditions de *Dirichlet non-homogènes*, nous avons stem:[u\in H^1(\Omega)] et stem:[u=u_g+\phi] où stem:[u_g] est un relèvement de la donnée au bord stem:[g] et stem:[\phi] résout le <<eqpbadr,problème générique>> avec des conditions de Dirichlet homogènes.
====

.Conditions aux limites essentielles et naturelles
[NOTE]
====
Il est important d'observer le traitement différent entre les conditions de Dirichlet et Neumann ou Robin conditions.

Les conditions de Dirichlet sont imposées explicitement dans l'espace fonctionnel où la solution est recherchée, et les fonctions de test disparaissent (_i.e._ stem:[v=0]) sur la partie correspondante de la frontière.
Pour cette raison, les conditions de Dirichlet sont souvent appelées conditions aux limites _essentielles_ .

Les conditions de Neumann et Robin ne sont pas imposées par le cadre fonctionnel mais par la formulation faible elle-même.
Le fait que les fonctions test ont des degrés de liberté sur la partie correspondante de la frontière est suffisant pour faire respecter les conditions limites en question.
Pour cette raison, ces conditions sont souvent appelées conditions aux limites _naturelles_.
====

[[sec:adr-coercivity]]
== Coercivité

On s'intéresse à présent au théorème traitant de la coercivité du <<resume-formulation,problème abstrait>>.

[env.theorem#adr-thr1]
****
Soient stem:[f\in L^2(\Omega),  stem:[\mathbf{\alpha} \in [L^{\infty}(\Omega)^{d\times d}], stem:[\mathbf{\beta} \in [L^{\infty}(\Omega)\]^d], stem:[\nabla \cdot \mathbf{\beta} \in L^{\infty}(\Omega)] et stem:[\mu \in L^\infty(\Omega)].

On note stem:[p = \essinf_{x \in \Omega} (\mu -\frac{1}{2} \nabla \cdot \mathbf{\beta})] et stem:[c_\Omega] est la constante de  xref:math:analyse-fonctionnelle:lemma.adoc#lemmaB61[l’inégalité de Poincaré].

_(i)_ Les problèmes avec conditions de Dirichlet  <<problem_dirichlet,homogènes>> et  <<problem_dirichlet_non_homogene,non-homogènes>> sont bien posés si
[[eq:92]]
[stem]
++++
  \alpha_0 > - \min( 0, \frac{\gamma}{c_\Omega}  )
++++

_(ii)_ Le problème  avec condition de Neumann <<problem_neumann>> est  bien posé si
[[eq:92_1]]
[stem]
++++
  p > 0\quad\text{et}\quad \essinf_{x \in \Omega}(\beta \cdot n ) \geq 0
++++

_(iii)_ Le problème  avec condition de Dirichlet-Neumann <<prob12_3>> est  bien posé si <<eq:92>> est vérifiée et
[[eq:92_2]]
[stem]
++++
  \mathrm{meas}(\partial \Omega_D) > 0\quad\text{et}\quad \partial \Omega^- = \{ x\in \partial \Omega ; (\beta \cdot n)(x) < 0\} \subset \partial \Omega_D
++++

_(iv)_ On pose stem:[q = \essinf_{x \in \Omega} (\gamma +\frac{1}{2} \mathbf{\beta}\cdot n)].
Le problème avec conditions de Robin <<problem_robin>>  non-homogènes est bien posé si
[[eq:92_3]]
[stem]
++++
  p \geq 0,\quad q \geq 0,\quad\text{et}\quad pq \neq 0.
++++
****

.Preuve
****
Nous prouvons _(i)_ et _(iv)_.

*Preuve de _(i)_*
En utilisant l'ellipticité de stem:[\mathcal{L}] et l'identité suivante(Formule de Green)
[stem]
++++
\int_\Omega u(\beta \cdot \nabla u) = -\frac{1}{2} \int_\Omega (\nabla \cdot \beta) u^2 + \frac{1}{2} \int_{\partial \Omega} (\beta \cdot n) u^2
++++
alors on a
[stem]
++++
\forall u \in H^1_0(\Omega),\quad a(u,u) \geq \alpha_0|u|^2_{1,\Omega} + p \|u\|^2_{0,\Omega}.
++++
En posant stem:[c=\min(0,\frac{p}{c_\Omega}] et en utilisant xref:math:analyse-fonctionnelle:lemma.adoc#lemmaB61[l'inégalité de Poincaré]  on a
[stem]
++++
\forall u \in H^1_0(\Omega),\quad a(u,u) \geq \left(\alpha_0+\frac{c}{c_\Omega}\right)|u|^2_{1,\Omega} \geq \sigma \|u\|^2_{1,\Omega}.
++++
avec stem:[\sigma=\frac{c_\Omega(c_\Omega\alpha_0+c)}{1+c^2_\Omega}].

Cela montre que stem:[a] est _coercive_ sur stem:[H^1_0(\Omega)].

Le caractère bien posé résulte alors du Lemme de Lax-Milgram pour les conditions de Dirichlet homogènes et de la <<proposition_dirichlet_non_homogene>> pour les conditions de Dirichlet non-homogènes.stem:[\square]

*Preuve de _(iv)_*
Notons stem:[a(u,v)=\int_\Omega \alpha \nabla u\cdot \nabla u + (\beta \cdot \nabla u) v + \mu u v + \int_{\partial \Omega} \gamma u v]. Nous avons l'inégalité suivante:
[stem]
++++
\forall u \in H^1(\Omega),\quad a(u,u) \geq \alpha_0|u|^2_{1,\Omega} + p \|u\|^2_{0,\Omega} + q\|u\|^2_{0,\partial \Omega}.
++++

Si stem:[p>0] et stem:[q\geq 0], la forme bilinéaire est _coercive_ sur stem:[H^1(\Omega)] avec comme constante stem:[\sigma = \min(\alpha_0,p)].

Si stem:[p\geq 0] et stem:[q > 0], la forme bilinéaire est _coercive_ sur stem:[H^1(\Omega)] grâce au xref:math:analyse-fonctionnelle:lemma.adoc#lemmaB63[Lemma B63].

Dans les deux cas, le caractère bien posé est obtenu par le Lemme de Lax-Milgram.stem:[\square]

Ceci termine les preuves de _(i)_ et _(iv)_. stem:[\blacksquare]
****

IMPORTANT: La coercivité est garantie si stem:[\alpha_0] est suffisamment grand c’est à dire que si la diffusion est dominante.

NOTE: Pour le problème Dirichlet homogène et non-homogène, stem:[f] peut être prise dans stem:[H^{-1}(\Omega)=\left(H_{0}^{1}(\Omega)\right)^{\prime} .]
Dans ce cas, le second membre du <<resume-formulation,problème générique>>  devient stem:[f(v)=\langle f, v\rangle_{H^{-1}, H_{0}^{1}},] et le problème est toujours bien posé. L'estimation de stabilité devient stem:[\|u\|_{1, \Omega} \leq c\|f\|_{-1, \Omega} .]

NOTE: Considérons le Laplacien avec conditions de Dirichlet homogène, i.e., étant donné stem:[f \in H^{-1}(\Omega),] résoudre stem:[-\Delta u=f] dans stem:[\Omega] avec la condition stem:[u_{\mid \partial \Omega}=0 .]
Alors, la formulation faible revient à chercher stem:[u \in H_{0}^{1}(\Omega)] telle que stem:[\int_{\Omega} \nabla u \cdot \nabla v=\langle f, v\rangle_{H^{-1}, H_{0}^{1}}] pour tout stem:[v \in H_{0}^{1}(\Omega)]
D'après le Théorème précédent stem:[(\mathrm{i})] avec stem:[\beta=0, \sigma=\mathcal{I},] et stem:[\mu=0,] le problème est bien posé. Cela signifie que l'opérateur stem:[(-\Delta)^{-1}: H^{-1}(\Omega) \rightarrow H_{0}^{1}(\Omega)] est un isomorphisme.

NOTE: L'unicité n'est pas une propriété triviale dans les espaces plus grands que stem:[H^{1}(\Omega).]
Par exemple, on peut construire des domaines dans lesquels cette propriété n'est pas  vérifiée dans stem:[L^{2}] pour le problème de Dirichlet

NOTE: Considérons le  <<resume-formulation,problème générique>>: si le champ d'advection stem:[\beta] disparaît et si la matrice de diffusion stem:[\sigma] est symétrique c.a. dans stem:[\Omega], la forme bilinéaire stem:[a] est symétrique et positive.
Par conséquent, en raison de la proposition ci-dessous,<<resume-formulation,le problème>> peut être reformulée en une forme variationnelle.
Pour le problème de Dirichlet homogène, la forme variationnelle en question est
[stem]
++++
\min _{v \in H_{0}^{1}(\Omega)}\left(\frac{1}{2} \int_{\Omega} \nabla v \cdot \sigma \cdot \nabla v+\frac{1}{2} \int_{\Omega} \mu v^{2}-\int_{\Omega} f v\right)
++++

.Proposition:
****
En plus des hypothèses du Lemme de Lax Milgram , supposons que:

(i) stem:[a] est  symétrique: stem:[a(u, v)=a(v, u), \forall u, v \in V]

(ii) stem:[a] est positive: stem:[a(u, u) \geq 0, \forall u \in V].

alors,  notant stem:[J(v)=\frac{1}{2} a(v, v)-f(v), u] résout le problème ci-dessous si et seulement si stem:[u] minimise stem:[J] sur stem:[V]

[stem]
++++
\left\{\begin{array}{l}\text { Trouver } u \in V \text { telle que } \\ a(u, v)=f(v), \quad \forall v \in V\end{array}\right.
++++
****

[[sec:adr-H1-conforming-approx]]
== Approximation conforme dans stem:[H^1]

NOTE: Cette section est en cours d'écriture

L’approximation élément fini est similaire à celle du Laplacian, de plus les variantes sur les conditions aux limites s’appliquent également: condition de Dirichlet non homogène, de Neumann ou de Robin.


Soit stem:[\Omega] un polyèdre dans stem:[\RR^d], soit stem:[\{\mathcal{T}_h\}] une famille de maillages de stem:[\Omega], et soit stem:[\{\hat{K}, \hat{P}, \hat{E}\}]  un élément fini Lagrange de référence du degré stem:[k \geq 1].

Soit stem:[P^k_{c,h}] l'espace d'approximation conformé stem:[H^1] défini par
[stem]
++++
P^k_{c,h}=\{v \in C^0(\bar{\Omega}); \quad \forall K \in \mathcal{T}_h v_{|K} \in \mathbb{P}^k (K) \}
++++
Pour obtenir une approximation conforme dans stem:[V], nous rajoutons les conditions aux limites, _i.e_, nous avons
[stem]
++++
V_h = P^k_{c,h} \cap V
++++
Dans le cas de conditions de Dirichlet homogène cela donne
[stem]
++++
V_h=\{ v_h \in P^k_{c,h} ;\ v_h = 0 \mbox{ sur } \partial \Omega\}
++++
Dans le cas Neumann et Robin, nous avons stem:[V_h=P^k_{c,h}].
Enfin dans le cas Dirichlet-Neumann, nous avons
[stem]
++++
V_h=\{v_h \in P^k_c; \ v_h = 0 \mbox{ sur } \partial \Omega_D\}
++++

Le problème discret s'ecrit
[env.problem]
****
Trouver stem:[u_h] dans stem:[V_h] telle que
[stem]
++++
a(u_h,v_h)=\ell(v_h), \quad \forall v_h \in V_h
++++
****

Nous cherchons à présent à estimer l'erreur stem:[u-u_h] en norme stem:[H^1] et stem:[L^2].


.Estimation stem:[H^1]
[env.theorem#thr-adr-conv]
****
Soit stem:[\Omega] un polyèdre dans stem:[\RR^d], soit stem:[\{\mathcal{T}_h\}] une famille de maillages de stem:[\Omega], et soit stem:[\{\hat{K}, \hat{P}, \hat{E}\}]  un élément fini Lagrange de référence du degré stem:[k \geq 1].
Nous avons stem:[\lim_{h\rightarrow 0} \|u-u_h\|_{1,\Omega} = 0] et pour stem:[\frac{d}{2} < s < k+1], il existe une constante stem:[c] telle que
[stem]
++++
\forall h, \quad \|u-u_h\| \leq c h^{s-1} |u|_{s,\Omega}
++++
****

.Estimation stem:[L^2]
[env.theorem#thr-adr-conv-l2]
****
Soient les hypothèse du théorème précédent, auxquelles nous ajoutons des hypothèses initiales, a des propriétés régularisantes
Nous avons stem:[\lim_{h\rightarrow 0} \|u-u_h\|_{1,\Omega} = 0] et pour stem:[\frac{d}{2} < s < k+1], il existe une constante stem:[c] telle que
[stem]
++++
\forall h, \quad \|u-u_h\|_{0,\Omega} \leq c h |u-u_h|_{1,\Omega}
++++
****

NOTE: nous n'avons pas défini ce que sont ces propriétés régularisantes. Nous supposerons qu'elles sont vérifiées.

.Exemple du Laplacien avec conditions de Dirichlet homogène en P1
[NOTE]
====
[stem]
++++
\forall h, \quad \|u-u\|_{0,\Omega} + h \|u-u_h\|_{1,\Omega} \leq c h^2 \|f\|_{0,\Omega}
++++
====

== Et après ?

Pour compléter l'étude de l'équation d'advection diffusion:

* [x] xref:advection-diffusion/numerical-experiments.adoc[Expériences numériques]
* [x] xref:advection-diffusion/dominant-advection.adoc[La perte de coercivité pour l'advection-diffusion]
