// -*- mode: adoc -*-
[[cha:appr-de-probl]]
= Approximation de problèmes coercifs

Dans ce chapitre, on s’intéresse à l’approximation de problèmes coercifs:

* le Laplacien et des variantes sur les conditions aux limites et le l’équation elle-même;
* l’élasticité linéaire qui permet de modéliser de petites déformations d’un milieu continu déformable.

[[sec:le-laplacien]]
== Le Laplacien

On s’instéresse dans cette section à l’_approximation élément fini conforme_ du problème suivant:

.Formulation forte du Laplacien
[env.problem#prob:1]
--
On cherche stem:[u] telle que
[[eq:64]]
\[
    \begin{split}
      -\Delta u &= f \mbox{ dans } \Omega\\
      u &= 0 \mbox{ sur } \partial \Omega
\end{split}
\]
--

[[sec:cadre-mathematique]]
=== Cadre Mathematique

On suppose que stem:[f \in L^2(\Omega)].

La formulation faible du problème <<prob:1>> est la suivante:

.Formulation faible pour des conditions de Dirichlet homogènes
[env.problem#prob:2]
--
On cherche stem:[u \in H^1_0(\Omega)] telle que
\[\label{eq:65}
    \int_\Omega \nabla u \cdot \nabla v =  \int_\Omega f\, v,\quad \forall v \in H^1_0(\Omega)
\]
--

[[sec:probleme-bien-pose]]
=== Problème bien posé

Introduisons

* stem:[V = H^1_0(\Omega)] doté de la norme
stem:[\|\cdot\|_{1,\Omega}] telle que
stem:[\|v\|_{1,\Omega} = (\|v\|^2_{0,\Omega} + \|\nabla v\|^2_{0,\Omega})^{1/2}]
* la forme bilinéaire stem:[a \in \mathcal{L}(V \times V, \R)]
telle que stem:[a(u,v) = \int_\Omega
  \nabla u \cdot \nabla v ]
* la forme linéaire stem:[\ell \in \mathcal{L}(V, \R)] telle que
stem:[l(v) = \int_\Omega   f \nabla v ]

Le problème <<prob:2>> s’écrit sous forme abstraite

[env.problem#prob:5]
--
On cherche stem:[u \in V] telle que
\[
    a(u, v) = \ell(v), \quad \forall v \in V
\]
--

L’espace stem:[V] est un espace de Hilbert et les formes stem:[a] et stem:[\ell] sont continues sur stem:[V\times V] et stem:[V] respectivement.

Il ne reste plus qu’à vérifier si le problème est bien posé (existence d’une solution unique).

Pour cela on utilise démontre la _coercivité_ de la forme bilinéaire stem:[a] sur stem:[V \equiv H^1_0(\Omega)].

Ceci se fait grâce au lemme suivant:

[env.lemma#lem:1]
--
Soit stem:[\Omega] un ouvert borné de stem:[\R].
Il existe une constante stem:[c_\Omega] (dépendente de stem:[\Omega] telle que
\[
    \forall v \in H^1_0(\Omega),\quad \|v\|_{0,\Omega} \le c_\Omega \|\nabla v\|_{0,\Omega}
\]
--

[[rem:24]]
NOTE: stem:[c_\Omega] est homogène à une longeur et peut être interprétée comme une mesure caractéristique de stem:[\Omega].

Grâce à l’inégalité de Poincaré, on a le résultat suivant

[env.proposition#prop:7]
--
La forme bilinéaire stem:[a] du problème <<prob:2>> est _coercive_
--

[env.proof]
--
On note tout d’abord que par l’inégalité de Poincaré et la définition de
stem:[\|\cdot\|_{1,\Omega}]
[[eq:68]]
\[
      \|v\|^2_{1,\Omega} \le (1 + c^2_\Omega) \|\nabla v\|^2_{0,\Omega}
\]
On en déduit que
[[eq:67]]
\[
\forall v \in H^1_0(\Omega),\quad a(v,v) = \|\nabla v\|^2_{0,\Omega} \ge \frac{1}{1+c^2_\Omega} \|v\|^2_{1,\Omega}
\]

Le Lemme de Lax-Milgram <<thr:12>> permet alors de conclure sur l’existence d’une solution unique pour le problème <<prob:2>>.
--

[[sec:appr-conf]]
=== Approximation conforme

On utilise une approximation conforme par éléments finis de Lagrange.

On considère stem:[\Omega] un polygone ou polyhèdre régulier de stem:[\RR^2] ou stem:[\RR^3] respectivement et un maillage stem:[\calTh = \{K_e\}_{e=1...\Ne}] de stem:[\Omega].

On considère un élément fini de référence stem:[(\hat{K},\hat{P},\hat{\Sigma})] tel que stem:[\Pk \subset \hat{P}] et stem:[k+1 > \frac{d}{2}], voir le théorème <<thr:16>>.

On note
[[eq:70]]
\[
  L^k_{c,h} = \{ v_h \in C^0(\bar{\Omega}); \forall K \in \mathcal{T}_h,\ v_h   \circ T_K \in \hat{P}\}
\]
où stem:[T_K] est la tranformation géométrique de stem:[\hat{K}] dans stem:[K].

* Si on utilise stem:[\hat{P}=\Pk{k}] on a stem:[L^k_{c,h} = P^k_{c,h}].
* Si on utilise stem:[\hat{P}=\Qk{k}] on a stem:[L^k_{c,h} = Q^k_{c,h}].

Afin de construire un espace d’approximation conforme stem:[V_h \subset V =H^1_0(\Omega)] on prend
\[
\label{eq:71}
V_h = L^k_{c,h} \cap H^1_0(\Omega)
\]
c’est à dire que les fonctions de stem:[V_h] satisfont les conditions aux limites outre le fait d’être dans stem:[L^k_{c,h}].

Le problème discret s’écrit alors

[env.problem#prob:6]
--
Trouver stem:[u_h \in V_h] telle que
\[
    a(u_h,v_h) = \ell(v_h),\, \forall v_h \in V_h
\]
--

qui est bien posé (existence et unicité de stem:[u_h]) car stem:[a] est coercive sur stem:[V] et que stem:[V_h \subset V].

On a le résultat suivant:

[env.theorem#thr:17]
--
On suppose que stem:[u] solution de <<prob:2>> est dans
stem:[H^{k+1}(\Omega) \cap   H^1_0(\Omega)], alors il existe une constante stem:[c_1] telle que pour tout stem:[h]
[[eq:73]]
\[
    \|u-u_v\|_{1,\Omega} \le c_1 h^k |u|_{k+1,\Omega}
\]
et il existe
une constante stem:[c_2] telle que pour tout stem:[h]
[[eq:74]]
\[
    \|u-u_v\|_{0,\Omega} \le c_2 h^{k+1} |u|_{k+1,\Omega}
\]
--

[env.proof]
--
La preuve de (<<eq:73>>) est obtenue grâce au lemme de Cea (<<eq:cea>>) et du théorème d’interpolation (<<eq:62>>).

La preuve de (<<eq:74>>) est obtenue grâce au lemme d’Aubin-Nitsche qui permet d’affirmer qu’il existe une constante stem:[c] telle que

[[eq:75]]
\[
    \|u-u_h\|_{0,\Omega} \leq c h |u-u_h|_{1,\Omega}
\]
et donc que (<<eq:74>>) se déduit de (<<eq:74>>).
--

[[sec:impl-en-feelpp]]
=== Implémentation avec {feelpp}

Avec {feelpp}, on ne construit pas explicitement l’espace stem:[V_h] mais stem:[L^k_{c,h}].

Le traitement des conditions aux limites de Dirichlet du problème (<<eq:64>>) peut être effectué de diverses façons, nous en verrons une.

Commencons par le maillage, dans un premier temps nous définissons le type du maillage contenant soit des éléments de type simplexe (segment,triangle, tetrahèdre) ou de type hypercube (segment, quadrangle, hexahèdre).

[source,cpp]
----
  // un maillage de simplexe dans $\R$ telle que la transformation
  // géométrique $T_K,\ K \in \calTh$  soit affine
  typedef Mesh<Simplex<d,1> > mesh_type;

  // un maillage d'hypercube dans $\R$ telle que la transformation
  // géométrique $T_K,\ K \in \calTh$  soit affine en chacune des variables
  // typedef Mesh<Hypercube<d,1> > mesh\_type;

  // generate the mesh associated to the unit square $[0,1]^2$ using triangles
  auto mesh = unitSquare();
----

[[rem:25]]
NOTE: Le mot clé `auto` permet de faire de l’inférence de type, pour plus de détails consultez
link:http://fr.wikipedia.org/wiki/C%2B%2B11#Inf.C3.A9rence_de_types[la page C++11 de Wikipedia].

Ensuite nous pouvons définir l’espace stem:[L^k_{c,h}],

[source,cpp]
----
  // Vh est une structure de donnée allouée dynamiquement
  auto Vh = Pch<1>( mesh );
  // u est un élément de Vh
  auto u = Vh->element();
  // u est un autre élément de Vh
  auto u = Vh->element();
----

À présent, nous définissons les formes bilinéaires stem:[a] et stem:[\ell] qui sont respectivement des formes bilinéaires et linéaires.

[source,cpp]
----
  auto a = form2( _test=Vh, _trial=Vh ); <1>
  a = integrate( _range=elements(mesh), _expr=gradt(u)*trans(grad(v)) ); <2>

  auto l = form1( _test=Vh ); <3>
  l = integrate( _range=elements(mesh), _expr=f*id(v) ); <4>
----
<1> stem:[a \in \mathcal{L}(V_h \times V_h,\ \RR)]
<2> stem:[a = \sum_{e=1...\Ne} \int_{K_e} \nabla \varphi_j \cdot \nabla \varphi_i,\quad  i,j=1...,\dim{V_h}]
<3> stem:[\ell \in \mathcal{L}(V_h,\ \RR)]
<4> stem:[\ell = \sum_{e=1...\Ne} \int_{K_e} f  \varphi_i,\quad  i=1...,\dim{V_h}]


Afin de traiter les conditions aux limites de Dirichlet homogènes, on peut utiliser le mot-clé `on` qui permet de les imposer de manière forte.

[source,cpp]
----
  a += on(_range=boundaryfaces(mesh), _element=u, _rhs=l, _expr=constant(0.) );
----

[[rem:26]]
NOTE: Le mot-clé `constant` permet de transformer une type numérique ( entier, flottant) en une expression utilisable par le langage de {feelpp}.
Notez également l’opération `+=` qui permet de rajouter le traitement des conditions de Dirichlet tout en gardant les contributions précédentes.
L’opération `=` aurait d’abord remis à stem:[0] les entrées de la matrice associée à stem:[a].

Enfin nous pouvons résoudre le problème <<prob:6>>

[source,cpp]
----
  a.solve( _rhs=l, _solution=u );
----

Le listing complet

[[sec:cond-aux-limit]]
=== Conditions aux limites

[[sec:cond-aux-limit-1]]
==== Conditions aux limites de Dirichlet non homogène


On suppose toujours stem:[f \in L^2(\Omega)] et on se donne une fonction stem:[g \in C^{0,1}(\partial \Omega)]

[stem:[g] est Lipschitzienne
sur stem:[\partial
\Omega]].

On s’intéresse au problème suivant:

[env.problem#prob:7]
--
On cherche stem:[u : \Omega \rightarrow \RR] telle que

[[eq:76]]
\[
    \begin{split}
    -\Delta u &= f \mbox{ dans } \Omega\\
    u &= g \mbox{ sur } \partial \Omega
    \end{split}
\]
--

[[rem:27]]
NOTE: L’hypothèse stem:[g \in C^{0,1}(\partial \Omega)] permet d’affirmer qu’il existe stem:[u_g \in H^1(\Omega)] telle que stem:[u_{g_{|\partial \Omega}} = g].

On se ramène au problème avec conditions de Dirichlet homogène en faisant le change d’inconnue stem:[u_0=u-u_g] et on s’intéresse au problème suivant:


[env.problem#prob:8]
--
On cherche stem:[u_0 \in H^1_0(\Omega)] telle que
[[eq:77]]
\[
    a(u_0,v) = \ell(v) - a(u_g,v),\quad \forall v \in H^1_0(\Omega)
\]
--

Ce problème est _bien posé_ d’après Lax-Milgram, voir section précédente.


[env.theorem#thr:18]
--
On suppose que stem:[u] solution de [prob:8] est dans stem:[H^{k+1}(\Omega) \cap   H^1_0(\Omega)],
alors il existe une constante stem:[c_1] telle que pour tout stem:[h]

[[eq:73]]
\[
    \|u-u_v\|_{1,\Omega} \le c_1 h^k |u|_{k+1,\Omega}
\]
et il existe une constante stem:[c_2] telle que pour tout stem:[h]
[[eq:74]]
\[
    \|u-u_v\|_{0,\Omega} \le c_2 h^{k+1} |u|_{k+1,\Omega}
\]
--

Avec {feelpp}, les conditions Dirichlet non-homogènes sont traitées par exemple avec le mot-clé `on`.


.Conditions de Dirichlet non homogènes
[source,cpp]
----
  auto g = sin(2*pi*Px() ); <1>
  <2>
  ...
  a += on( _range=boundaryfaces(mesh), _expr=g ); <3>
----
<1>  définition de la fonction, p.ex stem:[g=sin(2 \pi x)]
<2>  définition de stem:[a]
<3>  ajout des conditions de Dirichlet non-homogènes

[[rem:28]]
NOTE: Il n’y a pas besoin de rajouter le terme stem:[a(u_g,v)] au second membre stem:[\ell(v)], il est pris en compte automatiquement par `on`.

Voici le listing complet de l’exemple du laplacien avec conditions de Dirichlet non-homogène

[[sec:cond-aux-limit-2]]
=== Condition aux limites de Neumann

Étant donnés un réel stem:[\mu] strictement positif, stem:[f \in L^2(\Omega)] et stem:[g \in L^2(\partial \Omega)], on s’intéresse au problème suivant:


[env.problem#prob:9]
--
On cherche stem:[u : \Omega \rightarrow \RR] telle que
[[eq:78]]
\[
    \begin{split}
      -\Delta u + \mu u &= f, \mbox{ dans } \Omega\\
      \partial_\Next u &= g, \mbox{ sur } \partial\Omega
    \end{split}
\]
--

où stem:[\partial_\Next u = \nabla u \cdot \Next = \sum_{i=1}^d n_i \partial_i u] dénote la dérivée normale de stem:[u] avec stem:[\Next=(n_1,...,n_d) \in \RR^d] la normale extérieure unitaire en un point du bord de stem:[\Omega].

La formulation faible s’écrit


[env.problem#prob:13]
--
On cherche stem:[u \in H^1(\Omega)] telle que
[[eq:79]]
\[
    a( u, v ) = \ell(v),\ \forall v \in H^1(\Omega)
\]
avec
[[eq:80]]
\[
    a( u, v ) =  \int_\Omega \nabla u \cdot \nabla v + \mu u v
\]
et
[[eq:81]]
\[
    \ell( v ) =  \int_\Omega f v + \int_{\partial\Omega} g v
\]
--


On a
[[eq:82]]
\[
  a(v, v) =  \int_\Omega \nabla v \cdot \nabla v + \mu v v \ge \min(1,\mu)
  \int_\Omega \nabla v \cdot \nabla v +  v v  = \min(1,\mu) \|v\|_{1,\Omega}, \quad
  \forall v \in H^1(\Omega)
\]
ce qui nous permet d’affirmer que stem:[a] est coercive sur stem:[H^1(\Omega)] et que le problème <<prob:13>> est bien posé grâce à Lax-Milgram.

On peut approcher le problème <<prob:13>> par des éléments finis de Lagrange.

On utilise la formulation développée dans la section <<sec:appr-conf>>
[env.problem#prob:13_1]
--
On cherche stem:[u_h \in P^k_{c,h}] tel que
\[
a_h(u_h,w_h)=\ell(w_h), \quad \forall w_h \in P^k_{c,h}
\]
--

NOTE: Par rapport aux conditions de Dirichet, les conditions de Neumann sont directement (*naturellement*) traitées par la formulation faible.
Elles ne sont pas directement imposées dans l'espace et les fonctions tests peuvent prendre des valeurs non-nulles au bord.
Ces conditions sont traitées de manière approchée et non pas exacte.

L'analyse du problème <<prob:13_1>> est identique par le théorème <<thr:17>> aux mêmes estimations que dans le cas Dirichlet homogène.

==== Cas stem:[\lambda=0]

Le cas stem:[\lambda=0] présente quelques difficultés techniques.

On a
[env.problem#prob:13_2]
--
On cherche stem:[u : \Omega \rightarrow \RR] telle que
[[eq:78.1]]
\[
    \begin{split}
      -\Delta u &= f, \mbox{ dans } \Omega\\
      \partial_\Next u &= g, \mbox{ sur } \partial\Omega
    \end{split}
\]
--

NOTE: On observe ici qu'une condition nécessaire d'existence de solution est que
[stem]
++++
\int_\Omega f + \int_{\partial \Omega} g = 0
++++
de par le *théorème de la divergence*.

NOTE: la deuxième observation est que la solution de <<prob:13_2>> est connue à une constante additive près: si stem:[u] est solution  et stem:[c\in \RR] alors stem:[u+c] est également solution.

Il convient alors de chercher la solution dans l'espace fonctionel suivant
[env.equation]
--
H^1_*(\Omega) = \{ v \in H^1(\Omega):\quad \int_\Omega v  = 0 \}
--

La formulation faible du problème <<prob:13_2>>  s'écrit alors
[env.problem#prob:13_3]
--
On cherche stem:[u\in H^1_*(\Omega)], telle que
\[
a(u,v) = \ell(v) \quad \forall v\in H^1_*(\Omega)
\]
avec stem:[a(u,v)=\int_\Omega \nabla u \cdot \nabla v].
--

Le caractère bien posé du problème <<prob:13_3>> résulte de la coercivité de stem:[a] sur stem:[H^1_*(\Omega)] qui elle-même résulte du Lemme suivante


[env.lemma]
.Lemme d'inégalité de Poincaré-Wirtinger
--
Soit stem:[\Omega] un ouvert borné de stem:[\RR^d], il existe une constante stem:[C_\Omega] telle que
\[
\|v\| \leq C_\Omega \|\nabla v\|_{0,\Omega},\quad \forall v \in H^1_*(\Omega)
\]
--

Le problème <<prob:13_3>> peut être approché par des éléments finis de Lagrange ce qui conduit au problème discret suivant
[env.problem#prob:13_4]
--
On cherche stem:[u_h \in P^k_{c,h}] telle que
a_h(u_h,v_h)=\ell(v_h) \quad \forall v_h\in P^k_{c,h}
--

NOTE: L'espace d'approximation stem:[P^k{c,h}] n'est pas conforme dans stem:[H^1_*(\Omega)]

[NOTE]
====
le problème <<prob:13_4>> est *singulier*, il a une infinité de solution.
L'une d'entre elle peut être approchée par une méthode itérative de type gradient conjugué.
Notons stem:[u^*_h] cette solution alors la solution à moyenne nulle est
[stem]
++++
u_h=u^*_h-\frac{1}{|\Omega|}\int_\Omega u^*_h
++++
Il s'agit donc d'effectuer a posteriori du calcul un post-processing pour se ramener à la solution à moyenne nulle.
Dans {feelpp} on utilisera la fonction `mean`
[source,cpp]
----
// ...
// u est la solution du problème discret
a.solve(_rhs=l,_solution=u);

// calcul de la valeur moyenne de u
double meanu = mean(_range=elements(mesh),_expr=idv(u))(0,0);

// calcul de la solution à moyenne nulle u = u - meanu
u.add(-meanu);
----
====


[[sec:cond-aux-limit-robin]]
=== Conditions aux limites de Robin


Étant donnés un réel stem:[\mu] strictement positif, stem:[f \in L^2(\Omega)] et stem:[g \in L^2(\partial \Omega)], on s’intéresse au problème suivant:

[env.problem#prob:14]
--
On cherche stem:[u : \Omega \rightarrow \RR] telle que
[[eq:83]]
\[
    \begin{split}
      -\Delta u  &= f, \mbox{ dans } \Omega\\
      \mu u + \partial_\Next u &= g, \mbox{ sur } \partial\Omega.
    \end{split}
\]
--

La formulation faible s’écrit


[env.problem#prob:15]
--
On cherche stem:[u \in H^1(\Omega)] telle que
\[\label{eq:84}
    a( u, v ) = \ell(v),\ \forall v \in H^1(\Omega)
\]
avec
[[eq:85]]
\[
    a( u, v ) =  \int_\Omega \nabla u \cdot \nabla v + \int_{\partial     \Omega} \mu u v
\]
et
[[eq:86]]
\[
    \ell( v ) =  \int_\Omega f v + \int_{\partial\Omega} g v
\]
--

On a
[[eq:69]]
\[
  \begin{split}
    a(v, v) & =  \int_\Omega \nabla v \cdot \nabla v + \int_{\partial\Omega} \mu v v \\
    & \geq \min(1,\mu)\left( \int_\Omega \nabla v \cdot \nabla v +
      \int_{\partial\Omega} v v\right)  \\
    &\geq \min(1,\mu) \|v\|_{1,\Omega}, \quad \forall v \in H^1(\Omega)
  \end{split}
\]

La forme bilinéaire stem:[a] est donc coercive et le problème <<prob:15>> est bien posé grâce à Lax-Milgram.

On considère le problème discret suivant

[env.problem#prob:11]
--
On cherche stem:[u_h \in P^k_{c,h}(\Omega)] telle que
[[eq:87]]
\[
    a_h(u_h,v_h) = \ell(v_h)\quad \forall v_h \in P^k_{c,h}
\]
--

Le problème est _bien posé_ (stem:[P^k_{c,h} \subset H^1(\Omega)]).

NOTE: Comme pour le problème avec conditions de Neumann, les fonctions tests peuvent prendre des valeurs non nulles au bord.
Les conditions de Robin(ou Fourier) ne sont satisfaites que de manière _approchée_ et non pas _exacte_.

La convergence de stem:[u_h] est donnée par le théorème <<thr:17>>.

Considérons stem:[\Omega=[0,1]^2] et les données stem:[\mu=0.01], stem:[f=1] et stem:[g=0].


[[sec:advection-diffusion]]
== Advection-diffusion-réaction avec diffusion dominante


On s’intéresse au problème suivant:


[env.problem#prob:10]
--
On cherche stem:[u : \Omega \rightarrow \RR] telle que
[[eq:30]]
\[
    \begin{split}
      -\nabla \cdot ( \mathbf{\alpha} \nabla u  ) + \mathbf{\beta} \cdot \nabla u + \mu u &= f
      \mbox{ dans } \Omega\\
      \mathcal{B} u &= 0 \mbox{ sur } \partial \Omega\\
    \end{split}
\]
--

où stem:[\mathcal{B}] est l'opérateur prenant en compte les conditions aux limites.
La variation sur les conditions aux limites de la section [sec:cond-aux-limit] s’appliquent.

* stem:[\mathcal{B}u=u] condition de Dirichlet
* stem:[\mathcal{B}u=(\mathbf{\alpha}\nabla{u}) \cdot n] condition de Neumann
* stem:[\mathcal{B}u=\gamma u + (\mathbf{\alpha} \nabla u )\cdot n] condition de Robin

Les différents termes de l'opérateur ont une interprétation physique

* stem:[-\nabla \cdot ( \mathbf{\alpha} \nabla u  )] est un terme de link:https://en.wikipedia.org/wiki/Diffusion[diffusion],

* stem:[\mathbf{\beta} \cdot \nabla u] est un terme d'link:https://en.wikipedia.org/wiki/Advection[advection],

* stem:[\mu u] est un terme de réaction (production ou destruction).

Ce type d’équation est très fréquente en ingéniérie, biologie ou encore finance.


[NOTE]
.Transfert de chaleur
====
stem:[u] is the temperature, stem:[\alpha=\kappa \mathcal{I}] où stem:[\kappa] est la link:https://fr.wikipedia.org/wiki/Conductivité_thermique[_conductivité thermique_], stem:[\beta] est le champ d'écoulement, stem:[\mu = 0] et stem:[f] est chaleur apportée exterieurement par unité de volume.
====

[NOTE]
.Advection Diffusion
====
stem:[u] est la concentration d'un link:https://en.wikipedia.org/wiki/Solution[soluté] transportée dans un champ d'écoulement stem:[\beta].
La matrice stem:[\alpha] modélise la diffusivité du soluté soit de la link:https://en.wikipedia.org/wiki/Molecular_diffusion[diffusion moléculaire] soit du link:https://en.wikipedia.org/wiki/Turbulence[mélange turbulent] du fluide transporteur.
La production ou destruction par réaction chimique is pris en compte par le terme linéaire stem:[\mu u].
Le second membre stem:[f] modélise les sources ou puits.

====

On suppose que stem:[\mathbf{\alpha} \in [L^{\infty}(\Omega)\]^{d\times d}], stem:[\mathbf{\beta} \in [L^{\infty}(\Omega)\]^d], stem:[\nabla \cdot \mathbf{\beta} \in L^{\infty}(\Omega)] et stem:[\mu \in L^\infty(\Omega)].

On suppose que l’opérateur stem:[\mathcal{L}] tel que stem:[\mathcal{L} u = -\nabla \cdot ( \alpha \nabla u ) + \beta \cdot \nabla u + \mu u] est _elliptique_ au sens suivant:


[env.definition#def:39]
--
L’opérateur stem:[\mathcal{L}] est _elliptique_ si il existe une constante stem:[\alpha_0] telle que presque pour tout stem:[x\in\Omega]
[[eq:88]]
\[
    \forall \xi=(\xi_1, \ldots , \xi_n)\in\RR^n,\quad { \sum_{i,j=1}^n  \alpha_{ij}(x) \, \xi_i \, \xi_j  \ge \alpha_0 \, \| \xi \|^2 }
\]
--

[[rem:29]]
TIP: Le Laplacien est dans la catégorie des opérateurs elliptiques, il correspond à stem:[\mathbf{\beta} = 0], stem:[\mu = 0] et stem:[\mathbf{\alpha}=\mathcal{I}_d] avec stem:[\mathcal{I}_d] la matrice identité de stem:[\RR^{d\times d}].

=== Condition de Dirichlet homogène

Nous imposons stem:[u=0] sur stem:[\partial \Omega].

Nous multiplions stem:[\mathcal{L} u = f] par une fonction test (suffisamment régulière) s'annulant au bord et on intègre sur stem:[\Omega].
En intégrant par parties (formule de Green) nous avons

[[eq:adr-green]]
[stem]
++++
\int_\Omega \nabla \cdot (\mathbf{\alpha} \nabla u )  v  = \int_\Omega (\mathbf{\alpha} \nabla u ) \cdot \nabla v -\int_{\partial \Omega} ((\sigma \nabla u)\cdot n) v
    \nabla u) v + \mu u v
++++
ce qui donne
[stem]
++++
\int_\Omega (\mathbf{\alpha} \nabla u ) \cdot \nabla v + (\mathbf{\beta} \cdot
    \nabla u) v + \mu u v = \int_\Omega f v
++++

Afin que les intégrales sur stem:[\Omega] aient un sens, nous demandons par exemple que stem:[u] et stem:[v] aient la régularité suivante:
[stem]
++++
u\in H^1(\Omega)\quad\text{et}\quad v\in H^1(\Omega).
++++

Comme stem:[u\in H^1(\Omega)], le théorème <<toto>> implique que stem:[u] ait une _trace_ sur le bord.
Comme stem:[u_{|\partial \Omega} = 0], on cherche en fait stem:[u] dans stem:[H^1_0(\Omega)].
Les fonctions tests sont également prises dans stem:[H^1_0(\Omega)] ce qui donne la formulation faible suivante
[env.problem#prob:12]
--
On cherche stem:[u \in H^1_0(\Omega)] telle que
[[eq:89]]
\[
    a(u,v) = \ell(v) \quad \forall v \in H^1_0(\Omega)
\]
avec
[[eq:90]]
\[
    a(u,v)=\int_\Omega (\mathbf{\alpha} \nabla u ) \cdot \nabla v + (\mathbf{\beta} \cdot
    \nabla u) v + \mu u v
\]
et
[[eq:91]]
\[
    \ell(v) = \int_\Omega f v
\]
--

Nous avons le résultat suivant
.Une solution du problème faible est solution du problème fort
[env.proposition#prop:prob12]
--
Si stem:[u] résout <<eq:89>>, alors stem:[\mathcal{L}u=f] presque partout dans stem:[\Omega] et stem:[u=0] presque partout sur stem:[\partial \Omega].
--
[env.proof]
--
Soit stem:[\phi\in \mathcal{D}(\Omega)] et stem:[u] une solution de <<prob:12>>.
On a
\[
\begin{split}
\left\langle-\nabla \cdot (\alpha \nabla u), \phi \right\rangle_{\mathcal{D}',\mathcal{D}} &= \left\langle (\alpha \nabla u), \nabla \phi \right\rangle_{\mathcal{D}',\mathcal{D}} = \int_\Omega \alpha \nabla u \cdot \nabla \phi \\
 & = \int_\Omega (f - \beta \cdot \nabla u - \mu u ) \phi,
\end{split}
\]
ce qui donne stem:[\langle\mathcal{L}u,\phi\rangle_{\mathcal{D}',\mathcal{D}} = \int_\Omega f \phi].
Or stem:[\mathcal{D}(\Omega)] est _dense_ dans stem:[L^2(\Omega)], nous avons donc que stem:[\mathcal{L}u=f] dans stem:[L^2(\Omega)].
C'est à dire que stem:[\mathcal{L}u=f] presque partout dans stem:[\Omega].
Enfin stem:[u=0] presque partout sur stem:[\partial \Omega] par définition de stem:[H^1_0(\Omega)] d'après le théorème <<toto>> stem:[\blacksquare]
--

=== Conditions de Dirichlet Non homogène

Nous imposons stem:[u=0] sur stem:[\partial \Omega] où stem:[g : \partial \Omega \rightarrow \RR] est une fonction donnée.

Nous supposons que stem:[g] soit suffisamment régulière telle qu'il existe un relèvement stem:[u_g] de stem:[g] dans stem:[H^1(\Omega)], c'est à dire qu'il existe une fonction stem:[u_g] de stem:[H^1(\Omega)] telle que stem:[u_g=g] sur stem:[\partial \Omega].

[env.problem#prob:12_1]
--
On cherche stem:[u \in H^1(\Omega)] telle que
\[
u=u_g+\phi,\quad \phi \in H^1_0(\Omega)
\]
où stem:[\phi] est solution de
[[eq:89_1]]
\[
    a(\phi,v) = \ell(v) - a(u_g,v) \quad \forall v \in H^1_0(\Omega)
\]
avec
[[eq:90_1]]
\[
    a(u,v)=\int_\Omega (\mathbf{\alpha} \nabla u ) \cdot \nabla v + (\mathbf{\beta} \cdot
    \nabla u) v + \mu u v
\]
et
[[eq:91_1]]
\[
    \ell(v) = \int_\Omega f v
\]
--

[env.proposition#prop:prob12_1]
--
Soit stem:[g\in H^{\frac{1}{2}}(\partial \Omega)], si stem:[u] résout <<prob:12_1>>, alors stem:[\mathcal{L}u=f] presque partout dans stem:[\Omega] et stem:[u=g] presque partout sur stem:[\partial \Omega].
--


[env.proof]
--
La preuve est similaire à celle de <<prob:12>>.
--

NOTE: Lorsque l'opérateur stem:[\mathcal{L}] est le Laplacien, <<prob:12_1>> est appelé un _problème de Poisson_.


=== Conditions de Neumann

Soit une fonction stem:[g:\partial \Omega \rightarrow \RR], nous voulons imposer stem:[\mathcal{B}u=(\alpha \nabla u)\cdot n = g]  sur stem:[\partial \Omega].

NOTE: Dans le cas où stem:[\alpha = \mathcal{I}], la condition de Neumann correspond à spécifier la dérivée normale de stem:[u] car stem:[\nabla u \cdot n = \partial_n u = \frac{\partial u}{\partial n}].

Nous procédons de la même façon que précédemment et en utilisant la condition de Neumann dans l'intégrale de surface <<eq:adr-green>>, on obtient la formulation faible suivante:

[env.problem#prob:12_2]
--
On cherche stem:[u \in H^1(\Omega)] telle que

[[eq:89_2]]
\[
    a(u,v) = \ell(v) \quad \forall v \in H^1(\Omega)
\]
avec
[[eq:90_2]]
\[
    a(u,v)=\int_\Omega (\mathbf{\alpha} \nabla u ) \cdot \nabla v + (\mathbf{\beta} \cdot
    \nabla u) v + \mu u v
\]
et
[[eq:91_2]]
\[
    \ell(v) = \int_\Omega f v + \int_{\partial \Omega} g v
\]
--

[env.proposition#prop:prob12_2]
--
Soit stem:[g\in L^2(\partial \Omega)], si stem:[u] résout <<prob:12_2>>, alors stem:[\mathcal{L}u=f] presque partout dans stem:[\Omega] et stem:[\alpha \nabla u \cdot n = g] presque partout sur stem:[\partial \Omega].
--
[env.proof]
--
En prenant les fonctions tests dans stem:[\mathcal{D}(\Omega)] , on a immediatement que stem:[\mathcal{L}u = f] presque partout dans stem:[\Omega].
Nous avons donc que stem:[-\nabla \cdot (\alpha \nabla u ) \in L^2(\Omega)].
Le corollaire <<B59>> implique que stem:[\alpha \nabla u \cdot n \in H^{\frac{1}{2}}(\partial \Omega)' = H^{-\frac{1}{2}}(\partial \Omega)] du fait que
\[
\forall \phi \in H^{\frac{1}{2}}(\partial \Omega), \quad \left\langle\alpha \nabla u \cdot n, \phi\right\rangle_{H^{-\frac{1}{2}},H^{\frac{1}{2}}} = \int_{\Omega} -\nabla \cdot (\alpha \cdot \nabla u) u_\phi + \int_\Omega \alpha \nabla u \cdot \nabla u_\phi
\]
où stem:[u_\phi \in H^1(\Omega)] est un relèvement de stem:[\phi] dans stem:[H^1(\Omega)].
On a alors que <<prob12_2>> donne
\[
\forall \phi \in H^{\frac{1}{2}}(\partial \Omega), \quad \left\langle\alpha \nabla u \cdot n, \phi\right\rangle_{H^{-\frac{1}{2}},H^{\frac{1}{2}}} = \int_{\partial \Omega} g \phi
\]
montrant que stem:[\alpha \nabla u \cdot n = g] dans stem:[H^{-\frac{1}{2}}(\partial \Omega)] et donc, par conséquent, dans stem:[L^2(\Omega)] du fait que stem:[g] soit dans stem:[L^2(\Omega)].stem:[\blacksquare]
--


=== Conditions mixtes Dirichlet-Neumann

NOTE: documentation en cours


=== Conditions de Robin

NOTE: documentation en cours

Soient deux fonctions stem:[g,\gamma : \partial \Omega \rightarrow \RR], nous voulons imposer stem:[\gamma u + (\alpha \nabla u)\cdot n = g] sur stem:[\partial \Omega].
En utilisant la relation sur l'intégrale de surface <<eq:adr-green>>, nous avons la formulation faible suivante


[env.problem#prob:12_4]
--
On cherche stem:[u \in H^1(\Omega)] telle que

[[eq:89_4]]
\[
    a(u,v) + \int_{\partial \Omega} \gamma u v = \ell(v) \quad \forall v \in H^1(\Omega)
\]
avec
[[eq:90_4]]
\[
    a(u,v)=\int_\Omega (\mathbf{\alpha} \nabla u ) \cdot \nabla v + (\mathbf{\beta} \cdot
    \nabla u) v + \mu u v
\]
et
[[eq:91_4]]
\[
    \ell(v) = \int_\Omega f v + \int_{\partial \Omega} g v
\]
--

[env.proposition#prop:prob12_4]
--
Soit stem:[g\in L^2(\partial \Omega)] et stem:[\gamma \in L^\infty(\partial \Omega].
Si stem:[u] résout <<prob:12_4>>, alors stem:[\mathcal{L}u=f] presque partout dans stem:[\Omega] et stem:[\gamma u + \alpha \nabla u \cdot n = g] presque partout sur stem:[\partial \Omega].
--
[env.proof]
--
On procède de manière similaire aux preuves précédentes. stem:[\blacksquare]
--

Nous récapitulons dans la table suivante les différentes formulations

.Formulation faible pour différentes conditions aux limites
|===
| Problème | Espace | Forme bilinéaire | Forme linéaire

|Dirichlet homogène
| stem:[H^1_0(\Omega)]
| stem:[a(u,v)]
| stem:[\int_\Omega f v]

| Neumann
| stem:[H^1(\Omega)]
| stem:[a(u,v)]
| stem:[\int_\Omega f v + \int_{\partial \Omega} g v]

|Dirichlet Neumann
| stem:[H^1_{\partial \Omega_D}(\Omega)]
| stem:[a(u,v)]
| stem:[\int_\Omega f v + \int_{\partial \Omega_N} g v]

| Robin (Fourier)
| stem:[H^1(\Omega)]
| stem:[a(u,v) + \int_{\partial \Omega} \gamma uv]
| stem:[\int_\Omega f v + \int_{\partial \Omega} g v]

|===

.Résumé
[NOTE]
====
Les problèmes considérés précédent se mettent tous sous la forme suivante, sauf le problème de Dirichlet non homogène
[[eqpbadr]]
[stem]
++++
\left\{\begin{array}{l}
\text{ Chercher } u \in V \text{ telle que}\\
a(u,v)=f(v), \quad \forall v \in V
\end{array}\right.
++++
où stem:[V] est un espace de _Hilbert_ satisfaisant
[stem]
++++
H^1_0(\Omega) \subset V \subset H^1(\Omega)
++++

Dans le cas de conditions de *Dirichlet non-homogènes*, nous avons stem:[u\in H^1(\Omega)] et stem:[u=u_g+\phi] où stem:[u_g] est un relèvement de la donnée au bord stem:[g] et stem:[\phi] résout le <<eqpbadr,problème générique>> avec des conditions de Dirichlet homogènes.
====

.Conditions aux limites essentielles et naturelles
[NOTE]
====
Il est important d'observer le traitement différent entre les conditions de Dirichlet et Neumann ou Robin conditions.

Les conditions de Dirichlet sont imposées explicitement dans l'espace fonctionnel où la solution est recherchée, et les fonctions de test disparaissent (_i.e._ stem:[v=0]) sur la partie correspondante de la frontière.
Pour cette raison, les conditions de Dirichlet sont souvent appelées conditions aux limites _essentielles_ .

Les conditions de Neumann et Robin ne sont pas imposées par le cadre fonctionnel mais par la formulation faible elle-même.
Le fait que les fonctions test ont des degrés de liberté sur la partie correspondante de la frontière est suffisant pour faire respecter les conditions limites en question.
Pour cette raison, ces conditions sont souvent appelées conditions aux limites _naturelles_.
====

[[sec:adr-coercivity]]
=== Coercivité

NOTE: Cette section est en cours d'écriture

[env.theorem#adr-thr1]
--
Soient stem:[f\in L^2(\Omega),  stem:[\mathbf{\alpha} \in [L^{\infty}(\Omega)\]^{d\times d}], stem:[\mathbf{\beta} \in [L^{\infty}(\Omega)\]^d], stem:[\nabla \cdot \mathbf{\beta} \in L^{\infty}(\Omega)] et stem:[\mu \in L^\infty(\Omega)].

On note stem:[p = \essinf_{x \in \Omega} (\mu -\frac{1}{2} \nabla \cdot \mathbf{\beta})] et stem:[c_\Omega] est la constante de l’inégalité de Poincaré <<B23>>.

_(i)_ Les problèmes avec conditions de Dirichlet homogènes <<prob12>> et non-homogènes <<prob12_2>> sont bien posés si
[[eq:92]]
\[
  \alpha_0 > - \min( 0, \frac{\gamma}{c_\Omega}  )
\]

_(ii)_ Le problème  avec condition de Neumann <<prob12_1>> est  bien posé si
[[eq:92_1]]
\[
  p > 0\quad\text{et}\quad \essinf_{x \in \Omega}(\beta \cdot n ) \geq 0
\]

_(iii)_ Le problème  avec condition de Dirichlet-Neumann <<prob12_3>> est  bien posé si <<eq:92>> est vérifiée et
[[eq:92_2]]
\[
  \mathrm{meas}(\partial \Omega_D) > 0\quad\text{et}\quad \partial \Omega^- = \{ x\in \partial \Omega ; (\beta \cdot n)(x) < 0\} \subset \partial \Omega_D
\]

_(iv)_ On pose stem:[q = \essinf_{x \in \Omega} (\gamma +\frac{1}{2} \mathbf{\beta}\cdot n)].
Le problème avec conditions de Robin <<prob12_4>>  non-homogènes <<prob12_2>> est posé si
[[eq:92_3]]
\[
  p \geq 0,\quad q \geq 0,\quad\text{et}\quad pq \neq 0.
\]
--

[env.proof]
--
Nous prouvons _(i)_ et _(iv)_.

*Preuve de _(i)_*
En utilisant l'ellipticité de stem:[\mathcal{L}] et l'identité suivante(Formule de Green)
\[
\int_\Omega u(\beta \cdot \nabla u) = -\frac{1}{2} \int_\Omega (\nabla \cdot \beta) u^2 + \frac{1}{2} \int_{\partial \Omega} (\beta \cdot n) u^2
\]
alors on a
\[
\forall u \in H^1_0(\Omega),\quad a(u,u) \geq \alpha_0|u|^2_{1,\Omega} + p \|u\|^2_{0,\Omega}.
\]
En posant stem:[c=\min(0,\frac{p}{c_\Omega}] et en utilisant l'inégalité de Poincaré <<B53>> on a
\[
\forall u \in H^1_0(\Omega),\quad a(u,u) \geq \left(\alpha_0+\frac{c}{c_\Omega}\right)|u|^2_{1,\Omega} \geq \sigma \|u\|^2_{1,\Omega}.
\]
avec stem:[\sigma=\frac{c_\Omega(c_\Omega\alpha_0+c)}{1+c^2_\Omega}].

Cela montre que stem:[a] est _coercive_ sur stem:[H^1_0(\Omega)].

Le caractère bien posé résulte alors du Lemme de Lax-Milgram pour les conditions de Dicirichlet homogènes et de la proposition <<TODO>> pour les conditions de Dirichlet non-homogènes.stem:[\square]

*Preuve de _(iv)_*
Notons stem:[a(u,v)=\int_\Omega \alpha \nabla u\cdot \nabla u + (\beta \cdot \nabla u) v + \mu u v + \int_{\partial \Omega} \gamma u v]. Nous avons l'inégalité suivante:
\[
\forall u \in H^1(\Omega),\quad a(u,u) \geq \alpha_0|u|^2_{1,\Omega} + p \|u\|^2_{0,\Omega} + q\|u\|^2_{0,\partial \Omega}.
\]

Si stem:[p>0] et stem:[q\geq 0], la forme bilinéaire est _coercive_ sur stem:[H^1(\Omega)] avec comme constante stem:[\sigma = \min(\alpha_0,p).

Si stem:[p\geq 0] et stem:[q > 0], la forme bilinéaire est _coercive_ sur stem:[H^1(\Omega)] grâce au Lemme <<TODO>>.

Dans les deux cas, le caractère bien posé est obtenu par le Lemme de Lax-Milgram.stem:[\square]
Ceci termine les preuves de _(i)_ et _(iv)_. stem:[\blacksquare]
--

La coercivité est garantie si stem:[\alpha_0] est suffisamment grand c’est à dire que si la diffusion est dominante.


[[sec:adr-H1-conforming-approx]]
=== Approximation conforme dans stem:[H^1]

NOTE: Cette section est en cours d'écriture

L’approximation élément fini est similaire à celle du Laplacian, de plus les variantes sur les conditions aux limites s’appliquent également: condition de Dirichlet non homogène, de Neumann ou de Robin.


Soit stem:[\Omega] un polyèdre dans stem:[\RR^d], soit stem:[\{\mathcal{T}_h\}] une famille de maillages de stem:[\Omega], et soit stem:[\{\hat{K}, \hat{P}, \hat{E}\}]  un élément fini Lagrange de référence du degré stem:[k \geq 1].

Soit stem:[P^k_{c,h}] l'espace d'approximation conformé stem:[H^1] défini par
[stem]
++++
P^k_{c,h}=\{v \in C^0(\bar{\Omega}); \quad \forall K \in \mathcal{T}_h v_{|K} \in \mathbb{P}^k (K) \}
++++
Pour obtenir une approximation conforme dans stem:[V], nous rajoutons les conditions aux limites, _i.e_, nous avons
[stem]
++++
V_h = P^k_{c,h} \cap V
++++
Dans le cas de conditions de Dirichlet homogène cela donne
[stem]
++++
V_h=\{ v_h \in P^k_{c,h} ;\ v_h = 0 \mbox{ sur } \partial \Omega\}
++++
Dans le cas Neumann et Robin, nous avons stem:[Vh=P^k_{c,h}].
Enfin dans le cas Dirichlet-Neumann, nous avons
[stem]
++++
V_h=\{v_h \in P^k_c; \ v_h = 0 \mbox{ sur } \partial \Omega_D\}
++++

Le problème discret s'ecrit
[env.problem]
--
Trouver stem:[u_h] dans stem:[V_h] telle que
\[
a(u_h,v_h)=\ell(v_h), \quad \forall v_h \in V_h
\]
--

Nous cherchons à présent à estimer l'erreur stem:[u-u_h] en norme stem:[H^1] et stem:[L^2].


.Estimation stem:[H^1]
[env.theorem#thr-adr-conv]
--
Soit stem:[\Omega] un polyèdre dans stem:[\RR^d], soit stem:[\{\mathcal{T}_h\}] une famille de maillages de stem:[\Omega], et soit stem:[\{\hat{K}, \hat{P}, \hat{E}\}]  un élément fini Lagrange de référence du degré stem:[k \geq 1].
Nous avons stem:[\lim_{h\rightarrow 0} \|u-u_h\|_{1,\Omega} = 0] et pour stem:[\frac{d}{2} < s < k+1, il existe une constante stem:[c] telle que
\[
\forall h, \quad \|u-u_h\| \leq c h^{s-1} |u|_{s,\Omega}
\]
--

.Estimation stem:[L^2]
[env.theorem#thr-adr-conv]
--
Soient les hypothèse du théorème précédent, auxquelles nous ajoutons des hypothèses initial a des propriétés régularisantes
Nous avons stem:[\lim_{h\rightarrow 0} \|u-u_h\|_{1,\Omega} = 0] et pour stem:[\frac{d}{2} < s < k+1, il existe une constante stem:[c] telle que
\[
\forall h, \quad \|u-u_h\|_{0,\Omega} \leq c h |u-u_h|_{1,\Omega}
\]
--

NOTE: nous n'avons pas défini ce que sont ces propriétés régularisantes. Nous supposerons qu'elles sont vérifiées.

.Exemple du Laplacien avec conditions de Dirichlet homogène en P1
[NOTE]
====
\forall h, \quad \|u-u\|_{0,\Omega} + h \|u-u_h\|_{1,\Omega} \leq c h^2 \|f\|_{0,\Omega}
====


include::stab.adoc[]

[[sec:elasticite-lineaire]]
== Élasticité Linéaire

On s’intéresse dans cette section à l’approximation par éléments finis de problèmes de mécanique des milieux continus en 3D.

Soit stem:[\mathbf{f}: \Omega \rightarrow \mathbb{R}^3] la charge extérieur s’appliquant au domaine stem:[\Omega].

On note stem:[\disp: \Omega \rightarrow \mathbb{R}^3] le déplacement de la structure induit par cette charge stem:[\mathbf{f}].

En supposant que les déformations soient petites pour être modélisées dans le cadre de l’elasticité linéaire, on a la relation suivante à l’équilibre:

[[eq:31]]
\[
  \nabla \cdot \stresst + \mathbf{f} = \mathbf{0} \mbox{ dans } \Omega
\]
où stem:[\stresst: \Omega \rightarrow \RR^{d\times d}] est le _tenseur des contraintes_ défini par la relation
[[eq:93]]
\[
  \stresst = \lambda \tr(\deformt) \Id + 2 \mu \deformt
\]
et stem:[\deformt : \Omega \rightarrow \RR^{d\times d}] est  le _tenseur des déformations_ défini par
[[eq:94]]
\[
  \deformt = \frac{1}{2} \left( \nabla \disp + \nabla \disp^T \right),
\]
stem:[\lambda] et stem:[\mu] les coefficients de Lamé et stem:[\Id] la matrice identité de stem:[\RR^{d\times d}].

On a alors
[[eq:95]]
\[
  \stresst = \lambda( \nabla \cdot \disp ) \Id + \mu( \nabla \disp + \nabla \disp^T)
\]

[[sec:coefficients-de-lame]]
=== Coefficients de Lamé

Ils sont des coefficients phénoménologiques contraints par les relations suivants:

* stem:[\mu >0]
* stem:[\lambda + \frac{2}{3} \mu \ge 0]

Dans ce qui suit, on supposera que stem:[\lambda \ge 0] et ces coefficients constants.

D’un point de vue pratique, ces coefficients sont obtenus par les _module d’Young_ stem:[E] et _coefficient de Poisson_ stem:[\nu] tels que
[[eq:96]]
\[
  \lambda =  \frac{E \nu}{( 1+\nu )*( 1-2 \nu )} , \quad \mu =\frac{E}{2 ( 1+\nu )}
\]
