:cfpdes: Coefficient Form PDEs 
= The linear elasticity equation with {cfpdes} toolbox
:feelpp: Feel++
:stem: latexmath
:page-jupyter: true
:sectanchors: true
:sectnums: |,all|
:tocdepth: 3

== Introduction

This notebook deals with the finite element approximation of deformable continuum mechanics problems in three space dimensions. 
The domain stem:[\Omega \subset \mathbb{R}^3] represents a deformable medium, initially at rest and to which an external loading stem:[f: \Omega \rightarrow \mathbb{R}^3] is applied. 
The objective is to determine the displacement field stem:[u: \Omega \rightarrow \mathbb{R}^3] induced by this loading once the medium has reached equilibrium. 
It is assumed that the deformations are small enough to be modeled in the framework of linear elasticity. 
For simplicity, it is also assumed that the medium is isotropic.

We note stem:[\sigma: \Omega \rightarrow \mathbb{R}^{3,3}] the stress field. 
The equilibrium condition is written as follows
[stem]
++++
\nabla \cdot \sigma+f=0 \quad \text { in } \Omega
++++

.Strain tensor.
[.def#def:deformation]
****
Let us note stem:[\varepsilon(u): \Omega \rightarrow \mathbb{R}^{3,3}] the linearized deformation field defined by

[[eq-def-epsilon]]
[stem]
++++
\varepsilon(u)=\frac{1}{2}\left(\nabla u+\nabla u^T\right) .
++++
****

NOTE: stem:[\nabla u] is the field with values in stem:[\mathbb{R}^{3,3}] of components stem:[(\nabla u)_{i j}=\partial_j u_i, i, j \in\{1,2,3\}].

.Stress-strain relation.
[.def#def:stress]
****
In the framework of linear elasticity, the stress field is expressed as a function of the linearized strain field as
[stem]
++++
\sigma(u)=\lambda \operatorname{tr}(\varepsilon(u)) \mathcal{I}_3+2 \mu \varepsilon(u)
++++
where stem:[\lambda] and stem:[\mu] are the Lamé coefficients and stem:[\mathcal{I}_3] the identity matrix in stem:[\mathbb{R}^{3,3}]. Using <<eq-def-epsilon, the definition of the deformation tensor>>, we get
[stem]
++++
\sigma(u)=\lambda(\nabla \cdot u) \mathcal{I}_3+\mu\left(\nabla u+\nabla u^T\right)
++++
****

The Lamé coefficients are phenomenological coefficients which, for thermodynamic reasons, are constrained by the relations stem:[\mu>0] and stem:[\lambda+\frac{2}{3} \mu \geq 0]. 

For simplicity, we assume that stem:[\lambda \geq 0] and that the medium is homogeneous so that the coefficients stem:[\lambda] and stem:[\mu] are constants. 
In some applications, it is more convenient to introduce the Young's modulus stem:[E] and the Poisson's ratio stem:[\nu] such that

.Relation between Lamé coefficients and Young's modulus.
[.prop#prop:young]
****
[stem]
++++
\left\{\begin{aligned}
E=\mu \frac{3 \lambda+2 \mu}{\lambda+\mu} \quad \text { and } \quad v = \frac{\lambda} {2  (\lambda + \mu)}\\
\lambda = \frac{E \ \nu} {(1 + \nu) \ (1 - 2\nu)},\quad \mu = \frac{E} {2  (1 + \nu)}

\end{aligned}
\right.
++++
****

The Poisson coefficient is such that stem:[-1 \leq \nu<\frac{1}{2}]; moreover, stem:[\nu \geq 0] if stem:[\lambda \geq 0]. A Poisson's ratio very close to stem:[\frac{1}{2}] (i.e. Lamé coefficients such that the ratio stem:[\frac{1}{2}] is very large) characterizes a practically incompressible material.

The model problem  must be completed by boundary conditions. In the following, two cases are considered.

.Homogeneous Dirichlet problem
[.def#def:dirichlet]  
****
we impose the boundary condition
[stem]
++++
u=0 \quad \text { on } \partial \Omega
++++
****

.Pure traction problem (or Neumann problem)
[.def#def:neumann] 
****
we impose the boundary condition
[stem]
++++
\sigma(u) \cdot n=g \quad \text { on } \partial \Omega
++++
where stem:[g: \partial \Omega \rightarrow \mathbb{R}^3] represents a force field applied on the edge of stem:[\Omega] and stem:[n] the exterior normal to stem:[\Omega].
****

Other boundary conditions are possible such as, for example, mixed Dirichlet-Neumann conditions.

== The mathematical framework

.Weak formulation.
[.def#eq-def-a]
****
On stem:[\left[H^1(\Omega)\right\]^3 \times\left[H^1(\Omega)\right\]^3], we introduce the bilinear form 
[stem]
++++
a(v, w)=\int_{\Omega} \sigma(v): \varepsilon(w)=\int_{\Omega} \lambda(\nabla \cdot v)(\nabla \cdot w)+\int_{\Omega} 2 \mu \varepsilon(v): \varepsilon(w).
++++
****

NOTE: For two matrices stem:[\sigma] and stem:[\varepsilon] in stem:[\mathbb{R}^{3,3}, \sigma: \varepsilon] denotes their maximal contraction, which is equal to stem:[\sum_{i, j=1}^3 \sigma_{i j} \varepsilon_{i j}].

It is clear that stem:[a \in \mathcal{L}\left(\left[H^1(\Omega)\right\]^3 \times\left[H^1(\Omega)\right\]^3 ; \mathbb{R}\right)]. 
Moreover, the bilinear form stem:[a] is symmetric and positive. 
On the other hand, the bilinear form stem:[a] is singular. 
Indeed, by introducing the vector space of rigid displacements

[stem]
++++
\mathcal{R}=\left\{z \in\left[H^1(\Omega)\right]^3 ; \exists(\alpha, \beta) \in \mathbb{R}^3 \times \mathbb{R}^3, \forall x \in \Omega, z(x)=\alpha+\beta \times x\right\}
++++

we have the equivalence

[stem]
++++
(z \in \mathcal{R}) \Longleftrightarrow\left(\forall v \in \left[H^1(\Omega)\right]^3, a(z, v)=0\right) .
++++

We note that a rigid displacement consists in the compound of a translation and a rotation and that
[stem]
++++
\mathcal{R} \cap\left[H_0^1(\Omega)\right]^3=\{0\}
++++

since the only rigid displacement that preserves the boundary is the zero displacement.

=== Homogeneous Dirichlet problem. 

In order to write the homogeneous Dirichlet problem in weak form, we introduce the functional space
[stem]
++++
V_{\mathrm{D}}=\left[H_0^1(\Omega)\right]^3
++++
and the linear form stem:[f_{\mathrm{D}} \in V_{\mathrm{D}}^{\prime}] such that for any stem:[w \in V_{\mathrm{D}}],
[stem]
++++
f_{\mathrm{D}}(w)=\int_{\Omega} f \cdot w
++++


.Problem Formulation
[.prob#eq-problem-D]
****
We obtain the following problem:
[stem]
++++
\text { Find } u \in V_{\mathrm{D}} \text { such that } 
a(u, w)=f_{\mathrm{D}}(w), \quad \forall w \in V_{\mathrm{D}} .
++++
****


The well-posedness of <<eq-problem-D,the previous problem>> follows from the following inequality

.Lemma First Korn inequality. 
[.lem#lem:1st-korn-ineq]
****
Let stem:[\Omega] be a domain of stem:[\mathbb{R}^3]. Let stem:[\|\varepsilon(v)\|_{0, \Omega}=\left(\int_{\Omega} \varepsilon(v): \varepsilon(v)\right)^{\frac{1}{2}}]. There exists a constant stem:[\boldsymbol{\kappa}_{\Omega}] such that
[[1st-korn-ineq]]]
[stem]
++++
\forall v \in\left[H_0^1(\Omega)\right]^3, \quad \kappa_{\Omega}|v\|_{1, \Omega}.
++++
****

The <<1st-korn-ineq,inequality>> implies the coercivity of the bilinear form stem:[a] on stem:[V_{\mathrm{D}}=\left[H_0^1(\Omega)\right\]^3] since
[stem]
++++
\forall v \in\left[H_0^1(\Omega)\right]^3, \quad a(v, v) \geq 2 \mu|\varepsilon(v)\|_{0, \Omega}^2 \geq 2 \mu \kappa_{\Omega}^2|v||_{1, \Omega}^2 .
++++

=== Pure traction problem 

The mathematical study of the pure traction problem requires some precautions. 

Indeed, we cannot look for the solution stem:[u] in stem:[\left[H^1(\Omega)\right\]^3] and ask that for any stem:[w \in\left[H^1(\Omega)\right\]^3], stem:[a(u, w)=\int_{\Omega} f \cdot w+\int_{\partial \Omega} g \cdot w] because the bilinear form stem:[a] is singular on stem:[\left[H^1(\Omega)\right\]^3]. 

.Necessary condition for the existence of a solution.
[.def#def:rigid]
****
A necessary condition for the existence of a solution is that
[stem]
++++
\forall z \in \mathcal{R}, \quad \int_{\Omega} f \cdot z+\int_{\partial \Omega} g \cdot z=0 .
++++
****

This equation expresses the fact that the resultant of all external forces and their moments are zero. 
Moreover, the solution stem:[u], if it exists, is determined only to the nearest rigid displacement. 
We therefore consider the functional space
[stem]
++++
V_{\mathrm{N}}=\left\{v \in\left[H^1(\Omega)\right]^3; \int_{\Omega} v=0; \int_{\Omega} \nabla \times v=0\right\},
++++
and the linear form stem:[f_{\mathrm{N}} \in V_{\mathrm{N}}^{\prime}] such that for any stem:[w \in V_{\mathrm{N}}],
[stem]
++++
f_{\mathrm{N}}(w)=\int_{\Omega} f \cdot w+\int_{\partial \Omega} g \cdot w .
++++
We obtain the following problem:
[[pure-traction-problem-varf]]
[stem]
++++
\left\{\begin{array}{l}
\text { Find } u \in V_{\mathrm{N}} \text { such that } \\
a(u, w)=f_{\mathrm{N}}(w), \quad \forall w \in V_{\mathrm{N}}
\end{array}\right.
++++

The well-posedness of <<pure-traction-problem-varf,this problem>> follows from the following inequality 

.Lemma Second inequality of Korn. 
[.lem#lem:2nd-korn-ineq]
****
Let stem:[\Omega] be a domain of stem:[\mathbb{R}^3]. There exists a constant stem:[\kappa_{\Omega}^{\prime}] such that
[[2nd-korn-ineq]]
[stem]
++++
\forall v \in\left[H^1(\Omega)\right]^3, \quad \boldsymbol{\kappa}_{\Omega}^{\prime}\|v\|_{1, \Omega} \leq \|\varepsilon(v)\|_{0, \Omega}+\|v\|_{0, \Omega}
++++
****
We show that the <<2nd-korn-ineq,inequality>>  implies the coercivity of the bilinear form stem:[a] on stem:[V_{\mathrm{N}}].


[NOTE]
====
In continuum mechanics, the test function stem:[w] involved in the weak formulations is interpreted as an admissible virtual displacement field and the weak formulations express the principle of virtual work. Moreover, the bilinear form stem:[a] being symmetric and coercive on stem:[V_{\mathrm{D}}] and stem:[V_{\mathrm{N}}], the unique solution, respectively, minimizes on stem:[V_{\mathrm{D}}] and stem:[V_{\mathrm{N}}] the energy functional
[stem]
++++
\mathcal{E}_{\mathrm{D}}(v)=\frac{1}{2} \lambda \int_{\Omega}(\nabla \cdot v)^2+\frac{1}{2} \mu \int_{\Omega} \varepsilon(v): \varepsilon(v)-f_{\mathrm{D}}(v)
++++
and
[stem]
++++
\mathcal{E}_{\mathrm{N}}(v)=\frac{1}{2} \lambda \int_{\Omega}(\nabla \cdot v)^2+\frac{1}{2} \mu \int_{\Omega} \varepsilon(v): \varepsilon(v)-f_{\mathbb{N}}(v)
++++
We find the principle of least energy. The quadratic terms in stem:[v]  represent the elastic energy of deformation and the linear terms the potential energy under the external force field.
====

== Conformal approximation

We consider a conformal approximation of problems by Lagrangian finite elements. 
We suppose that stem:[\Omega] is a polyhedron of stem:[\mathbb{R}^3] and we consider a regular and conformal family of affine meshes of stem:[\Omega] that we note stem:[\left\{\mathcal{T}_h\right\}_{h>0}]. 
We choose as reference finite element stem:[\left\{\widehat{K}, \widehat{P}, \widehat{Sigma}\right\}] a Lagrangian finite element of degree stem:[k \geq 1].

=== Homogeneous Dirichlet problem

In order to construct a stem:[V_{\mathrm{D}}]-conformal approximation space, we pose
[stem]
++++
V_{\mathrm{D} h}=\left[P_{\mathrm{c}, h}^k\right]^3 \cap\left[H_0^1(\Omega)\right]^3,
++++
The elements of stem:[V_{\mathrm{D} h}] are the vector fields of which each component is in stem:[P_{\mathrm{c}, h}^k] and which cancel on the boundary of stem:[\Omega].
We consider the following approximate problem:
[stem]
++++
\left\{\begin{array}{l}
\text { Search } u_h \in V_{\mathrm{D} h} \text { such as } \\
a\left(u_h, w_h\right)=f_{\mathrm{D}}\left(w_h\right), \quad \forall w_h \in V_{\mathrm{D} h},
\end{array}\right.
++++
which is clearly well-posed since stem:[a] is coercive on stem:[V_{\mathrm{D}}] and stem:[V_{\mathrm{D}h} \subset V_{\mathrm{D}}].


.Theorem Convergence. 
[.thm#thm:convergence]
****
With the above assumptions, we suppose that the unique solution stem:[u] is in 
stem:[\left[H^{k+1}(\Omega) \cap H_0^1(\Omega)\right\]^3]. Then, there exists a constant stem:[c] such that for all stem:[h],
[stem]
++++
\left\|u-u_h\right\|_{1, \Omega} \leq c b^k|u|_{k+1, \Omega}
++++
Moreover, if the problem  is regularizing (i.e., if there exists a constant stem:[c_s] such that for any stem:[f \in\left[L^2(\Omega)\right\]^3], the unique solution satisfies stem:[\|u|_{2, \Omega} \leq c_s\|f|_{0, \Omega}]), there exists a constant stem:[c] such that for any stem:[h],
[[estimation-conv]]
[stem]
++++
\left\|u-u_h\right\|_{0, \Omega} \leq c h^{k+1}|u|_{k+1, \Omega} .
++++
****
.Elements of proof
[%collapsible.proof#proof-1]
====
The <<estimation-conv,estimation>> results from the lemma of Céa  and the interpolation theorem which we apply component by component. The estimate results from the Aubin-Nitsche lemma.
====

=== Pure traction problem

For the pure traction problem, one way to eliminate the arbitrary rigid displacement at the discrete level is to:
[lowerroman]
. impose that the displacement at one mesh node, stem:[a_0], is zero;
. choose three other mesh nodes, stem:[a_1, a_2, a_3], and three unit vectors, stem:[\tau_1, \tau_2, \tau_3], such that the set stem:[\left\{\left(a_i-a_0\right) \times \tau_i\right\}_{1 \leq i \leq 3}] forms a basis of stem:[\mathbb{R}^3];
. impose that the displacement at the node stem:[a_i] along the direction stem:[\boldsymbol{\tau}_i] is zero.

.Pure Traction approximation space
[.def#def:space-pure-traction]
****
This leads to the approximation space
[stem]
++++
\begin{aligned} 
V_{\mathrm{N} h}=\left\{v_h \in\left[\mathcal{C}^0(\bar{\Omega})\right]^3 ;\right. & \forall K \in \mathcal{T}_h, v_h \circ T_K \in[\widehat{P}]^3 ; \\ & \left.v_h\left(a_0\right)=0 ; v_h\left(a_i\right) \cdot \tau_i=0, i \in\{1,2,3\}\right\} .
\end{aligned}
++++
****

We consider the following approximated problem:
[[approx-problem-N]]
[stem]
++++
\left\{\begin{array}{l}
\text { Find } u_h \in V_{\mathrm{N} h} \text { such as } \\
a\left(u_h, w_h\right)=f_{\mathrm{N}}\left(w_h\right), \quad \forall w_h \in V_{\mathrm{N} h} .
\end{array}\right.
++++
Using the second Korn inequality, we show that the bilinear form stem:[a] is coercive on stem:[V_{\mathrm{N} h}] so that the <<approx-problem-N,discrete problem>>  is well posed.

.Theorem Convergence. 
[.thm#thm:convergence-N]
****
With the above assumptions, we suppose that the unique solution u of <<pure-traction-problem-varf,continuous problem>> is in stem:[\left[H^{k+1}(\Omega)\right\]^3 \cap V_{\mathrm{N}}]. Then there exists a constant stem:[c] such that for all stem:[h],
[stem]
++++
\left\|u-u_h\right\|_{1, \Omega} \leq c h^k|u|_{k+1, \Omega} .
++++
Moreover, if stem:[g=0] and if the <<pure-traction-problem-varf,problem>>  is regularizing, (i.e. if there exists a constant stem:[c_s] such that for any stem:[f \in\left[L^2(\Omega)\right\]^3], the unique solution of <<pure-traction-problem-varf,problem>> with stem:[g=0] satisfies stem:[\left.\|u\|_{2, \Omega} \leq c_s\|f\|_{0, \Omega}\right)]), there exists a constant stem:[c] such that for any stem:[h],
[stem]
++++
\left\|u-u_h\right\|_{0, \Omega} \leq c h^{k+1}|u|_{k+1, \Omega}
++++
****
[NOTE]
====
A sufficient condition for the problems  to be regularizing is that the polyhedron stem:[\Omega] is convex and that stem:[g=0]; see, for example, the book by <<grisvard,Grisvard>>.
====

=== Example

[source,python]
----
# To be done
----

== Virtually incompressible materials: loss of coercivity

We are now interested in materials whose ratio of Lamé coefficients is such that
[[coercivity-loss]]]
[stem]
++++
\frac{\lambda}{\mu} \gg 1
++++

This situation occurs when the *Poisson's ratio* is very close to stem:[\frac{1}{2}], i.e. for practically incompressible materials.

For such materials, it is observed that if we use a mesh that is not fine enough, the discrete solution is polluted by spurious oscillations. This phenomenon, called **coercivity loss**. 
The ratio stem:[\frac{\lambda}{\mu}] being very large, it is not reasonable to absorb it in the generic constants stem:[c] appearing in the error estimates.
We consider the bilinear form stem:[a] defined <<eq-def-a,above>>. 

.Definition Coercivity and Continuity constants. 
[.def#def:alpha-omega]
****
We pose
[stem]
++++
\begin{aligned}
& \alpha_a=\inf _{v \in V} \frac{a(v, v)}{\|v\|_{1, \Omega}^2} \\
& \omega_a=\sup _{v \in V} \sup _{w \in V} \frac{a(v, w)}{\|v\|_{1, \Omega}\|w\|_{1, \Omega}}
\end{aligned}
++++
where stem:[V] is the functional space on which the continuous problem is posed. 
****

NOTE: Under the <<coercivity-loss,hypothesis>>, we show that the ratio stem:[\frac{\omega_a}{\alpha_a}] is of order stem:[\frac{\lambda}{\mu}]. 

Using the convergence analysis presented in the previous section, we obtain the error estimate
[stem]
++++
\left\|u-u_h\right\|_{1, \Omega} \leq c \frac{\lambda}{\mu} h^k|u|_{k+1, \Omega}
++++
with a constant stem:[c] independent of stem:[h] and the ratio stem:[\frac{\lambda}{\mu}]. This estimate shows that the mesh must be fine enough for the error to be controlled. 

=== Example of coercivity loss


[source,python]
----
# TODO
----

[bibliography]
== Bibliography

* [[[grisvard]]] GRISVARD (P.), Singularities in Boundary Value Problems. Masson, Paris, France, 1992.