// -*- mode: adoc -*-
= Functional analysis tools
:lang: fr
:stem: latexmath


[[A few reminders]]
== A few reminders

[[norms-and-scalar-products]]
=== Norms and scalar products

Let stem:[E] be a vector space. +

//[[def:7]]
.Definition: Norm
[.def#def:norm]
****
stem:[\|.\|] : stem:[E \rightarrow \RR] is a *norm* on stem:[E] if it verifies :

(N1):: stem:[ \left( \| x \| = 0 \right) \Longrightarrow (x=0) ]

(N2):: stem:[\forall\, \lambda\in\RR,\; \forall x\in E, \quad \| \lambda x \| = |\lambda| \; \| x \| ]

(N3):: stem:[\forall\, x,y \in E, \quad \| x+ y \| \le \|x \| + \|y\|] (triangular inequality)
****

For stem:[E=\RR^n] and stem:[x=(x_1,\ldots,x_n) \in\RR^n], we define the norms

[stem]
++++
\| x \|_1 = \sum_{i=1}^n |x_i| \qquad \| x \|_2 = \left( \sum_{i=1}^n x_i^2 \right)^{1/2} \qquad \| x \|_\infty = \sup_{i} |x_i|
++++



.Definition: Scalar product
[.def#def:scalar-product]
****
Any positive definite symmetric bilinear form is called _scalar product_ on stem:[E].

stem:[\quad<.,.>] : stem:[E\times E \rightarrow \RR] is therefore a scalar product on stem:[E] if it verifies :

S1::
[stem]
++++
\forall\; x,y \in E, \quad <x,y> = <y,x>
++++

S2::
[stem]
++++
\forall\; x_1,x_2,y \in E, \quad <x_1+x_2,y> = <x_1,y>+ <x_2,y>
++++

S3::
[stem]
++++
\forall\; x,y \in E, \, \forall\, \lambda\in\RR,\quad <\lambda x,y> = \lambda <x,y>
++++

S4::
[stem]
++++
\forall\; x \in E, x\ne 0, \quad <x,x>\; \gt 0
++++
****


From a scalar product, an *induced norm* can be defined:
[stem]
++++
\| x \| = \sqrt{<x,x>}
++++
Then, according to (N3), we have the Cauchy-Schwarz *inequality*:
[stem]
++++
{ | <x,y> | \le \| x \| \; \| y \| }
++++


[NOTE]
====
For stem:[E=\RR^n], we define the scalar product
[stem]
++++
<x,y> = \sum_{i=1}^n x_i \, y_i.
++++
Its induced norm is stem:[\| . \|_2] defined above.
====



.Definition: Normed space
[.def#def:normed-space]
****
A vector space with a norm is called *normed space*.
****

.Definition: Prehilbert space
[.def#def:prehilbert-space]
****
A vector space with a scalar product is called a *Prehilbertian
prehilbert space*. In particular, it is a normed space for the norm
norm.
****


=== Cauchy sequences and complete spaces


.Definition: Cauchy sequences
[.def#def:cauchy-sequence]
****
Let stem:[E] be a vector space and
stem:[(x_n)_n] a sequence of stem:[E].
stem:[(x_n)_n] is a *Cauchy sequence* if and only if

[stem]
++++
\forall \varepsilon > 0,\;\; \exists N / \forall p>N, \forall q>N, \quad \|x_p - x_q \| < \varepsilon
++++
****


.Cauchy's theorem
[.thm#th-conv-cauchy]
====
Every convergent sequence is Cauchy.
====

NOTE: The reciprocal of <<th-conv-cauchy>> is false.

.Definition: Complete space
[.def#def:complete-space]
****
A vector space is *complete* if every Cauchy sequence y
is convergent.
****


.Definition: Banach space
[.def#def:banach-space]
****
A complete normed space is a *Banach space*.
****

.Definition: Hilbert space
[.def#def:hilbert-space]
****
A complete pre-Hilbert space is a *Hilbert space*.
****


.Definition: Euclidean space
[.def#def:euclidean-space]
****
A finite-dimensional Hilbert space is called a *Euclidean
Euclidean* space.
****

[[Functional spaces]]
== Functional spaces



.Definition: Functional space
[.def#def:functional-space]
****
A *functional space* is a vector space whose elements are
elements are functions.
****

[example]
.stem:[{\cal C}^p([a;b])]
====
stem:[{\cal C}^p([a;b])] denotes the space of functions defined on the interval stem:[[a,b]], all derivatives of which up to the order stem:[p] exist and are continuous on stem:[[a,b]].
====

In the following, functions will be defined on a subset of stem:[\RR^n] (most often an open denoted stem:[\Omega]), with values in stem:[\RR] or stem:[\RR^p].

[example]
.Temperature
====
The temperature stem:[T(x,y,z,t)] at any point of an object stem:[\bar{\Omega}\subset \RR^3] is a function of stem:[ \bar{\Omega} \times \RR \longrightarrow \RR].
====

The simplest usual norms for functional spaces are
the *norms* stem:[\bf L^p] defined by :

[stem]
++++
\| u \|_{L^p} = \left ( \int_{\Omega } |u|^p \right) ^{1/p} \quad ,\; p\in [1,+ \infty[ ,
\qquad \hbox{and}\qquad \| u \|_{L^\infty} = {\hbox{Sup}}_{\Omega } |u|
++++

As we shall see, these stem:[L^p] forms are not necessarily standards. And
when they are, the functional spaces with these norms are not necessarily
are not necessarily Banach spaces. For example, the forms
stem:[L^\infty] and stem:[L^1] are norms on the space
the space stem:[{\cal C}^0([a;b])], and this space is complete if we
with the norm stem:[L^\infty], but not with the norm stem:[L^\infty].
the stem:[L^1] norm.

For this reason, we define the spaces stem:[{\cal L}^p(\Omega)(p\in [1,+ \infty[]) by

[stem]
++++
{\cal L}^p(\Omega) = \left\{ u : \Omega \rightarrow \RR, \hbox{ measurable, and such that }\int_\Omega |u|^p<\infty \right\}
++++

NOTE: A function stem:[u] is measurable if stem:[\{ x / |u(x)|<r \}] is measurable stem:[\forall r>0].

On these spaces stem:[{\cal L}^p(\Omega)], the
forms stem:[L^p] are not norms. Indeed, stem:[\| u
\|_{L^p} = 0] implies that stem:[u] is *zero almost everywhere* in
stem:[{\cal L}^p(\Omega)], not stem:[u=0]. This is why we'll
define the *spaces* stem:[\bf L^p(\Omega)] :

.Definition: Equality almost everywhere
[.def#def:almost-everywhere]
****
stem:[L^p(\Omega)] is the equivalence class of functions of
stem:[{\cal L}^p(\Omega)] for the equivalence relation *equality almost everywhere
everywhere*. In other words, we'll confuse two functions whenever they are
are equal almost everywhere, i.e. they differ only on a set of zero measure.
a set of zero measure.
****

.Theorem: stem:[L^p(\Omega)]
[.thm#th-lp-complete]
****
The form stem:[L^p] is a norm on stem:[L^p(\Omega)],
and stem:[L^p(\Omega)] equipped with the norm stem:[L^p] is a
Banach space (i.e. is complete).
****

NOTE: A very important special case is stem:[p=2]. In this case
the *functional space stem:[L^2(\Omega)]*, i.e. the space of
the space of summable square functions on stem:[\Omega] (at the
equivalence relation *equality almost everywhere*). To the norm
stem:[L^2] :
stem:[\| u \|_{L^2} = \left( \int_\Omega u^2 \right)^{1/2} ], we can associate the bilinear form
the bilinear form
stem:[(u,v)_{L^2} = \int_\Omega u\, v]. This is a scalar product
from which the norm stem:[L^2] is derived.

Hence the following theorem


.Theorem: stem:[L^2(\Omega)] 
[.thm#th-l2-hilbert]
****
stem:[L^2(\Omega)] is a Hilbert space.
****

[[sec:notion-de-derivee]]
== Notion of generalized derivative


We've just defined complete functional spaces, which provide a good framework for demonstrating the existence and uniqueness of solutions to partial differential equations, as we'll see later with the Lax-Milgram theorem.

However, we have seen that the elements of these stem:[L^p] spaces are not necessarily very regular functions.

Consequently, the partial derivatives of such functions are not necessarily defined everywhere.

To overcome this problem, we're going to extend the notion of derivation.

The real tool to be introduced for this is the notion of *distribution*, due to L. Schwartz (1950).

For lack of time in this course, we'll confine ourselves here to giving a very simplified idea, with the notion of *generalized derivative*.

The latter has much more limited properties than distributions, but allows us to get a "feel" for the aspects necessary to
the variational formulation.

In the following, stem:[\Omega] will be an open (not necessarily bounded) of stem:[\RR^n].

[[sec:test-functions]]
=== Test functions


Let stem:[\varphi : \Omega \rightarrow \RR].

.Definition: support of stem:[\varphi]
[.def#def:support]
****
We call *support of stem:[\bf \varphi]* the adherence of stem:[\{ x \in \Omega / \varphi(x) \ne 0 \}].
****

[example]
====
For stem:[\Omega = \]-1,1\]], and stem:[\varphi] the constant function equal to 1, stem:[\hbox{Supp}\, \varphi = \[-1,1\]].
====

.Definition: Space for test functions
[.def#def:test-functions]
****
Let stem:[{\cal D}(\Omega)] be the space of functions from stem:[\Omega] to stem:[\RR], of class stem:[{\cal C}^\infty], and with compact support included in stem:[\Omega].

stem:[{\cal D}(\Omega)] is sometimes called *test function space*.
****

[example]
====
The most classic example in the 1-D case is the function

stem:[
\varphi(x) =
  \left\{
    \begin{array}{ll}
    { e^{- \frac{1}{1-x^2}} } & \hbox{si } |x|<1
      0 & \hbox{si } |x|1\\ge
    \end{array}
  \right.
]
stem:[\varphi] is a function of stem:[{\cal D}(]a,bstem:[)] for all stem:[a < -1 < 1 < b].


NOTE: This example can easily be extended to the multi-dimensional case (stem:[n>1]).
====

Let stem:[a\in\Omega] and stem:[r>0] be such that the closed ball of center stem:[a] and radius stem:[r] is included in stem:[\Omega].

We then pose :
[[eq:function-test2]]
[stem]
++++
 \varphi(x) = \left\{
 \begin{array}{ll}
 { e^{- \frac{1}{r^2-|x-a|^2}} } & \hbox{si } |x-a| < r\\
 0 & \hbox{ otherwise }
 \end{array}
 \right.
++++

stem:[\varphi] thus defined is an element of stem:[{\cal D}(\Omega)].


.Theorem: Adherence of stem:[\overline{{\cal D}(\Omega)}]]
[.thm#thm:adherence]
****
stem:[\overline{{\cal D}(\Omega) } = L^2(\Omega)]
****

[[sec:derivee-generalisee]]
=== Generalized derivative


Let stem:[u\in {\cal C}^1(\Omega)] and stem:[\varphi \in {\cal D}(\Omega)].

By integration by parts (appendix [sec:green]), we have :

[stem]
++++
\int_\Omega \partial_i u\; \varphi = - \int_\Omega u \; \partial_i\varphi + \int_{\partial \Omega} u \; \varphi \; {\bf e}_i.{\bf n}
++++

This last term (integral on the edge of stem:[\Omega]) is null because stem:[\varphi] is compactly supported (hence null on
stem:[\partial \Omega]).

But stem:[\int_\Omega u \; \partial_i\varphi] makes sense as soon as stem:[u\in L^2(\Omega)].

So stem:[\int_\Omega \partial_i u\; \varphi] also makes sense, without stem:[u] necessarily being of class stem:[{\cal C}^1].

This makes it possible to define stem:[\partial_i u] even in this case.

.Definition: Generalized derivative
[.def#def:generalized-derivative]
****
1-D case stem:[\quad] Let stem:[I] be an interval of stem:[\RR], not necessarily bounded.
not necessarily bounded.

We say that stem:[u\in L^2(I)] admits a *generalized derivative* in stem:[L^2(I)] if stem:[\exists u_1\in L^2(I)] such that

stem:[
\forall \varphi\in {\cal D}(I), \quad \int_I u_1\;\varphi = - \int_I u \varphi'
]
****

[example]
====
Let stem:[I=\]a,b[] be a bounded interval, and stem:[c] be a point of stem:[I].
point of stem:[I]. Consider a function stem:[u]
formed by two branches of class stem:[{\cal C}^1], one on
one on stem:[]a,c[], the other on stem:[]c,b[], and connecting continuously
to stem:[c]. Then
stem:[u] has a generalized derivative defined by
stem:[u_1(x)=u'(x)\quad \forall x\ne c]. Indeed :


stem:[
\forall \varphi\in {\cal D}(\]a,b[)\qquad \int_a^b u \varphi' = \int_a^c + \int_c^b = - \int_a^c u' \varphi - \int_c^b u'\varphi + \underbrace{(u(c^-)-u(c^+))}_{=0} \, \varphi(c)
]

by integration by parts. The stem value:[u_1(c)] doesn't matter: we end up with the same
the same function as stem:[L^2(I)],
since it is defined as the equivalence class of the equivalence relation
equivalence relation *equality almost everywhere*.
====


.Definition: Generalized derivative of order stem:[k]
[.def#def:generalized-derivative-order-k]
****
By iterating, we say that stem:[u] admits a *generalized derivative
of order stem:[\bf k]* in stem:[L^2(I)], denoted by
stem:[u_k], ssi stem:[{\forall \varphi\in
  {\cal D}(I), \quad \int_I u_k\;\varphi = (- 1)^k \; \int_I u \varphi^{(k)}
  }]
****

These definitions extend naturally to the definition of generalized partial derivatives, in the stem case:[n>1].


.Theorem: Uniqueness of the generalized derivative
[.thm#thm:uniqueness]
****
When it exists, the generalized derivative is unique.
****


.Theorem: generalized derivative and classical derivative
[.thm#thm:generalized-classical]
--
When stem:[u] is of class stem:[{\cal C}^1(\bar{\Omega})], the generalized derivative is equal to the classical derivative.
--

[[Sobolev spaces]]
== Sobolev spaces


=== stem:[H^m] spaces


.Definition: stem:[H^1(\Omega)]
[.def#def:h1]
****
[stem]
++++
{ H^1(\Omega) = \left\{ u \in L^2(\Omega)\; / \; \partial_i u \; \in
    L^2(\Omega), \; 1 \leq i \leq n \right\} }
++++
where stem:[\partial_i u] is defined in the sense of the generalized derivative.


stem:[H^1(\Omega)] is called *Sobolev space of order 1*.
****

.Definition: stem:[H^m(\Omega)]
[.def#def:hm]
****
For any integer stem:[m\ge 1],
stem:[
H^m(\Omega) = \left\{ u \in L^2(\Omega) \; / \; \partial^\alpha u \; \in
  L^2(\Omega) \quad \forall \alpha =(\alpha_1,\ldots,\alpha_n) \in \N^n\hbox{
  such that}\; |\alpha|= \alpha_1+\cdots+\alpha_n \le m \right\}]


stem:[H^m(\Omega)] is called *Sobolev space of order stem:[\bf m].
****

NOTE: By extension, we also see that stem:[H^0(\Omega)=L^2(\Omega)].

[NOTE]
====
In the case of dimension 1, it's simpler to write stem:[I] open from stem:[\RR] :

stem:[ H^m(I) = \left\{ u \in L^2(I) \; / \; u', \ldots, u^{(m)} \in L^2(I) \right\} ]
====

.Theorem: stem:[H^1(\Omega)] is a Hilbert space
[.thm#thm:h1-hilbert]
****
stem:[H^1(\Omega)] is a Hilbert space for the scalar product
stem:[(u,v)_1 = \int_\Omega u \, v\, + \sum_{i=1}^n \; \int_\Omega \partial_i u
\; \partial_i v = (u,v)_0 + \sum_{i=1}^n (\partial_i u, \partial_i v )_0]

noting stem:[(.,.)_0] the scalar product stem:[L^2].
Let stem:[\|.\|_1] be the norm associated with
stem:[(.,.)_1].
****

Similarly, we define a scalar product and a norm on
stem:[H^m(\Omega)] by
[stem]
++++
(u,v)_m = \sum_{|alpha| \le m} ( \partial^\alpha u , \partial^\alpha v )_0 \qquad
\hbox{ and }\qquad \| u \|_m = (u,u)_m^{1/2}]
++++

.Theorem: stem:[H^m(\Omega)] are Hilbert spaces]
[.thm#thm:hm-hilbert]
****
stem:[H^m(\Omega)] with scalar product stem:[(.,.)_m] is a Hilbert space.
is a Hilbert space [thr:8].
****


.Theorem: stem:[H^m(\Omega)] and stem:[{\cal C}^k(\bar{\Omega})]
[.thm#thm:hm-ck]
****
If stem:[\Omega] is an open of stem:[\RR^n] with boundary stem:[\partial\Omega].
"sufficiently regular"  stem:[\partial\Omega] (for example
example stem:[{\cal C}^1]), we have the inclusion :
stem:[H^m(\Omega) \subset {\cal C}^k(\bar{\Omega})] for
stem:[{ k < m-\frac{n}{2}
  }]
****

[example]
====
In particular, we see that for an interval stem:[I] of stem:[\RR],
we have stem:[H^1(I) \subset {\cal C}^0(\bar{I})], i.e. in
1-D, any stem:[H^1] function is continuous.

The example of stem:[u(x) = x\, \sin\frac{1}{x}] for
stem:[x\in\]0,1\]] and stem:[u(0)=0] shows that the converse is false.
is false.

The example of stem:[u(x,y) = | \ln (x^2+y^2) |^k] for
stem:[0<k<1/2] shows that in dimensions greater than 1 there are
discontinuous stem:[H^1] functions.
====

[[trace-a-function]]
=== Trace of a function


To be able to perform integrations by parts, which will be useful for
for variational formulation, you need to be able to define the extension
extension (_trace_) of a function on the edge of the open
stem:[\Omega].

*stem:[n=1] (case 1-D)*:: we consider an open interval
stem:[I=\]a,b[] bounded.
We have seen that stem:[H^1(I) \subset {\cal C}^0(\bar{I})]. Therefore, for
stem:[u\in H^1(I)], stem:[u] is continuous on
stem:[\[a,b\]], and stem:[u(a)] and stem:[u(b)] are
well-defined.


stem:[n>1]:: we no longer have stem:[H^1(\Omega) \subset {\cal C}^0(\bar{\Omega})]. How can
define the trace? Here's how:
 * We define the  space stem:[{\cal C}^1(\bar{\Omega}) = \left\{ \varphi : \Omega \rightarrow \RR \;/\; \exists O \hbox{ open containing } \bar{\Omega},\; \exists \psi \in {\cal C}^1(O),\; \psi_{|\Omega} = \varphi \right\}]
In other words, stem:[{\cal C}^1(\bar{\Omega})] is the space of functions stem:[{\cal C}^1] on stem:[\Omega],
extendable by continuity on stem:[\partial\Omega] and whose gradient
gradient can also be extended by continuity. There is therefore no
to define the trace of such functions.
 * We show that, if stem:[\partial\Omega] is a bounded open
boundary stem:[\partial\Omega] "regular enough", then
stem:[{\cal C}^1(\bar{\Omega})] is dense in
stem:[H^1(\Omega)].
 * The continuous linear application, which to any function stem:[u]
of stem:[{\cal C}^1(\bar{\Omega})] associates its trace on
stem:[\partial\Omega], then extends into a continuous
continuous linear application of stem:[H^1(\\Omega)] in
stem:[L^2(\partial\Omega)], denoted stem:[\gamma_0], which we call *trace application*.
trace application*. We say that stem:[\gamma_0(u)] *is
the trace of stem:[u] on* stem:[\partial\Omega].

NOTE: For a function stem:[u] of stem:[H^1(\Omega)] which is at the same time continuous on stem:[\bar{\Omega}], we obviously have stem:[\gamma_0(u) = u_{||partial\Omega}].
This is why stem:[u_{|\partial\Omega}] is often simply noted rather than stem:[\gamma_0(u)].



Analogously, we can define stem:[\gamma_1], an application
which extends the usual definition of the normal derivative
on stem:[\partial\O]. For
stem:[u\in H^2(\Omega)], we have
stem:[\partial_i u \in H^1(\Omega)],
stem:[\forall i=1,\ldots,n], and we can therefore define
stem:[\gamma_0(\partial_i u)]. The boundary
stem:[\partial\Omega] being "fairly regular" (for example,
ideally, of class stem:[{\cal C}^1]), we can define the
normal
stem:[n=\left( \begin{array}{l} n_1 \\ \vdots  n_n \end{array} \right)]
at any point of stem:[\partial\Omega]. We then pose
stem:[{\gamma_1(u) = \sum_{i=1}^n \gamma_0(\partial_i u) n_i}].
This continuous application stem:[\gamma_1] of
stem:[H^2(\Omega)] into stem:[L^2(\partial\Omega)] thus extends
the usual definition of the normal derivative. In
the case where stem:[u] is a function of stem:[H^2(\Omega)]
which is at the same time in stem:[{\cal C}^1(\bar{\Omega})]], the normal
normal derivative in the usual sense of stem:[u] exists, and
stem:[\gamma_1(u)] is obviously equal to it. This is why
stem:[\partial_n u] rather than stem:[\gamma_1(u)].
stem:[\gamma_1(u)].

[[sec:H10]]
=== Space stem:[H^1_0(\Omega)]


.Definition: stem:[H^1_0(\Omega)]
[.def#def:h10]
****
Let stem:[\Omega] be open from stem:[\RR^n].
The space stem:[H^1_0(\Omega)] is defined as the adherence of stem:[{\cal D}(\Omega)] to the norm stem:[\|.\|_1] of stem:[H^1(\Omega)].
(Recall that stem:[{\cal D}(\Omega)] is the space of stem:[{\cal C}^\infty] functions on stem:[\Omega] with compact support, also known as the space of test functions).
****


.Theorem: stem:[H^1_0(\Omega)] is a Hilbert space
[.thm#thm:h10-hilbert]
****
By construction stem:[H^1_0(\Omega)] is a complete space.
It is a Hilbert space for the norm stem:[\|.\|_1]
****

If stem:[n=1] (case 1-D)}:: consider a bounded open interval stem:[I=\]a,b[]. Then
[stem]
++++
H^1_0(]a,b[) = \left\{ u \in H^1(]a,b[),\; u(a)=u(b)=0 \right\}
++++

If stem:[n>1]:: If stem:[\Omega] is a bounded open with a "fairly
regular" boundary (for example stem:[{\cal C}^1] by pieces), then
stem:[H^1_0(\Omega) = \ker \gamma_0]. stem:[H^1_0(\Omega)]
is therefore the subspace of functions of stem:[H^1(\Omega)] with
zero trace on the stem:[\partial\Omega] boundary.


.Definition
[.def#def:trace]
****
For any stem:[u] function of stem:[H^1(\Omega)], we 
can define :
[stem]
++++
{ |u|_1 = \left( \sum_{i=1}^n \| \partial_i u \|_0^2 \right)^{1/2} = \left( \int_\Omega \sum_{i=1}^n \left( \partial_i u \right)^2 dx \right)^{1/2} }
++++
****


.Theorem: Poincaré's inequality
[.thm#thm:poincare]
****
If stem:[\Omega] is bounded in at least one direction, then there exists a constant stem:[C(\Omega)] such that
[stem]
++++
\forall u \in H^1_0(\Omega), \; \|u\|_0 \le C(\Omega)\; |u|_1.
++++
****

We deduce that stem:[|.|_1] is a norm on stem:[H^1_0(\Omega)], equivalent to the norm stem:[\|.\|_1].

The previous result extends to the case where we have a null Dirichlet condition only on a part of stem:[\partial\Omega], if stem:[\Omega] is connected.

We assume that stem:[\Omega] is a connected bounded open, of boundary stem:[{\cal C}^1] by pieces.

Let stem:[V=\left\{ v\in H^1(\Omega),\, v=0 \hbox{ on }\Gamma_0 \right\}] be where stem:[\Gamma_0] is a part of stem:[\partial\Omega] of non-zero measure.

Then there exists a constant stem:[C(\Omega)] such that stem:[\forall u \in V, \; \|u\|_{0,V} \le C(\Omega)\; |u|_{1,V}], where stem:[\|.\|_{0,V}] and stem:[|.|_{1,V}] denote the norm and semi-norm induced on stem:[V].

We deduce that stem:[|.|_{1,V}] is a norm on stem:[V], equivalent to the norm stem:[\|.\|_{1,V}].



.Theorem: Trace theorem
[.thm#thm:trace]
****
Let D be an open with type edge.
There exists a constant stem:[c] such that stem:[\forall g \in H^{\frac{1}{2}}(\partial \Omega)] there exists stem:[u_g \in H^1(\Omega)] satisfying
[stem]
++++
\gamma_0(u_g) = g \mbox{ and } \|u\|_{H^1} \leq c \|g\|_{H^\frac{1}{2}}
++++
stem:[u_g] is called an *overlap* of stem:[g] in stem:[H^1(\Omega)].
****

[[exercises]]
== Exercises


1.  Show that the functions defined by ([eq:test-function1]) and
([eq:function-test2]) are stem:[{\cal C}^\infty] with support
support.
2.  Show that stem:[{\cal C}^0([a,b\])] is a complete space
for the norm stem:[L^\infty].
3.  Show that this is not the case for stem:[L^1].
(show a non-convergent Cauchy sequence in
stem:[{\cal C}^0([a,b\])]).
4.  Show that, when it exists, the generalized derivative is
unique.
5.  Show that, for a function of class stem:[{\cal C}^1],
the generalized derivative is equal to the classical derivative.
6.  Let be a function from stem:[[a,b\]] to stem:[\RR],
formed by two branches of class stem:[{\cal C}^1] on
stem:[[a,c[] and stem:[\]c,b\]], and discontinuous in
stem:[c]. Show that it has no generalized derivative. (you
the notion of distribution to derive this function).
this function).
7.  Show that stem:[|.|_1] is a norm on
stem:[H^1_0(\Omega)], equivalent to the norm
stem:[\|.\|_1]
