= Theorems and Lemma

NOTE: The following theorems and lemma are taken from Theory and Practice of Finite Elements by A. Ern and J.L. Guermond.

[[thmB46]]
.Theorem B.46 (Rellich-Kondrachov)
****
Let stem:[1 \leq p \leq+\infty] and let stem:[s \geq 0]. Let stem:[\Omega] be a bounded open set having the stem:[(s, p)] - extension property. The following injections are compact:

(i) If stem:[p \leq d, W^{s, p}(\Omega) \subset L^{q}(\Omega)] for all stem:[1 \leq q<p^{*}] where stem:[\frac{1}{p^{*}}=\frac{1}{p}-\frac{s}{d}]

(ii) If stem:[p>d, W^{s, p}(\Omega) \subset \mathcal{C}^{0}(\bar{\Omega})]

**Proof.** See [MaZ97], [BrS94, Chap. 1], or [Bre91, Chap. 8]. stem:[\square]
****
IMPORTANT: <<thmB46>> states a very useful compacity result.

[[LemmaB63]]
.Lemma B63
****
Let stem:[1 \leq p<+\infty] and stem:[\Omega] be a bounded connected open set having the stem:[(1, p)] - extension property. Let stem:[f] be a linear form on stem:[W^{1, p}(\Omega)] whose restriction on constant functions is not zero. Then, there is stem:[c_{p, \Omega}>0] such that
[stem]
++++
\forall v \in W^{1, p}(\Omega), \quad c_{p, \Omega}\|v\|_{W^{1, p}(\Omega)} \leq\|\nabla v\|_{L^{p}(\Omega)}+|f(v)|
++++
**Proof**. Use the Petree-Tartar Lemma. To this end, set stem:[X=W^{1, p}(\Omega), Y=] stem:[\left[L^{p}(\Omega)\right\]^{d} \times \mathbb{R}, Z=L^{p}(\Omega),] and stem:[A: X \ni v \mapsto(\nabla v, f(v)) \in Y .] Owing to
Lemma B. 29 and the hypotheses on stem:[f, A] is continuous and injective. Moreover, the injection stem:[X \subset Z] is compact owing to <<thmB46>> stem:[\square]
****