= Theorems and Lemma

NOTE: The following theorems and lemma are taken from Theory and Practice of Finite Elements by A. Ern and J.L. Guermond.

== Embedding and Compacity

[[thmB39]]
.Proposition B.39 
****
Let stem:[\Omega] be an open bounded set. Then, for stem:[1 \leq p<q \leq +\infty], the embedding stem:[L^q(\Omega) \subset L^p(\Omega)] is continuous.
****
**Proof.** This is a consequence of Hölder's inequality.

One of the key arguments in the embedding theory is the following:

[[thmB40]]
.Theorem B.40 (Sobolev). 
****
Let stem:[1 \leq p<d] and denote by stem:[p^*] the number such that stem:[\frac{1}{p^*}=\frac{1}{p}-\frac{1}{d}]. Then,
[stem]
++++
\begin{equation*}
\exists c=\frac{p^*}{1^*}, \forall u \in W^{1, p}\left(\mathbb{R}^d\right), \quad\|u\|_{L^{p^*}\left(\mathbb{R}^d\right)} \leq c\|\nabla u\|_{L^p\left(\mathbb{R}^d\right)} .
\end{equation*}
++++
****
**Proof.** See [MaZ97, p. 32], [Sob63, §I.7.4], or [Bre91, p. 162].

[[thmB41]]
.Corollary B.41. 
****
Let stem:[1 \leq p, q \leq+\infty]. The following embeddings are continuous:
[stem]
++++
\begin{equation*}
W^{1, p}\left(\mathbb{R}^d\right) \subset L^q\left(\mathbb{R}^d\right) \text { if }\left\{\begin{array}{l}
\text { either } 1 \leq p<d \text { and } p \leq q \leq p^*, \\
\text { or } p=d \text { and } p \leq q<+\infty .
\end{array}\right.
\end{equation*}
++++
****
**Proof.** See [MaZ97, p. 34], [Sob63, §I.8.2], or [Bre91, p. 165].

[[thmB46]]
.Theorem B.46 (Rellich-Kondrachov)
****
Let stem:[1 \leq p \leq+\infty] and let stem:[s \geq 0]. Let stem:[\Omega] be a bounded open set having the stem:[(s, p)] - extension property. The following injections are compact:

(i) If stem:[p \leq d, W^{s, p}(\Omega) \subset L^{q}(\Omega)] for all stem:[1 \leq q<p^{*}] where stem:[\frac{1}{p^{*}}=\frac{1}{p}-\frac{s}{d}]

(ii) If stem:[p>d, W^{s, p}(\Omega) \subset \mathcal{C}^{0}(\bar{\Omega})]
****
**Proof.** See [MaZ97], [BrS94, Chap. 1], or [Bre91, Chap. 8]. stem:[\square]

IMPORTANT: <<thmB46>> states a very useful compacity result.


== Poincaré-like inequalities

[[B61]]
.Lemma B.61 (Poincaré). 
****
Let stem:[1 \leq p<+\infty] and let stem:[\Omega] be a bounded open set. Then, there exists stem:[c_{p, \Omega}>0] such that
[stem]
++++
\forall v \in W_{0}^{1, p}(\Omega), \quad c_{p, \Omega}\|v\|_{L^{p}(\Omega)} \leq\|\nabla v\|_{L^{p}(\Omega)}
]
++++
For stem:[p=2,] we denote stem:[c_{\Omega}=c_{2, \Omega}]
****
**Proof.** We only give the proof for stem:[p<d]. 
Let stem:[\tilde{v} \in W^{1, p}\left(\mathbb{R}^{d}\right)] be the zeroextension of stem:[v ;] see Proposition B.48. 
Theorem B.40 implies stem:[\|\tilde{v}\|_{L^{p^{*}}\left(\mathbb{R}^{d}\right)} \leq]
stem:[c\|\nabla \tilde{v}\|_{L^{p}\left(\mathbb{R}^{d}\right)} .] since stem:[\Omega] is bounded and stem:[p^{*} \geq p,] we infer stem:[\|v\|_{L^{p}(\Omega)}=\|\tilde{v}\|_{L^{p}\left(\mathbb{R}^{d}\right)} \leq]
stem:[c\|\tilde{v}\|_{L^{p *}\left(\mathbb{R}^{d}\right)},] yielding <<B61>>

[[LemmaB63]]
.Lemma B63
****
Let stem:[1 \leq p<+\infty] and stem:[\Omega] be a bounded connected open set having the stem:[(1, p)] - extension property. Let stem:[f] be a linear form on stem:[W^{1, p}(\Omega)] whose restriction on constant functions is not zero. Then, there is stem:[c_{p, \Omega}>0] such that
[stem]
++++
\forall v \in W^{1, p}(\Omega), \quad c_{p, \Omega}\|v\|_{W^{1, p}(\Omega)} \leq\|\nabla v\|_{L^{p}(\Omega)}+|f(v)|
++++
****
**Proof**. Use the Petree-Tartar Lemma. To this end, set stem:[X=W^{1, p}(\Omega), Y=] stem:[\left[L^{p}(\Omega)\right\]^{d} \times \mathbb{R}, Z=L^{p}(\Omega),] and stem:[A: X \ni v \mapsto(\nabla v, f(v)) \in Y .] Owing to
Lemma B. 29 and the hypotheses on stem:[f, A] is continuous and injective. Moreover, the injection stem:[X \subset Z] is compact owing to <<thmB46>> stem:[\square]
