= Formulation avec conditions de Dirichlet et de Neumann

On considère stem:[\Omega \subset \RR^3] tel que stem:[\partial \Omega = \partial \Omega_D \cap \partial \Omega_N].
On se donne stem:[\mathbf{g}: \partial \Omega_N \rightarrow \mathbb{R}^3] la charge normale(densité de force) sur stem:[\partial \Omega_N].
Le problème mélangeant condition de Dirichlet, imposant le déplacement, et de Neumann, imposant les contraintes normales, en élasticité linéaire s'exprime sous la forme suivante

.Problème mixte
****
[stem]
++++
\begin{align}
\nabla \cdot \stresst{\disp{d}} + \mathbf{f} = \mathbf{0} & \quad \mbox{ in } \Omega \\
\stresst{\disp{d}} = \lambda (\nabla \cdot \disp{d}) \Id + \mu (\nabla \disp{d} + \nabla \disp{d}^T) & \quad \mbox{ in } \Omega\\
\disp{d} = \mathbf{0} & \quad \mbox{ on } \partial \Omega_D\\
\stresst{\disp{d}} \normal = \mathbf{g} & \quad \mbox{ sur } \partial \Omega_N
\end{align}
++++
****

TIP: si stem:[g=\mathbf 0] sur stem:[\partial \Omega_N] on dira que la surface est laissée libre (de force ou de charge).

Le choix naturel d'espace fonctionel est stem:[X\equiv[H^1_{0,\partial \Omega_D}(\Omega)\]^3] pour la solution et les fonctions tests avec
[stem]
++++
X\equiv [H^1_{0,\partial \Omega_D}(\Omega)]^3=\left\{ \disp{v} \in [H^1(\Omega)]^3\ \mathrm{s.t.}\ \disp{v} = \mathbf{0}\ \mbox{ on } \partial \Omega_D \right\}
++++

La formulation variationnelle est obtenue en faisant le produit scalaire de la première équation par la fonction test
stem:[\mathbf{v}].
Observez de plus que:

[stem]
.Intégration par partie (Théorème de la divergence)
++++
\int_\Omega \nabla\cdot \stresst{\disp{d}}\ \cdot\ \mathbf{v} = \int_\Omega \stresst{\disp{d}}\ :\ \nabla \mathbf{v} - \int_{\partial \Omega} \mathbf{v} \cdot ( \stresst{\disp{d}} \normal)
++++

et

[stem]
.Symmetry of stem:[\stresst{\disp{d}}]
++++
\stresst{\disp{d}} : \nabla \mathbf{v} = \stresst{\disp{d}} : \deformt{\disp{v}}
++++

et nous obtenons

[stem]
++++
\int_\Omega \stresst{\disp{d}}\ :\ \deformt{\disp{v}} - \int_{\partial \Omega} \mathbf{v} \cdot ( \stresst{\disp{d}} \normal) = \int_\Omega \mathbf{f}\cdot \disp{v}
++++

La formulation faible s'écrit alors

[[mixed-weak]]
.Formulation faible du problème mixte
****
On cherche stem:[\disp{d} \in H^1_{0,\partial \Omega_D}(\Omega)\]^3] telle que
[stem]
++++
a(\disp{d},\disp{v}) = \int_\Omega f \cdot \disp{v} + \int_{\partial \Omega_N} \disp{g} \cdot \normal \quad  \forall v \in [H^1_{0,\partial \Omega_D}(\Omega)]^3
++++
Avec
[stem]
++++
a(\disp{d},\disp{v}) = \int_\Omega \stresst{\disp{d}}\ :\ \deformt{\disp{v}} = \int_\Omega \lambda \nabla \cdot \disp{d} \nabla \cdot \disp{v} + \int_\Omega 2 \mu \deformt{\disp{d}} : \deformt{\disp{v}}
++++
****

NOTE: En mécanique du continuum, la fonction de test v joue le rôle d'un _déplacement virtuel_ et la formulation faible précédente exprime le principe du _travail virtuel_.

== Problème bien posé

Le  <<mixed-weak,problème faible>> avec condition aux limites mixtes est bien posé grâce à l'inégalité de Korn.

== Finite element approximation

On considère une approximation du problème mixte par  élément fini stem:[H^1]-conforme à partir d'une famille de maillages affines, géométriquement conformes stem:[\{\calTh\}_{h>0}] et d'un élément fini de Lagrange de degré stem:[k\geq 1] décrit par stem:[\{\hat{K}, \hat{P}, \hat{\Sigma} \}].
On introduit Ensuite
[stem]
++++
X^k_h = \left\{  \disp{v}_h \in [C^0(\Omega)]^3 | \forall K \in \calTh, \disp{v}_h \circ \varphi_K^{\mathrm{geo}} \in [\hat{P}]^3;\ \disp{v}_h = \disp{0} \mbox{ on } \partial \Omega_N \right\}
++++

.Problème discret
****
Trouver stem:[\disp{d} \in X_h^k] telle que
[stem]
++++
a(\disp{d}_h,\disp{v}_h) = \int_\Omega f \cdot \disp{v}_h + \int_{\partial \Omega_N} \disp{g} \cdot \normal \quad  \forall v_h \in X_h^k
++++
****

.Proposition: Estimation a priori pour le problème mixte
****
Soit stem:[\disp{d}] une solution du  <<mixed-weak,problème faible>>, on a tout d'abord que stem:[\lim_{h\rightarrow 0} \|\disp{d}-\disp{d}_h\|_{1,\Omega} = 0].
De plus si stem:[\disp{d} \in [H^{l+1}(\Omega)\]^3 \cap X^k_h] pour stem:[l\in \{1\ldots k\}] alors il existe stem:[c] telle que
[stem]
++++
\forall h, \quad \|\disp{d}-\disp{d}_h\|_{1,\Omega} \leq c h^l |\disp{d}|_{l+1,\Omega}.
++++
****
