= Expériences numériques
:page-vtkjs: true

Ce document présente des expériences numériques en élasticité linéaire.

== Cantilever

We consider a 2D link:https://en.wikipedia.org/wiki/Cantilever[Cantilever] structure which is clamped on one side and free of constraints otherwise.

The dimensions are stem:[\Omega=[0,L\]\times[0,1\] \subset \RR^2] with stem:[L=10].

.Young Modulus and Poisson Ratio values
|===
| stem:[E] (Pa) | stem:[\nu]
| 1e06 | 0.3
|===

The external forces are set to be the gravity, stem:[\mathbf{f}=-9.81 \vec\jmath]

The boundary conditions read:

* at stem:[x=0], stem:[\disp{d} = \disp{0}]

It means that on stem:[\partial \Omega \backslash
x=0], we have stem:[\stresst{\disp{d}} \normal = \disp{0}].

The command line reads:
----
./feelpp_qs_elasticity_2d --config-file /feel/testcases/quickstart/elastivity/cantilever/cantilever.cfg
----

The results on Paraview

.2D Cantilever
++++

<div class="stretchy-wrapper-16_9">
<div id="vtkVisuSection2" style="margin: auto; width: 100%; height: 100%;      padding: 10px;"></div>
</div>
<script type="text/javascript">
feelppVtkJs.createSceneImporter( vtkVisuSection2, {
                                 fileURL: "https://girder.math.unistra.fr/api/v1/file/5aef723db0e9574027047f6c/download",
                                 objects: { "deformation":[ { scene:"u", name:"displacement" } ],
                                            "geometry":[ { scene:"geometry", name:"cantilever" } ] }
                               } );
</script>

++++

++++
<div class="stretchy-wrapper-16_9">
<div id="vtkVisuSection3" style="margin: auto; width: 100%; height: 100%;      padding: 10px;"></div>
</div>
<script type="text/javascript">
feelppVtkJs.createSceneImporter( vtkVisuSection3, {
                                 fileURL: "https://girder.math.unistra.fr/api/v1/file/5affc155b0e9574027048059/download",
                                 objects: { "reference":[ { scene:"cantilever-pure-traction", name:"Cantilever" }, { scene:"displacement", name:"Displacement" } ],
                                            "deformed":[ { scene:"deformed", name:"Cantilever Rotated" } ] }
                               } );
</script>

++++
