[glossary]
= Glossary

[glossary]
Conductivity:: Conductivity of a solid is the heat flow per unit area in the normal direction within the solid body as a result of temperature difference.

Heat flux(conduction):: The heat flux by conduction stem:[q''(W/m2)] is the heat transfer rate per unit area perpendicular to the direction of transfer, and it is proportional to the temperature gradient in this direction. We have the Fourier law in the multi-dimensional case:
+
[stem]
++++
q'' = -k \nabla T
++++

Heat Rate(conduction):: The heat rate by conduction, stem:[q (W)], through a plane wall of area stem:[A] is then the product of
the flux and the area, stem:[q = q'' \cdot A].

Specific heat:: It is the energy required to raise the temperature of unit mass through one degree temperature rise.

Adiabatic condition:: An adiabatic condition means that heat is not allowed to transfer across the boundary. In other words it means a perfectly insulated boundary. Symmetry boundaries are adiabatic.

Emmissivity:: This terminology is used in the context of radiation. It is the ratio of the total energy emitted by a surface to the total energy emitted by a black surface at the same temperature.

View factor:: In the radiation heat transfer context, it is the ratio of the energy incident on the second body to the energy emitted by the first body. Sometimes, it is also referred to as a geometric factor or form factor.

Thermal stress:: Stress induced in a structure or body as a result of thermal loading.

Phase change:: Substance subjected to temperature changes may transfer from solid state to liquid and/or gaseous state. During change of phase the latent heat is either released or absorbed.