Thermo-Electric Toolbox
=======================
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

Let $$\Omega \subset \mathbb{R}^d, d=2,3$$ with $$\partial\Omega=\Gamma=\Gamma_{C}\cup\Gamma_{T}=\Gamma_E\cup\Gamma_{in}\cup\Gamma_{out}$$.
We are interested in defining and solving an thermo-electric model involving the coupling of electrostatic and heat transfer models.

== Electrostatic problem
We need to find the electric potential $$V$$ by solving:
$$
\begin{align}
\nabla\cdot(-\sigma\nabla V) &= 0 &\text{ in } \Omega
\end{align}
$$where $$\sigma$$ is the electric conductivity. We denote by $$\mathbf{j} = - \sigma \nabla V$$ the electric current. On the boundary, we impose the electric potential on $$\Gamma_{in}$$ and $$\Gamma_{out}$$:

- $$V=0$$ on $$\Gamma_{in}$$
- $$V=V_{out}$$ on $$\Gamma_{out}$$.

We also want the other boundaries to be electrically insulating:

- $$-\sigma\nabla V\cdot\mathbf{n}=\mathbf{j}\cdot\mathbf{n} = 0$$ on $$\Gamma_E$$

== Heat transfer problem

Find the temperature $$T$$ by solving a thermal problem, where the source term comes from Joule effect:
$$
\begin{align}
\nabla\cdot(-k\nabla T) &= \sigma\nabla V\cdot \nabla V &\text{ in } \Omega
\end{align}
$$where $$k$$ is the thermal conductivity. +
The thermal exchanges with air are not considered, leading to a Neumann condition on $$\Gamma_T$$. While the thermal exchanges with the cooling water depends on a heat transfer coefficient $$h$$ and the cooling temperature $$T_c$$, leading to a Robin condition on $$\Gamma_C$$:

- $$-k\nabla T\cdot \mathbf{n} = 0$$ on $$\Gamma_T$$
- $$-k\nabla T\cdot\mathbf{n} = h(T-T_c)$$ on $$\Gamma_{C}$$


== Thermo-Electric problem

In the thermo-electric model, we have 4 parameters
$$\sigma, k, T_c, h$$ which can be scalars or fields.

We gather in the following table parameter ranges, nominal values as well as units for $$\sigma, k, T_c, h$$.

.Table of parameters for the simulation
|===
| Parameters | Ranges |  Nominal value | Units
| $$\sigma$$ | $$[52.10^{6};58.10^{6}]$$ | $$53\cdot 10^{6}$$ | $$S \cdot m^{-1}$$
| $$k$$ | $$[360;380]$$| $$370$$ | $$W\cdot m^{-1} \cdot K^{-1}$$
| $$T_c$$ | $$[293;310]$$ | 300 | K
| $$h$$ | $$[70000;90000]$$ | $$850000$$ | $$W \cdot m^{-2} \cdot K^{-1}$$
|===

In the linear case, we first solve for $$V$$ and then  for $$T$$ using $$V$$ to compute the joule effect that generate heat inside $$\Omega$$.

== Running the Thermo-electric application

Using link:../../02-docker/feelpp-containers.adoc[] , you can run Feel++ model application and in particular the thermo-electric model using the following command

.Docker command
[source,shell]
----
$ docker run -it -v $HOME/feel:/feel feelpp/feelpp-toolboxes:latest
----

Then type the following command in docker environment to run the model

.Running Thermo-Electric model
[source,shell]
----
$ cd Testcases/models/thermoelectric/test
$ mpirun -np 4 /usr/local/bin/feelpp_toolbox_thermoelectric_3d --config-file model.cfg
----
