// -*- mode: adoc -*-
[[cha:appr-de-probl]]
= Approximation de problèmes coercifs

Dans ce chapitre, on s’intéresse à l’approximation de problèmes coercifs:

* le Laplacien et des variantes sur les conditions aux limites et le l’équation elle-même;
* l’élasticité linéaire qui permet de modéliser de petites déformations d’un milieu continu déformable.

[[sec:le-laplacien]]
== Le Laplacien

On s’instéresse dans cette section à l’_approximation élément fini conforme_ du problème suivant:


[[prob:1]]
.Problème: Formulation forte du Laplacien
****
On cherche stem:[u] telle que
[[eq:64]]
[stem]
++++
    \begin{split}
      -\Delta u &= f \mbox{ dans } \Omega\\
      u &= 0 \mbox{ sur } \partial \Omega
\end{split}
++++
****

[[sec:cadre-mathematique]]
=== Cadre Mathematique

On suppose que stem:[f \in L^2(\Omega)].

La formulation faible du problème <<prob:1>> est la suivante:


[[prob:2]]
.Formulation faible pour des conditions de Dirichlet homogènes
****
On cherche stem:[u \in H^1_0(\Omega)] telle que
[stem]
++++
\label{eq:65}
    \int_\Omega \nabla u \cdot \nabla v =  \int_\Omega f\, v,\quad \forall v \in H^1_0(\Omega)
++++
****

[[sec:probleme-bien-pose]]
=== Problème bien posé

Introduisons

* stem:[V = H^1_0(\Omega)] doté de la norme
stem:[\|\cdot\|_{1,\Omega}] telle que
stem:[\|v\|_{1,\Omega} = (\|v\|^2_{0,\Omega} + \|\nabla v\|^2_{0,\Omega})^{1/2}]
* la forme bilinéaire stem:[a \in \mathcal{L}(V \times V, \RR)]
telle que stem:[a(u,v) = \int_\Omega
  \nabla u \cdot \nabla v ]
* la forme linéaire stem:[\ell \in \mathcal{L}(V, \RR)] telle que
stem:[l(v) = \int_\Omega   f \nabla v ]

Le problème <<prob:2>> s’écrit sous forme abstraite

[[prob:5]]
.Problème:
****
On cherche stem:[u \in V] telle que
[stem]
++++
    a(u, v) = \ell(v), \quad \forall v \in V
++++
****

L’espace stem:[V] est un espace de Hilbert et les formes stem:[a] et stem:[\ell] sont continues sur stem:[V\times V] et stem:[V] respectivement.

Il ne reste plus qu’à vérifier si le problème est bien posé (existence d’une solution unique).

Pour cela on utilise démontre la _coercivité_ de la forme bilinéaire stem:[a] sur stem:[V \equiv H^1_0(\Omega)].

Ceci se fait grâce au lemme suivant:

[[lem:1]]
.Lemma
****
Soit stem:[\Omega] un ouvert borné de stem:[\R{d}].
Il existe une constante stem:[c_\Omega] (dépendente de stem:[\Omega] telle que
[stem]
++++
    \forall v \in H^1_0(\Omega),\quad \|v\|_{0,\Omega} \le c_\Omega \|\nabla v\|_{0,\Omega}
++++
****

[[rem:24]]
NOTE: stem:[c_\Omega] est homogène à une longeur et peut être interprétée comme une mesure caractéristique de stem:[\Omega].

Grâce à l’inégalité de Poincaré, on a le résultat suivant

[[prop:7]]
.Proposition
****
La forme bilinéaire stem:[a] du problème <<prob:2>> est _coercive_
****

.Preuve
****
On note tout d’abord que par l’inégalité de Poincaré et la définition de
stem:[\|\cdot\|_{1,\Omega}]
[[eq:68]]
[stem]
++++
      \|v\|^2_{1,\Omega} \le (1 + c^2_\Omega) \|\nabla v\|^2_{0,\Omega}
++++
On en déduit que
[[eq:67]]
[stem]
++++
\forall v \in H^1_0(\Omega),\quad a(v,v) = \|\nabla v\|^2_{0,\Omega} \ge \frac{1}{1+c^2_\Omega} \|v\|^2_{1,\Omega}
++++

Le Lemme de Lax-Milgram <<thr:12>> permet alors de conclure sur l’existence d’une solution unique pour le problème <<prob:2>>.
****

[[sec:appr-conf]]
=== Approximation conforme

On utilise une approximation conforme par éléments finis de Lagrange.

On considère stem:[\Omega] un polygone ou polyhèdre régulier de stem:[\RR^2] ou stem:[\RR^3] respectivement et un maillage stem:[\calTh = \{K_e\}_{e=1...\Ne}] de stem:[\Omega].

On considère un élément fini de référence stem:[(\hat{K},\hat{P},\hat{\Sigma})] tel que stem:[\Pk \subset \hat{P}] et stem:[k+1 > \frac{d}{2}], voir le théorème <<thr:16>>.

On note
[[eq:70]]
[stem]
++++
  L^k_{c,h} = \{ v_h \in C^0(\bar{\Omega}); \forall K \in \mathcal{T}_h,\ v_h   \circ T_K \in \hat{P}\}
++++
où stem:[T_K] est la tranformation géométrique de stem:[\hat{K}] dans stem:[K].

* Si on utilise stem:[\hat{P}=\Pk{k}] on a stem:[L^k_{c,h} = P^k_{c,h}].
* Si on utilise stem:[\hat{P}=\Qk{k}] on a stem:[L^k_{c,h} = Q^k_{c,h}].

Afin de construire un espace d’approximation conforme stem:[V_h \subset V =H^1_0(\Omega)] on prend
[stem]
++++
\label{eq:71}
V_h = L^k_{c,h} \cap H^1_0(\Omega)
++++
c’est à dire que les fonctions de stem:[V_h] satisfont les conditions aux limites outre le fait d’être dans stem:[L^k_{c,h}].

Le problème discret s’écrit alors

[[prob:6]]
.Problème
****
Trouver stem:[u_h \in V_h] telle que
[stem]
++++
    a(u_h,v_h) = \ell(v_h),\, \forall v_h \in V_h
++++
****

qui est bien posé (existence et unicité de stem:[u_h]) car stem:[a] est coercive sur stem:[V] et que stem:[V_h \subset V].

On a le résultat suivant:

[[thr:17]]
.Théorème
****
On suppose que stem:[u] solution de <<prob:2>> est dans
stem:[H^{k+1}(\Omega) \cap   H^1_0(\Omega)], alors il existe une constante stem:[c_1] telle que pour tout stem:[h]
[[eq:73]]
[stem]
++++
    \|u-u_v\|_{1,\Omega} \le c_1 h^k |u|_{k+1,\Omega}
++++
et il existe
une constante stem:[c_2] telle que pour tout stem:[h]
[[eq:74]]
[stem]
++++
    \|u-u_v\|_{0,\Omega} \le c_2 h^{k+1} |u|_{k+1,\Omega}
++++
****

.Preuve
****
La preuve de (<<eq:73>>) est obtenue grâce au lemme de Cea (<<eq:cea>>) et du théorème d’interpolation (<<eq:62>>).

La preuve de (<<eq:74>>) est obtenue grâce au lemme d’Aubin-Nitsche qui permet d’affirmer qu’il existe une constante stem:[c] telle que

[[eq:75]]
[stem]
++++
    \|u-u_h\|_{0,\Omega} \leq c h |u-u_h|_{1,\Omega}
++++
et donc que (<<eq:74>>) se déduit de (<<eq:74>>).
****

[[sec:impl-en-feelpp]]
=== Implémentation avec {feelpp}

Avec {feelpp}, on ne construit pas explicitement l’espace stem:[V_h] mais stem:[L^k_{c,h}].

Le traitement des conditions aux limites de Dirichlet du problème (<<eq:64>>) peut être effectué de diverses façons, nous en verrons une.

Commencons par le maillage, dans un premier temps nous définissons le type du maillage contenant soit des éléments de type simplexe (segment,triangle, tetrahèdre) ou de type hypercube (segment, quadrangle, hexahèdre).

[source,cpp]
********
  // un maillage de simplexe dans $\R{d}$ telle que la transformation
  // géométrique $T_K,\ K \in \calTh$  soit affine
  typedef Mesh<Simplex<d,1> > mesh_type;

  // un maillage d'hypercube dans $\R{d}$ telle que la transformation
  // géométrique $T_K,\ K \in \calTh$  soit affine en chacune des variables
  // typedef Mesh<Hypercube<d,1> > mesh\_type;

  // generate the mesh associated to the unit square $[0,1]^2$ using triangles
  auto mesh = unitSquare();
********

[[rem:25]]
NOTE: Le mot clé `auto` permet de faire de l’inférence de type, pour plus de détails consultez
link:http://fr.wikipedia.org/wiki/C%2B%2B11#Inf.C3.A9rence_de_types[la page C++11 de Wikipedia].

Ensuite nous pouvons définir l’espace stem:[L^k_{c,h}],

[source,cpp]
********
  // Vh est une structure de donnée allouée dynamiquement
  auto Vh = Pch<1>( mesh );
  // u est un élément de Vh
  auto u = Vh->element();
  // u est un autre élément de Vh
  auto u = Vh->element();
********

À présent, nous définissons les formes bilinéaires stem:[a] et stem:[\ell] qui sont respectivement des formes bilinéaires et linéaires.

[source,cpp]
********
  auto a = form2( _test=Vh, _trial=Vh ); <1>
  a = integrate( _range=elements(mesh), _expr=gradt(u)*trans(grad(v)) ); <2>

  auto l = form1( _test=Vh ); <3>
  l = integrate( _range=elements(mesh), _expr=f*id(v) ); <4>
********
<1> stem:[a \in \mathcal{L}(V_h \times V_h,\ \RR)]
<2> stem:[a = \sum_{e=1...\Ne} \int_{K_e} \nabla \varphi_j \cdot \nabla \varphi_i,\quad  i,j=1...,\dim{V_h}]
<3> stem:[\ell \in \mathcal{L}(V_h,\ \RR)]
<4> stem:[\ell = \sum_{e=1...\Ne} \int_{K_e} f  \varphi_i,\quad  i=1...,\dim{V_h}]


Afin de traiter les conditions aux limites de Dirichlet homogènes, on peut utiliser le mot-clé `on` qui permet de les imposer de manière forte.

[source,cpp]
********
  a += on(_range=boundaryfaces(mesh), _element=u, _rhs=l, _expr=constant(0.) );
********

[[rem:26]]
NOTE: Le mot-clé `constant` permet de transformer une type numérique ( entier, flottant) en une expression utilisable par le langage de {feelpp}.
Notez également l’opération `+=` qui permet de rajouter le traitement des conditions de Dirichlet tout en gardant les contributions précédentes.
L’opération `=` aurait d’abord remis à stem:[0] les entrées de la matrice associée à stem:[a].

Enfin nous pouvons résoudre le problème <<prob:6>>

[source,cpp]
----
  a.solve( _rhs=l, _solution=u );
----

Le listing complet

[[sec:cond-aux-limit]]
=== Conditions aux limites

[[sec:cond-aux-limit-1]]
==== Conditions aux limites de Dirichlet non homogène


On suppose toujours stem:[f \in L^2(\Omega)] et on se donne une fonction stem:[g \in C^{0,1}(\partial \Omega)]

[stem:[g] est Lipschitzienne
sur stem:[\partial
\Omega]].

On s’intéresse au problème suivant:

[env.problem#prob:7]
****
On cherche stem:[u : \Omega \rightarrow \RR] telle que

[[eq:76]]
[stem]
++++
    \begin{split}
    -\Delta u &= f \mbox{ dans } \Omega\\
    u &= g \mbox{ sur } \partial \Omega
    \end{split}
++++
****

[[rem:27]]
NOTE: L’hypothèse stem:[g \in C^{0,1}(\partial \Omega)] permet d’affirmer qu’il existe stem:[u_g \in H^1(\Omega)] telle que stem:[u_{g_{|\partial \Omega}} = g].

On se ramène au problème avec conditions de Dirichlet homogène en faisant le change d’inconnue stem:[u_0=u-u_g] et on s’intéresse au problème suivant:


[[prob:8]]
.Problème
****
On cherche stem:[u_0 \in H^1_0(\Omega)] telle que
[[eq:77]]
[stem]
++++
    a(u_0,v) = \ell(v) - a(u_g,v),\quad \forall v \in H^1_0(\Omega)
++++
****

Ce problème est _bien posé_ d’après Lax-Milgram, voir section précédente.


[[thr:18]]
.Théorème
****
On suppose que stem:[u] solution de [prob:8] est dans stem:[H^{k+1}(\Omega) \cap   H^1_0(\Omega)],
alors il existe une constante stem:[c_1] telle que pour tout stem:[h]

[[eq:73]]
[stem]
++++
    \|u-u_v\|_{1,\Omega} \le c_1 h^k |u|_{k+1,\Omega}
++++
et il existe une constante stem:[c_2] telle que pour tout stem:[h]
[[eq:74]]
[stem]
++++
    \|u-u_v\|_{0,\Omega} \le c_2 h^{k+1} |u|_{k+1,\Omega}
++++
****

Avec {feelpp}, les conditions Dirichlet non-homogènes sont traitées par exemple avec le mot-clé `on`.


.Conditions de Dirichlet non homogènes
[source,cpp]
********
  auto g = sin(2*pi*Px() ); <1>
  <2>
  ...
  a += on( _range=boundaryfaces(mesh), _expr=g ); <3>
********
<1>  définition de la fonction, p.ex stem:[g=sin(2 \pi x)]
<2>  définition de stem:[a]
<3>  ajout des conditions de Dirichlet non-homogènes

[[rem:28]]
NOTE: Il n’y a pas besoin de rajouter le terme stem:[a(u_g,v)] au second membre stem:[\ell(v)], il est pris en compte automatiquement par `on`.

Voici le listing complet de l’exemple du laplacien avec conditions de Dirichlet non-homogène

[[sec:cond-aux-limit-2]]
=== Condition aux limites de Neumann

Étant donnés un réel stem:[\mu] strictement positif, stem:[f \in L^2(\Omega)] et stem:[g \in L^2(\partial \Omega)], on s’intéresse au problème suivant:


[[prob:9]]
****
On cherche stem:[u : \Omega \rightarrow \RR] telle que
[[eq:78]]
[stem]
++++
    \begin{split}
      -\Delta u + \mu u &= f, \mbox{ dans } \Omega\\
      \partial_\Next u &= g, \mbox{ sur } \partial\Omega
    \end{split}
++++
****

où stem:[\partial_\Next u = \nabla u \cdot \Next = \sum_{i=1}^d n_i \partial_i u] dénote la dérivée normale de stem:[u] avec stem:[\Next=(n_1,...,n_d) \in \RR^d] la normale extérieure unitaire en un point du bord de stem:[\Omega].

La formulation faible s’écrit


[env.problem#prob:13]
****
On cherche stem:[u \in H^1(\Omega)] telle que
[[eq:79]]
[stem]
++++
    a( u, v ) = \ell(v),\ \forall v \in H^1(\Omega)
++++
avec
[[eq:80]]
[stem]
++++
    a( u, v ) =  \int_\Omega \nabla u \cdot \nabla v + \mu u v
++++
et
[[eq:81]]
[stem]
++++
    \ell( v ) =  \int_\Omega f v + \int_{\partial\Omega} g v
++++
****


On a
[[eq:82]]
[stem]
++++
  a(v, v) =  \int_\Omega \nabla v \cdot \nabla v + \mu v v \ge \min(1,\mu)
  \int_\Omega \nabla v \cdot \nabla v +  v v  = \min(1,\mu) \|v\|_{1,\Omega}, \quad
  \forall v \in H^1(\Omega)
++++
ce qui nous permet d’affirmer que stem:[a] est coercive sur stem:[H^1(\Omega)] et que le problème <<prob:13>> est bien posé grâce à Lax-Milgram.

On peut approcher le problème <<prob:13>> par des éléments finis de Lagrange.

On utilise la formulation développée dans la section <<sec:appr-conf>>
[[prob:13_1]]
.Problème
****
On cherche stem:[u_h \in P^k_{c,h}] tel que
[stem]
++++
a_h(u_h,w_h)=\ell(w_h), \quad \forall w_h \in P^k_{c,h}
++++
****

NOTE: Par rapport aux conditions de Dirichet, les conditions de Neumann sont directement (*naturellement*) traitées par la formulation faible.
Elles ne sont pas directement imposées dans l'espace et les fonctions tests peuvent prendre des valeurs non-nulles au bord.
Ces conditions sont traitées de manière approchée et non pas exacte.

L'analyse du problème <<prob:13_1>> est identique par le théorème <<thr:17>> aux mêmes estimations que dans le cas Dirichlet homogène.

==== Cas stem:[\lambda=0]

Le cas stem:[\lambda=0] présente quelques difficultés techniques.

On a
[[prob:13_2]]
.Problème
****
On cherche stem:[u : \Omega \rightarrow \RR] telle que
[[eq:78.1]]
[stem]
++++
    \begin{split}
      -\Delta u &= f, \mbox{ dans } \Omega\\
      \partial_\Next u &= g, \mbox{ sur } \partial\Omega
    \end{split}
++++
****

NOTE: On observe ici qu'une condition nécessaire d'existence de solution est que
[stem]
++++
\int_\Omega f + \int_{\partial \Omega} g = 0
++++
de par le *théorème de la divergence*.

NOTE: la deuxième observation est que la solution de <<prob:13_2>> est connue à une constante additive près: si stem:[u] est solution  et stem:[c\in \RR] alors stem:[u+c] est également solution.

Il convient alors de chercher la solution dans l'espace fonctionel suivant
[stem]
++++
H^1_*(\Omega) = \{ v \in H^1(\Omega):\quad \int_\Omega v  = 0 \}
++++

La formulation faible du problème <<prob:13_2>>  s'écrit alors
[[prob:13_3]]
.Problème
****
On cherche stem:[u\in H^1_*(\Omega)], telle que
[stem]
++++
a(u,v) = \ell(v) \quad \forall v\in H^1_*(\Omega)
++++
avec stem:[a(u,v)=\int_\Omega \nabla u \cdot \nabla v].
****

Le caractère bien posé du problème <<prob:13_3>> résulte de la coercivité de stem:[a] sur stem:[H^1_*(\Omega)] qui elle-même résulte du Lemme suivante



.Lemme d'inégalité de Poincaré-Wirtinger
****
Soit stem:[\Omega] un ouvert borné de stem:[\RR^d], il existe une constante stem:[C_\Omega] telle que
[stem]
++++
\|v\| \leq C_\Omega \|\nabla v\|_{0,\Omega},\quad \forall v \in H^1_*(\Omega)
++++
****

Le problème <<prob:13_3>> peut être approché par des éléments finis de Lagrange ce qui conduit au problème discret suivant
[[prob:13_4]]
.Problème
****
On cherche stem:[u_h \in P^k_{c,h}] telle que
a_h(u_h,v_h)=\ell(v_h) \quad \forall v_h\in P^k_{c,h}
****

NOTE: L'espace d'approximation stem:[P^k{c,h}] n'est pas conforme dans stem:[H^1_*(\Omega)]

[NOTE]
====
le problème <<prob:13_4>> est *singulier*, il a une infinité de solution.
L'une d'entre elle peut être approchée par une méthode itérative de type gradient conjugué.
Notons stem:[u^*_h] cette solution alors la solution à moyenne nulle est
[stem]
++++
u_h=u^*_h-\frac{1}{|\Omega|}\int_\Omega u^*_h
++++
Il s'agit donc d'effectuer a posteriori du calcul un post-processing pour se ramener à la solution à moyenne nulle.
Dans {feelpp} on utilisera la fonction `mean`
[source,cpp]
********
// ...
// u est la solution du problème discret
a.solve(_rhs=l,_solution=u);

// calcul de la valeur moyenne de u
double meanu = mean(_range=elements(mesh),_expr=idv(u))(0,0);

// calcul de la solution à moyenne nulle u = u - meanu
u.add(-meanu);
********
====


[[sec:cond-aux-limit-robin]]
=== Conditions aux limites de Robin


Étant donnés un réel stem:[\mu] strictement positif, stem:[f \in L^2(\Omega)] et stem:[g \in L^2(\partial \Omega)], on s’intéresse au problème suivant:

[[prob:14]]
.Problème
****
On cherche stem:[u : \Omega \rightarrow \RR] telle que
[[eq:83]]
[stem]
++++
    \begin{split}
      -\Delta u  &= f, \mbox{ dans } \Omega\\
      \mu u + \partial_\Next u &= g, \mbox{ sur } \partial\Omega.
    \end{split}
++++
****

La formulation faible s’écrit


[[prob:15]]
.Problème
****
On cherche stem:[u \in H^1(\Omega)] telle que
[stem]
++++
\label{eq:84}
    a( u, v ) = \ell(v),\ \forall v \in H^1(\Omega)
++++
avec
[[eq:85]]
[stem]
++++
    a( u, v ) =  \int_\Omega \nabla u \cdot \nabla v + \int_{\partial     \Omega} \mu u v
++++
et
[[eq:86]]
[stem]
++++
    \ell( v ) =  \int_\Omega f v + \int_{\partial\Omega} g v
++++
****

On a
[[eq:69]]
[stem]
++++
  \begin{split}
    a(v, v) & =  \int_\Omega \nabla v \cdot \nabla v + \int_{\partial\Omega} \mu v v \\
    & \geq \min(1,\mu)\left( \int_\Omega \nabla v \cdot \nabla v +
      \int_{\partial\Omega} v v\right)  \\
    &\geq \min(1,\mu) \|v\|_{1,\Omega}, \quad \forall v \in H^1(\Omega)
  \end{split}
++++

La forme bilinéaire stem:[a] est donc coercive et le problème <<prob:15>> est bien posé grâce à Lax-Milgram.

On considère le problème discret suivant

[[prob:11]]
.Problème
****
On cherche stem:[u_h \in P^k_{c,h}(\Omega)] telle que
[[eq:87]]
[stem]
++++
    a_h(u_h,v_h) = \ell(v_h)\quad \forall v_h \in P^k_{c,h}
++++
****

Le problème est _bien posé_ (stem:[P^k_{c,h} \subset H^1(\Omega)]).

NOTE: Comme pour le problème avec conditions de Neumann, les fonctions tests peuvent prendre des valeurs non nulles au bord.
Les conditions de Robin(ou Fourier) ne sont satisfaites que de manière _approchée_ et non pas _exacte_.

La convergence de stem:[u_h] est donnée par le théorème <<thr:17>>.

Considérons stem:[\Omega=[0,1]^2] et les données stem:[\mu=0.01], stem:[f=1] et stem:[g=0].
