// -*- mode: adoc -*-
[[cha:appr-de-probl-1]]
= Approximation de problèmes mixtes

[[sec:model-problems]]
== Model Problems

We consider now model problems as systems of PDEs where several
functions are unknowns and which don’t play the same roles
_mathematically_ and _physically_.

Stokes::
[[eq:chmixte:98]]
\[
      \left\{\begin{array}[c]{rl}
          -\Delta u + \nabla p & = f\ \mbox{ in } \Omega\\
          \nabla \cdot u & = 0\ \mbox{ in } \Omega
          \end{array}\right.
\]
where latexmath:[u: \Omega \mapsto \RR^d] is a velocity and latexmath:[p: \Omega \mapsto \RR] is a pressure.

Darcy::
[[eq:chmixte:99]]
\[
      \left\{\begin{array}[c]{rl}
          \sigma + \nabla u & = f\ \mbox{ in } \Omega\\
          \nabla \cdot \sigma & = g\ \mbox{ in } \Omega
          \end{array}\right.
\]
where latexmath:[\sigma: \Omega \mapsto \RR^d] is a velocity and latexmath:[u: \Omega \mapsto \RR] is a hydraulic charge(pressure).

[[applications]]
== Applications

We shall focus on Stokes, but the abstract setting of the next section is the same for Stokes and Darcy.

Stokes and incompressible Navier-Stokes for Newtonian fluids::
The Stokes model is the basis for fluid mechanics models and is a simplication of the Navier-Stokes equations where the viscous effects/terms are much bigger than the convective ones
[[eq:chmixte:3]]
\[
    \left\{\begin{array}[c]{rl}
           \rho( \frac{\partial u}{\partial t} + u \cdot \nabla u) - \nu \Delta u + \nabla p & = f\ \mbox{ in } \Omega\\
           \nabla \cdot u & = 0\ \mbox{ in } \Omega
           \end{array}\right.
\]
The first equation results from the conservation of momentum and the second from the conservation of mass.

The well-posedness of these problems results from a so-called which is not automatically transfered at the _discrete level_.

In practice In order to ensure that the finite element approximation is well-posed, we will need to choose approximation spaces that satisfy a _compatibility condition_ that ensures that a _discrete inf-sup condition_ is satisfied.

[[sec:saddle-point-probl]]
== Saddle point problems

[[abstract-continuous-setting]]
=== Abstract Continuous Setting

Denote

* latexmath:[X] and latexmath:[M] two Hilbert spaces.footnote:[An euclidian space which is complete for the norm induced by the scalar product]
* two linear forms latexmath:[f \in X'=\mathcal{L}(X, \RR)] and latexmath:[g \in M'=\mathcal{L}(M, \RR)]
* latexmath:[a \in \mathcal{L}(X\times X, \RR)] and latexmath:[b \in \mathcal{L}(X\times M, \RR)] two bilinear forms

We are interested in the following abstract problem:


[env.problem#prob:chmixte:1]
--
Look for latexmath:[(u,p) \in X \times M] such that
[[eq:chmixte:4]]
\[
      \left\{
        \begin{array}[c]{rl}
          a(u,v) + b(v,p) & = f(v), \quad \forall v \in X\\
          b(u,q) & = g(q), \quad \forall q \in M
        \end{array}
        \right.
\]
--

[[definition-of-a-saddle-point-problem]]
==== Definition of a saddle point problem

[env.definiton#def:chmixte:1]
--
If the bilinear form latexmath:[a] is _symmetric_ and positive on latexmath:[X\times X], we say that <<prob:chmixte:1>> is a _saddle point problem_.
--

The structure of the problem is as follows

* the space of solution is the same of the test space
* the unknown latexmath:[p] does not appear in the second equation
* the unknown functions latexmath:[u] and latexmath:[p] are coupled via the same bilinear form latexmath:[b] is the first and second equation.

The next question is :

[[sec:well-posed-problemframe]]
=== Well posed problem

[[reformulation]]
==== Reformulation


Let’s rewrite Problem <<prob:chmixte:1>>.

Denote latexmath:[V=X\times M] and introduce latexmath:[c \in \mathcal{L}(V\times V, \RR)] such that

[[eq:chmixte:5]]
\[
c((u,p),(v,q)) = a(u,v)+b(v,p)+b(u,q)
\]
and latexmath:[h\in \mathcal{L}(V,\RR)] such that
[[eq:chmixte:6]]
\[
h(v,q) = f(v)+g(q)
\]
then problem <<prob:chmixte:1>> reads

[env.problem#prob:chmixte:2]
--
Look for latexmath:[(u,p) \in V] such that
[[eq:chmixte:7]]
\[
        \begin{array}[c]{rl}
          c((u,p), (v,q)) & = h(v,q), \quad \forall (v,q) \in V
          \end{array}
\]
--

[env.theorem#thr:chmixte:1]
--
We suppose that latexmath:[a] is coercive over latexmath:[X], the <<prob:chmixte:2>> is _well-posed_ if and only if the bilinear form latexmath:[b] satisfies the following
inf-sup condition:

there exists latexmath:[\beta > 0] such that
[[eq:chmixte:8]]
\[
\inf_{q \in M} \sup_{v \in X} \frac{b(v,q)}{||v||_X ||q||_M} \geq \beta
\]
--

NOTE: Lax-Milgram provides only a sufficient condition for well-posedness

NOTE: The form latexmath:[c] in <<prob:chmixte:2>> does not satisfy Lax-Milgram.

Let’s introduce the so-called _Lagrangian_ latexmath:[l \in \mathcal{L}(X\times M, \RR)] defined by
[[eq:chmixte:9]]
\[
l(v,q) =  \frac{1}{2} a(v,v) + b(v,q) - f(v) - g(q)
\]

[env.definition#def:chmixte:2]
--
We say that the point latexmath:[(u,p)\in X\times M] is a saddle point of latexmath:[l] if
[[eq:chmixte:10]]
\[
\forall (v,q) \in X\times M, \quad l(u,q) \leq l(u,p) \leq l(v,p)
\]
--

[env.proposition#prop:chmixte:1]
--
Under the hypothesys oF <<thr:chmixte:1>>, the Lagrangian latexmath:[l] defined by has a _unique_ saddle point.
Moreover this saddle point is the _unique solution_ of problem <<prob:chmixte:1>>.
--


[[sec:finite-elem-appr]]
== Finite element approximation


[[abstract-discrete-problem]]
=== Abstract Discrete Problem


We now turn to the approximation of the problem <<prob:chmixte:1>> by a _standard Galerkin method_ in a _conforming_ way.

Denote the two spaces latexmath:[X_h \subset X] and latexmath:[M_h \subset M], we consider the following problem:

[env.problem#prob:chmixte:3]
--
Look for latexmath:[(u_h,p_h) \in X_h \times M_h] such that
[[eq:chmixte:11]]
\[
      \left\{
        \begin{array}[c]{rl}
          a(u_h,v_h) + b(v_h,p_h) & = f(v_h), \quad \forall v_h \in X_h\\
          b(u_h,q_h) & = g(q_h), \quad \forall q_h \in M_h
        \end{array}
        \right.
\]
--

[env.theorem#thr:chmixte:2]
--
We suppose that latexmath:[a] is coercive over latexmath:[X] and that latexmath:[X_h \subset X] and latexmath:[M_h \subset M].

Then the <<prob:chmixte:3>> is _well-posed_ if and only if the following _discrete inf-sup condition_ is satisfied:

there exists latexmath:[\beta_h  > 0] such that
[[eq:chmixte:12]]
\[
\inf_{q_h \in M_h} \sup_{v_h \in X_h} \frac{b(v_h,q_h)}{||v_h||_{X_h} ||q_h||_{M_h}} \geq \beta_h
\]
--

The compatibility condition problem <<prob:chmixte:3>>, to be well posed, requires that the spaces latexmath:[X_h] and latexmath:[M_h] satisfy the condition.

This is known as the Babuska-Brezzi (BB) or Ladyhenskaya-Babuska-Brezzi (LBB).

Regarding error analysis, we have the following lemma

[env.lemma#lem:1]
--
Thanks to the Lemma of Céa applied to Saddle-Point Problems, the unique solution latexmath:[(u,p)] of problem <<prob:chmixte:3>> satisfies
[[eq:chmixte:13]]
\[
        \begin{array}[c]{rl}
          ||u-u_h||_X & \leq c_{1h} \inf_{v_h \in X_h}  ||u-v_h||_X + c_{2}
          \inf_{q_h \in M_h}  ||q-q_h||_M\\
          ||p-p_h||_X & \leq c_{3h} \inf_{v_h \in X_h}  ||u-v_h||_X + c_{4h} \inf_{q_h \in M_h}  ||q-q_h||_M
          \end{array}
\]
where

* latexmath:[c_{1h} = (1+\frac{||a||_{X,X}}{\alpha})(1+\frac{||b||_{X,M}}{\beta_h})] with latexmath:[\alpha]  the coercivity constant of latexmath:[a] over X.

* latexmath:[c_{2} = \frac{||b||_{X,M}}{\alpha}]

* latexmath:[c_{3h} = c_{1h} \frac{||a||_{X,X}}{\beta_h}], latexmath:[c_{4h} = 1+ \frac{||b||_{X,M}}{\beta_h}+\frac{||a||_{X,X}}{\beta_h}]
--

NOTE: The constants latexmath:[c_{1h}, c_{3h}, c_{4h}] are as large as latexmath:[\beta_h] is small.


[[sec:linear-system]]
=== Linear system associated

The discretisation process leads to a linear system.

We denote

* latexmath:[N_u = \dim {X_h}]
* latexmath:[N_p = \dim {M_h}]
* latexmath:[\{\phi_i\}_{i=1,...,N_u}] a basis of latexmath:[X_h]
* latexmath:[\{\psi_k\}_{k=1,...,N_p}] a basis of latexmath:[M_h]
* for all latexmath:[u_h = \sum_{i=1}^{N_u} u_i \phi_i], we associate latexmath:[U \in   \R{N_u}], latexmath:[U=(u_1,\ldots,u_{N_u})^T], the component vector of latexmath:[u_h] is latexmath:[\{\phi_i\}_{i=1,\ldots,N_u}]
* for all latexmath:[p_h = \sum_{k=1}^{N_p} u_k \psi_k], we associate latexmath:[P \in     \R{N_p}], latexmath:[P=(p_1,\ldots,p_{N_p})^T], the component vector of latexmath:[p_h] is latexmath:[\{\psi_k\}_{k=1,\ldots,N_p}]

The matricial form of problem <<prob:chmixte:3>> reads
[[eq:chmixte:15]]
\[
      \begin{bmatrix}
        \mathcal{A} & \mathcal{B}^T\\
        \mathcal{B} & 0
      \end{bmatrix}
      \begin{bmatrix}
        U \\
        P
      \end{bmatrix}
      =
      \begin{bmatrix}
        F\\
        G
        \end{bmatrix}
\]

where the matrix latexmath:[\mathcal{A} \in \R{N_u,N_u}] and latexmath:[\mathcal{B} \in     \R{N_p,N_u}] have the coefficients

[[eq:chmixte:16]]
\[
\mathcal{A}_{ij} = a(\phi_j,\phi_i), \quad \mathcal{B}_{ki} = b(\phi_i,\psi_k)
\]

and the vectors latexmath:[\mathcal{F} \in \R{N_u}] and latexmath:[\mathcal{G} \in \R{N_p}] have the coefficients

* latexmath:[F_i=f(\phi_i)]
* latexmath:[G_k=g(\psi_k)]

[[rem:2]]
[NOTE]
====
1.  Since latexmath:[a] is symmetric and coercive,
latexmath:[\mathcal{A}] is _symmetric positive definite_
2.  The matrix of the system is symmetric but not positive
3.  The inf-sup condition  is equivalent to the fact that
latexmath:[\mathcal{B}] is of _maximum rank_, _i.e._
latexmath:[\ker(\mathcal{B}^T)
       = \{0 \}].
4.  From theorem [thr:chmixte:2], the matrix of the system  is
invertible
====

[WARNING]
.When the inf-sup is not satisfied
====
The counter examples when the inf-sup condition  is not satisfied(e.g. latexmath:[\mathcal{B}] is not maximum rank ) occur usually in two cases:

Locking::
latexmath:[\dim {M_h} > \dim {X_h}]: the space of pressure is too large for the matrix latexmath:[\mathcal{B}] to be maximum rank.
In that case latexmath:[\mathcal{B}] is injective (latexmath:[\ker(\mathcal{B}) = \{0\})]. We call this _*locking*_.

Spurious modes::
there exists a vector latexmath:[Q^* \neq 0] in latexmath:[\ker(\mathcal{B}^T)].
The discrete fieldlatexmath:[q^*_h] in latexmath:[M_h], latexmath:[q^*_h=\sum_{k=1}^{N_p} Q^*_k \psi_k], associated is called a _*spurious mode*_.
latexmath:[q^*_H] is such that
[[eq:chmixte:14]]
\[
b(v_h,q^*_h)=0.
\]
====

We now introduce the _Uzawa matrix_ as follows

[env.definition#uzawa]
--
The matrix
[[eq:chmixte:17]]
\[
\mathcal{U} = \mathcal{B} \mathcal{A}^{-1} \mathcal{B}^T
\]
is called the _Uzawa matrix_. It is _symmetric positive definite_ from the
properties of latexmath:[\mathcal{A}], latexmath:[\mathcal{B}]
--

Applications:: The Uzawa matrix occurs when eliminating the velocity in system  and get a linear system on latexmath:[P]:
[[eq:chmixte:18]]
\[
\mathcal{U} P = \mathcal{B} \mathcal{A}^{-1} F - G
\]
then one application is to solve by solving iteratively and compute the velocity afterwards.

[[sec:mixed-finite-element]]
== Mixed finite element for Stokes

[[sec:vari-form-]]
=== Variational formulation

We start with the Well-posedness at the continuous level

* We consider the model problem  with homogeneous Dirichlet condition on velocity latexmath:[u = 0] on latexmath:[\partial \Omega]
* We suppose the latexmath:[f \in [L^2(\Omega)]^d] and latexmath:[g \in L^2(\Omega)] with
[[eq:chmixte:20]]
\[
\int_\Omega g = 0
\]
Introduce
[[eq:chmixte:19]]
\[
L^2_0(\Omega) = \Big\{ q \in L^2(\Omega): \int_\Omega q = 0 \Big\}
\]

The condition comes from the divergence theorem applied to the divergence equation and the fact that latexmath:[u=0] on the boundary
[[eq:chmixte:21]]
\[
\int_\Omega g = \int_\Omega \nabla \cdot u = \int_{\partial \Omega} u \cdot n = 0
\]
This is a _necessary_ condition for the existence of a solution latexmath:[(u,p)] for the Stokes equations with these boundary conditions.

We turn now to the variational formulation.

The Stokes problem reads

[env.problem#prob:chmixte:4]
--
Look for latexmath:[(u,p) \in [H^1_0(\Omega)]^d \times L^2_0(\Omega)] such that
[[eq:chmixte:25]]
\[
      \left\{
        \begin{array}[c]{rl}
          \int_\Omega \nabla u : \nabla v -\int_\Omega p \nabla \cdot v  & =
          \int_\Omega f \cdot v, \quad \forall v \in [H^1_0(\Omega)]^d\\
          \int_\Omega q \nabla \cdot u & = - \int_\Omega g q, \quad \forall q \in L^2_0(\Omega)
        \end{array}
        \right.
\]
--

We retrieve the problem <<prob:chmixte:1>> with latexmath:[X=[H^1_0(\Omega)]^d] and latexmath:[M=L^2_0(\Omega)] and
[[eq:chmixte:22]]
\[
      \begin{array}[c]{rlrl}
      a(u,v) &= \int_\Omega \nabla u : \nabla v,& \quad b(v,p) &= -\int_\Omega p
      \nabla \cdot v,\\
      \quad f(v) &=  \int_\Omega f \cdot v,& \quad g(q) &= - \int_\Omega g q
      \end{array}
\]

.Pressure up to a constant
NOTE: The pressure is known up to a constant, that’s why we look for them in latexmath:[L^2_0(\Omega)] to ensure uniqueness.

[[sec:finite-elem-appr-1]]
=== Finite element approximation

Denote latexmath:[X_h \subset [H^1_0(\Omega)]^d] and latexmath:[M_h \subset L^2_0(\Omega)]

[env.problem#prob:chmixte:5]
--
Look for latexmath:[(u_h,p_h) \in X_h \times M_h] such that
[[eq:chmixte:24]]
\[
      \left\{
        \begin{array}[c]{rl}
          \int_\Omega \nabla u_h : \nabla v_h + \int_\Omega p_h \nabla \cdot v_h
          & = \int_\Omega f \cdot v_h, \quad \forall v_h \in X_h\\
          \int_\Omega q_h \nabla \cdot u_h & = -\int_\Omega g q_h, \quad \forall q_h \in M_h
        \end{array}
        \right.
\]
--

[[rem:1]]
NOTE: This problem, thanks to theorem <<thr:chmixte:2>> is well-posed if and only if latexmath:[X_h] and latexmath:[M_h] are such that there exists latexmath:[\beta_h > 0]
[[eq:chmixte:26]]
\[
\inf_{q_h \in M_h} \sup_{v_h \in X_h} \frac{\int_\Omega q_h \nabla \cdot v_h}{||v_h||_{X_h} ||q_h||_{M_h}} \geq \beta_h
\]

[[sec:counter-examples]]
=== Some counter examples: bad finite element for Stokes

In this section, we present two classical bad finite element approximations.

[[finite-element-polyp_1polyp_0-locking]]
==== Finite element latexmath:[\poly{P}_1/\poly{P}_0]: locking


Thanks to the Euler relations, we have
[[eq:chmixte:28]]
\[
      \begin{array}[c]{rl}
        N_{\mathrm{cells}} - N_{\mathrm{edges}} + N_{vertices}  &= 1-I\\
      N^\partial_{\mathrm{vertices}} - N^\partial_{\mathrm{edges}} &= 0
      \end{array}
\]

where latexmath:[I] is the number of holes in latexmath:[\Omega].

We have that latexmath:[\dim {M_h} = N_{\mathrm{cells}}],latexmath:[\dim {X_h} = 2 N^i_{\mathrm{vertices}}] and so
[[eq:chmixte:29]]
\[
\dim {M_h} - \dim {X_h} = N_{\mathrm{cells}} - 2 N^i_{\mathrm{vertices}} = N^\partial_{\mathrm{edges}} - 2 > 0
\]

so latexmath:[M_h] is too rich for the condition and we have latexmath:[\ker(\mathcal{B}) = \{0\}] such that the _only_ discrete latexmath:[u_h^*], with components latexmath:[U^*], satisfying latexmath:[\mathcal{B} U^*] is the null field, latexmath:[U^*=0].

[[finite-element-polyq_1polyp_0-spurious-mode]]
==== Finite element latexmath:[\poly{Q}_1/\poly{P}_0]: spurious mode

We can construct in that case a function latexmath:[q_h^*] on a uniform grid which is equal alternatively -1, +1 (chessboard) in the cells of the mesh, then
[[eq:chmixte:27]]
\[
\forall v_h \in [Q^1_{c,h}]^d, \quad \int_\Omega q^*_h \nabla \cdot v_h = 0
\]
and thus the associated latexmath:[X_h], latexmath:[M_h] do not satisfy the condition.

[[finite-element-polyp_1polyp_1-spurious-mode]]
==== Finite element latexmath:[\poly{P}_1/\poly{P}_1]: spurious mode

We can construct in that case a function latexmath:[q_h^*] on a uniform grid which is equal alternatively -1, 0, +1 at the vertices of the mesh, then
[[eq:chmixte:27]]
\[
\forall v_h \in [P^1_{c,h}]^d, \quad \int_\Omega q^*_h \nabla \cdot v_h = 0
\]
and thus the associated latexmath:[X_h], latexmath:[M_h] do not satisfy the condition.

[[sec:finite-elem-stok]]
=== Mini-Element

The problem with the latexmath:[\poly{P}_1/\poly{P}_1] mixed finite element is that the velocity is not _rich_ enough.

A cure is to add a function latexmath:[v_h^*] in the velocity approximation space to ensure that
[[eq:chmixte:30]]
\[
\int_\Omega q^*_h \nabla \cdot v_h^* \neq 0
\]
where latexmath:[q_h^*] is the spurious mode.

To do that we add the bubble function to the latexmath:[\poly{P}_1] velocity space.

[env.definition#def:chmixte:3]
--
Recall the construction of finite elements on a reference convex latexmath:[\hat{K}].
We say that latexmath:[\hat{b}: \hat{K} \mapsto \RR] is a bubble function if:

* latexmath:[\hat{b} \in H^1_0(\hat{K})]
* latexmath:[0 \leq \hat{b}(\hat{x}) \leq 1, \quad \forall \hat{x} \in \hat{K}]
* latexmath:[\hat{b}(\hat{C}) = 1, \quad \mbox{where} \hat{C}] is the
barycenter of latexmath:[\hat{K}]
--

Example::
The function
[[eq:chmixte:31]]
\[
\hat{b} = (d+1)^{d+1} \Pi_{i=0}^d\ \hat{\lambda}_i
\]
where latexmath:[(\hat{\lambda}_0, \ldots, \hat{\lambda}_d)] denote the barycentric coordinates on latexmath:[\hat{K}]

Denote now latexmath:[\hat{b}] a bubble fonction on latexmath:[\hat{K}], we set
[[eq:chmixte:32]]
\[
\hat{P} = [\poly{P}_1(\hat{K}) \oplus \mathrm{span} (\hat{b})]^d,
\]
and introduce

[env.aligned#eq:chmixte:33]
--
    X_h &=& \Big\{ v_h \in [C^0(\bar{\Omega})]^d : \forall K \in \mathcal{T}_h, v_h
    \circ T_K \in \hat{P}; v_{h_|{\partial \Omega}} = 0 \Big\}\\
    M_h &=& P^1_{c,h}
--

[env.lemma#lem:3]
--
The spaces latexmath:[X_h] and latexmath:[M_h \cap L^2_0(\Omega)] satisfy the compatibility condition  uniformly in latexmath:[h].
--

[env.theorem#thr:chmixte:3]
--
Suppose that latexmath:[(u,p)], solution of <<prob:chmixte:1>>, is smooth enough, ie. latexmath:[u \in [H^2(\Omega)]^d \cap [H^1_0(\Omega)]^d] and latexmath:[p\in H^1(\Omega)     \cap L^2_0(\Omega)].

Then there exists a constant latexmath:[c] such that for all latexmath:[h >0]
[[eq:chmixte:34]]
\[
\| u- u_h \|_{1,\Omega} + \|p-p_h\|_{0,\Omega} \leq c h (\|u\|_{2,\Omega} + \|p\|_{1,\Omega})
\]
and if the Stokes problem is stabilizing then
[[eq:chmixte:35]]
\[
  \|u-u_h\|_{0,\Omega} \leq c h^2 ( \|u\|_{2,\Omega} +\|p\|_{1,\Omega}).
\]
--

[env.definition#def:chmixte:4]
.Stabilizing Stokes problem
--
We say that the Stokes problem is stabilizing if there exists a constant latexmath:[c_S] such that for all latexmath:[f \in [L^2(\Omega)]^d], the unique solution latexmath:[(u,p)] of with latexmath:[g=0] is such that:
[[eq:chmixte:36]]
\[
\|u\|_{2,\Omega} + \|p\|_{1,\Omega} \leq c_S \|f\|_{0,\Omega}
\]
A sufficient condition for stabilizing Stokes problem is that the latexmath:[\Omega] is a polygonal convex in 2D or of class latexmath:[C^1] in latexmath:[\RR^d, d=2,3].
--

[[sec:taylor-hood-element]]
=== Taylor-Hood Element


The mini-element solved the compatibility condition problem, but the error estimation in equation is not optimal in the sense that

1.  the pressure space is sufficiently rich to enable a latexmath:[h^2] convergence in the pressure error,
2.  but the velocity space is not rich enough to ensure a latexmath:[h^2] convergence in the velocity error.

The idea of the Taylor-Hood element is to enrich even more the velocity space to ensure optimal convergence in latexmath:[h].

Here we will take latexmath:[[\poly{P}_2]^d] for the velocity and latexmath:[\poly{P}_1] for the pressure.

Introduce
\[\begin{aligned}
    \label{eq:chmixte:39}
    X_h &=&  [P^2_{c,h}]^d\\
    M_h &=& P^1_{c,h}
    \end{aligned}
\]

[env.lemma#lem:3]
--
The spaces latexmath:[X_h] and latexmath:[M_h \cap L^2_0(\Omega)] satisfy the compatibility condition  uniformly in latexmath:[h].
--

[env.theorem#thr:chmixte:3]
--
Suppose that latexmath:[(u,p)], solution of problem <<prob:chmixte:1>>, is smooth enough, ie. latexmath:[u \in [H^3(\Omega)]^d \cap [H^1_0(\Omega)]^d] and latexmath:[p\in H^2(\Omega)     \cap L^2_0(\Omega)].

Then there exists a constant latexmath:[c] such that for all latexmath:[h >0]

[[eq:chmixte:40]]
\[
  \| u- u_h \|_{1,\Omega} + \|p-p_h\|_{0,\Omega} \leq c h^2 (\|u\|_{3,\Omega} + \|p\|_{2,\Omega})
\]
and if the Stokes problem is stabilizing then
[[eq:chmixte:41]]
\[
  \|u-u_h\|_{0,\Omega} \leq c h^3 ( \|u\|_{3,\Omega} +\|p\|_{2,\Omega}).
\]
--

Generalized Taylor-Hood element:: We consider the mixed finite elements latexmath:[\poly{P}_k/\poly{P}_{k-1}] and latexmath:[\poly{Q}_k/\poly{Q}_{k-1}] which allows to approximate the velocity and pressure respectively with, on Simplices
\[\begin{aligned}
        \label{eq:chmixte:42}
        X_h &=&  [P^{k}_{c,h}]^d\\
        M_h &=& P^{k-1}_{c,h}
      \end{aligned}\]] On Hypercubes latexmath:[\[\begin{aligned}
        \label{eq:chmixte:43}
        X_h &=&  [Q^{k}_{c,h}]^d\\
        M_h &=& Q^{k-1}_{c,h}
        \end{aligned}
\]
We then have
[[eq:chmixte:40]]
\[
\|u-u_h\|_{0,\Omega} + h ( \| u- u_h \|_{1,\Omega} + \|p-p_h\|_{0,\Omega} ) \leq c h^{k+1} (\|u\|_{k+1,\Omega} +\|p\|_{k,\Omega})
\]

There are other stable discretization spaces

* Discrete inf-sup condition: dictates the choice of spaces
* Inf-sup stables spaces:
** latexmath:[\mathbb Q_k]-latexmath:[\mathbb Q_{k-2}],
latexmath:[\mathbb Q_k]-latexmath:[\mathbb Q^{disc}_{k-2}]
** latexmath:[\mathbb P_k]-latexmath:[\mathbb P_{k-1}],
latexmath:[\mathbb P_k]-latexmath:[\mathbb P_{k-2}],
latexmath:[\mathbb P_k]-latexmath:[\mathbb P^{disc}_{k-2}]
** Discrete inf-sup constant independent of latexmath:[h], but
dependent on latexmath:[k]

[[numerical-validation-test-case]]
==== Numerical validation: Test case

We consider the Kovasznay solution of the steady Stokes equations.

The exact solution reads as follows
[[eq:kovaznay]]
[stem]
++++
\begin{array}{r c l}
  \mathbf{u}(x,y) & = &  \left(1 - e^{\lambda x } \cos (2 \pi y), \frac{\lambda}{2 \pi} e^{\lambda x } \sin (2 \pi y)\right)^T \\
  p(x,y) & = &  -\frac{e^{2 \lambda x}}{2} \\
  \lambda & = &  \frac{1}{2 \nu} - \sqrt{\frac{1}{4\nu^2} + 4\pi^2}.
 \end{array}
++++

The domain is defined as stem:[\domain = (-0.5,1) \times (-0.5,1.5)] and stem:[\nu = 0.035].

The forcing term for the momentum equation is obtained from the solution and is
[stem]
++++
 \mathbf{f} = \left( e^{\lambda x}  \left( \left( \lambda^2 - 4\pi^2 \right) \nu \cos (2\pi y) - \lambda e^{\lambda x} \right), e^{\lambda x} \nu \sin (2 \pi y) (-\lambda^2 + 4 \pi^2)           \right)^T
++++

Dirichlet boundary conditions are derived from the exact solution.
