= HDG methods for diffusion-reaction

Most of the material presented in this section can be found in <<<cockburn2009,Cockburn 2009>>>.

We provide a first characterization of HDG methods for the following second-order elliptic model problem:

[stem]
++++
\begin{align*}
\Lambda\mathbf{u} + \nabla p &= \mathbf 0 & &\text{in }\Omega & &(1)\\
\nabla\cdot\mathbf u + d p &= f & &\text{in }\Omega & &(2)\\
p &= h_D & &\text{on }\Gamma_D & &(3)\\
\mathbf u\cdot\mathbf n &= h_N & &\text{on }\Gamma_N & &(4)
\end{align*}
++++

Here stem:[\Omega\subset\mathbb R^n] is a polyhedral domain stem:[(n\geq 2)], stem:[\partial\Omega = \Gamma = \Gamma_D \cup \Gamma_N], stem:[d(\mathbf x)] is a scalar nonnegative function, stem:[\Lambda(\mathbf x)] is a matrix valued function that is symmetric and uniformly positive definite on stem:[\Omega], and stem:[f\in L^2(\Omega)]. If stem:[d = 0], we get the Darcy model presented in <<darcy-model>>. These assumptions can be generalized but we take them to simplify the discussion.

The Darcy problem presented in <<stabilized-formulations>> fits into this framework. Here, rather than using stabilized Galerkin formulations, the idea is to insert a Lagrange multiplier to handle the continuity of the normal components of the approximated flux stem:[\mathbf{u}_h]. In other words, the requirement stem:[\mathbf{u}_h\in H(\text{div},\Omega)] will be written in weak form initially, and then recovered in strong form later.
The introduction of a Lagrange multipliers leads to a formulation with three fields <<<boffi2013,Boffi 2013>>>. We will show how the interior fields can be eliminated in order to build a discrete system that has lost the saddle point structure and only contains degrees of freedom on the faces.

== The general structure of the methods

=== Notation

Let stem:[\Omega_h] be a collection of disjoint elements that partition stem:[\Omega]. The shape of the elements is not important in this general framework. Moreover, stem:[\Omega_h] needs not to be conforming. An interior ''face'' of stem:[\Omega_h] is any set stem:[F] of positive stem:[(n-1)]-Lebesgue measure of the form stem:[F = \partial K^\+\cap\partial K^-] for some two elements stem:[K^+] and stem:[K^-] of stem:[\Omega_h]. We say that stem:[F] is a boundary face if there is an element stem:[K\in\Omega_h] such that stem:[F = \partial K\cap\Gamma] and the stem:[(n-1)]-Lebesgue measure of stem:[F] is not zero. Let stem:[\mathcal E^o_h] and stem:[\mathcal E^\partial_h] denote the set of interior and boundary faces of stem:[\Omega_h], respectively. We denote by stem:[\mathcal E_h] the union of all the faces in stem:[\mathcal E^o_h] and stem:[\mathcal E^\partial_h].

The global finite element spaces for the approximated flux stem:[\mathbf u_h] and scalar solutions stem:[p_h] are

[stem]
++++
\begin{align*}
\mathbf V_h &= \left\{\mathbf v : \Omega\to\mathbb R^n : \mathbf v|_K \in\mathbf V(K)\quad\forall\,K\in\Omega_h\right\},\\
W_h &= \left\{w : \Omega\to\mathbb R : w|_K \in W(K)\quad\forall\,K\in\Omega_h\right\}.
\end{align*}
++++

We also need to introduce the spaces
[stem]
++++
\begin{align*}
M_h &= \{\mu : \mathcal E_h\to \mathbb R : \mu|_F\in M(F)\quad\forall\,F\in\mathcal E_h \},\\
M_h^o &= \{\mu\in M_h : \mu|_\Gamma = 0 \},\\
M_h^D &= \{\mu\in M_h : \mu|_F = 0\quad\forall\,F\in\mathcal E_h\setminus\Gamma_D \},\\
M_h^N &= \{\mu\in M_h : \mu|_F = 0\quad\forall\,F\in\mathcal E_h\setminus\Gamma_N \}.
\end{align*}
++++

*Different choices of the local spaces stem:[\mathbf V(K), W(K)], and stem:[M(F)] correspond to different hybrid methods.*

For any discontinuous (scalar or vector) function stem:[u] in stem:[W_h] or stem:[\mathbf V_h], the trace stem:[u|_F] on an interior face stem:[F = \partial K^\+\cap\partial K^-] is a double value function, whose two branches are denoted by stem:[u|_{K^+}] and stem:[u|_{K^-}]. Here, stem:[\mathbf n_K] denotes the unit outward normal of stem:[K]. For any double-valued vector function stem:[\mathbf v], we define the _jump_ of its normal component across an interior face stem:[F] by

[stem]
++++
[[ \mathbf v ]]_F = \mathbf v_{K^+} \cdot\mathbf n_{K^+} + \mathbf v_{K^-}\cdot\mathbf n_{K^-}.
++++
On any face stem:[F] of stem:[K] lying on the boundary, we set
[stem]
++++
[[ \mathbf v ]]_F = \mathbf v_K \cdot\mathbf n_K.
++++
A similar notation will be used for scalar functions. For functions stem:[u] and stem:[v] in stem:[L^2(D)], we write stem:[(u, v)_D = \int_D uv] if stem:[D] is a domain of stem:[\mathbb R^n], and stem:[\langle u, v\rangle_D = \int_Duv] if stem:[D] is a domain of stem:[\mathbf R^{n-1}]. Also, we will use the notation
[stem]
++++
(v, w)_{\Omega_h} = \sum_{K\in\Omega_h}(v, w)_K,\qquad\langle\mu,\lambda\rangle_{\partial\Omega_h} = \sum_{K\in\Omega_h}\langle\mu,\lambda\rangle_{\partial K}.
++++


=== Reaching the formulation
==== A characterization of the exact solution
Two functions stem:[\mathbf u, p] are exact solutions of stem:[(1)-(4)] if and only if they satisfy the _local_ problems
[stem]
++++
\begin{align*}
\Lambda\mathbf u + \nabla p &= \mathbf 0 & &\text{in }K,\\
\nabla\cdot\mathbf u + d p &= f & &\text{in K},
\end{align*}
++++
the _transmission_ conditions
[stem]
++++
\begin{align*}
[[ \hat p ]] &= 0 & &\text{if }F\in\mathcal E^o_h,\\
[[ \hat{\mathbf u}]] &= 0 & &\text{if }F\in\mathcal E^o_h,
\end{align*}
++++
and the boundary conditions
[stem]
++++
\begin{align}
\hat p &= h_D & &\text{if }F\in\Gamma_D,\\
\hat{\mathbf u}\cdot\mathbf n &= h_N & &\text{if }F\in\Gamma_N,
\end{align}
++++
where stem:[\hat p] and stem:[\hat{\mathbf u}] are the traces of stem:[p] and stem:[\mathbf u], respectively. The transmission conditions state that the normal component of stem:[\hat{\mathbf u}] across interelement boundary must be continuous. We can obtain stem:[(\mathbf u, p)] in stem:[K] in terms of stem:[\hat p] on stem:[\partial K] and stem:[f] by solving the following _local_ Dirichlet problem
[stem]
++++
\begin{align*}
\Lambda\mathbf u + \nabla p &= \mathbf 0 & &\text{in }K, & &(5)\\
\nabla\cdot\mathbf u + d p &= f & &\text{in K}, & &(6)\\
p &= \hat p & &\text{on }\partial K. & &(7)
\end{align*}
++++
The function stem:[\hat p] can now be determined as the solution, on each stem:[F\in\mathcal E_h], of the _global_ equations
$$
\begin{align*}
[[ \hat{\mathbf u} ]]_F &= 0 & &\text{if }F\in\mathcal E^o_h, & &(8)\\
[[ \hat{\mathbf u} ]]_F &= h_N & &\text{if }F\in\Gamma_N, & & (9)\\
\hat p|_F &= h_D & &\text{if }F\in\Gamma_D. & &(10)
\end{align*}
$$

Hybrid methods are obtained by constructing *discrete* versions of stem:[(5)-(10)]. In this way, the *globally coupled* degrees of freedom will be those of the corresponding global formulations.


==== The local solvers: a weak formulation on each element
From stem:[(5)-(7)], on the element stem:[K\in\Omega_h], we define stem:[(\mathbf u_h, p_h)] in terms of stem:[(\hat p_h, f)] as the element of stem:[\mathbf V(K)\times W(K)] such that
[stem]
++++
\begin{align*}
(\Lambda\mathbf u_h,\mathbf v)_K - (p_h, \nabla\cdot\mathbf v)_K + \langle\hat p_h, \mathbf v\cdot\mathbf n\rangle_{\partial K} &= 0, & &(11)\\
-(\mathbf u_h, \nabla w)_K + \langle\hat{\mathbf u}_h\cdot\mathbf n,w\rangle_{\partial K} + (dp_h, w)_K &= (f,w)_K, & &(12)
\end{align*}
++++
for all stem:[(\mathbf v, w) \in \mathbf V(K)\times W(K)], where stem:[\hat{\mathbf u}_h] is the numerical trace of the flux and depends, in general, on stem:[\mathbf u_h, p_h], and stem:[\hat p_h]. Different methods will correspond to different choices of stem:[\hat{\mathbf u}_h].

==== The global problem
From stem:[(8)-(10)], We determine stem:[\hat p_h\in M_h] by requiring that
[stem]
++++
\begin{align*}
\langle\mu,[[ \hat{\mathbf u}_h ]]\rangle_F &= 0 & &\forall\,\mu\in M(F) & &\text{if }F\in\mathcal E_h^o, & &(13)\\
\langle\mu,[[ \hat{\mathbf u}_h ]]\rangle_F &= \langle\mu,h_N\rangle_F & &\forall\,\mu\in M(F) & &\text{if }F\in\Gamma_N, & &(14)\\
\langle\mu,\hat p_h\rangle_F &= \langle\mu,h_D\rangle_F & &\forall\,\mu\in M(F) & &\text{if }F\in\Gamma_D. & &(15)
\end{align*}
++++
By solving stem:[(11), (12)] for stem:[(\mathbf u_h, p_h)] in terms of stem:[(\hat p_h, f)] at each element and plugging the results into stem:[(13)-(15)], we get a system whose globally coupled degrees of freedom are those of the numerical trace stem:[\hat p_h]. This procedure corresponds to performing *static condensation* on the full discrete global system written in terms of stem:[\mathbf u_h, p_h, \hat p_h].

If the (extension by zero to stem:[\mathcal E_h] of the) function stem:[[[ \hat{\mathbf u}_h \]\]_{|\mathcal E_h^o}] belongs to the space stem:[M_h], then condition stem:[(13)] is stating that stem:[[[ \hat{\mathbf u}_h \]\]_{|\mathcal E_h^o} = 0] pointwise, that is, the normal component of the numerical trace stem:[\hat{\mathbf u}_h] is single valued. This means that the function stem:[\hat{\mathbf u}_h] is a *conservative* numerical flux (stem:[\hat{\mathbf u}_h\in H(\text{div},\Omega)]).

==== Summary
The approximate solution stem:[(\mathbf u_h, p_h, \hat p_h)] is the element of the space stem:[\mathbf V_h\times W_h\times M_h] satisfying the equations
[stem]
++++
\begin{align*}
(\Lambda\mathbf u_h,\mathbf v)_{\Omega_h} - (p_h, \nabla\cdot\mathbf v)_{\Omega_h} + \langle\hat p_h, \mathbf v\cdot\mathbf n\rangle_{\partial\Omega_h} &= 0 & &\forall\mathbf v\in \mathbf V_h, & &(16)\\
-(\mathbf u_h, \nabla w)_{\Omega_h} + \langle\hat{\mathbf u}_h\cdot\mathbf n,w\rangle_{\partial\Omega_h}  + (d p_h, w)_{\Omega_h} &= (f,w)_{\Omega_h} & &\forall w\in W_h, & &(17)\\
\langle\mu,\hat{\mathbf u}_h\cdot\mathbf n\rangle_{\partial\Omega_h\setminus\Gamma} &= 0 & &\forall \mu\in M^o_h, & &(18)\\
\langle\mu,\hat{\mathbf u}_h\cdot\mathbf n\rangle_{\Gamma_N} &= \langle\mu,h_N\rangle_{\Gamma_N} & &\forall\mu\in M^N_h, & &(19)\\
\langle\mu,\hat p_h\rangle_{\Gamma_D} &= \langle\mu,h_D\rangle_{\Gamma_D} & &\forall\mu\in M^D_h, & &(20)
\end{align*}
++++
where the local spaces stem:[\mathbf V(K), W(K), M(F)], as well as the numerical trace stem:[\hat{\mathbf q}_h], need to be specified.




== Examples of hybridizable methods
In this section we give som examples of methods fitting the general structure described in the previous section. The first three methods use the *same* local solver in all the elements stem:[K] of the mesh stem:[\Omega_h] and assume that stem:[\Omega_h] is a *conforming simplicial mesh*. The fourth example is a class of methods employing *different* local solvers in different parts of the domain, which can easily deal with *nonconforming* meshes. To define each method, we have only to specify:

- the numerical trace of the flux stem:[\hat{\mathbf u}_h];
- the local spaces stem:[\mathbf V(K), W(K)];
- the space of approximate traces stem:[M_h].


=== The RT-H method
This method is obtained by using the Raviart-Thomas method to define the local solvers. The three ingredients of the RT-H method are:

. stem:[\hat{\mathbf u}_h = \mathbf u_h] on stem:[\partial K], for each stem:[K\in\Omega_h].
. stem:[\mathbf V(K) = [P_k(K)\]^n + \mathbf x P_k(K),\quad W(K) = P_k(K),\quad k\geq 0].
. stem:[M_h = \{\mu\in L^2(\mathcal E_h) : \mu|_F\in P_k(F)\quad\forall\,F\in\mathcal E_h\}].

The accuracy of the RT-H method is summarized in section <<accuracy>>. Note that, because stem:[[[ \hat{\mathbf u}_h \]\]] and test functions stem:[\mu] belong to the same space <<<sayas-voyage,Sayas 2013>>>, conservativity condition stem:[(13)] forces
[stem]
++++
[[ \hat{\mathbf u}_h]] = 0\quad\text{on }\mathcal E_h^o,
++++
so the normal component of the numerical trace stem:[\hat{\mathbf u}_h] is single-valued, and stem:[\mathbf u_h\in H(\text{div},\Omega)].


=== The BDM-H method
This method is obtained by using the Brezzi-Douglas-Marini method to define the local solvers. The three ingredients of the BDM-H method are:

. stem:[\hat{\mathbf u}_h = \mathbf u_h] on stem:[\partial K], for each stem:[K\in\Omega_h].
. stem:[\mathbf V(K) = [P_k(K)\]^n,\quad W(K) = P_{k-1}(K),\quad k\geq 1].
. Same stem:[M_h] of the RT-H method.

Everything said about the RT-H method in the previous subsection applies to the BDM-H method.


=== The HDG method
The spaces of RT-H and BDM-H can be balanced to have equal polynomial degree. Stability is restored using a discrete stabilization (not penalization) function. The resulting method is known as the Hybridizable Discontinuous Galerkin (HDG) method. The HDG method is obtained by using the local DG method to define the local solvers. The three ingredients of the HDG method are:

. For each stem:[K\in\Omega_h]: stem:[\hat{\mathbf u}_h = \mathbf u_h + \tau_K(p_h - \hat p_h)\mathbf n\quad\text{on }\partial K,] +
where stem:[\tau_K] is a *nonnegative* function that can vary on stem:[\partial K], and stem:[\tau_K > 0] on at least one face of stem:[\partial K].
. stem:[\mathbf V(K) = [P_k(K)\]^n,\quad W(K) = P_k(K),\quad k\geq 0].
. Same stem:[M_h] of the RT-H method.

The function stem:[\tau] can be double valued on stem:[\mathcal E_h^o], with two branches stem:[\tau^-=\tau_{K^-}] and stem:[\tau^\+=\tau_{K^+}] defined on the face stem:[F] shared by the finite elements stem:[K^+] and stem:[K^-]. Note that the numerical trace of the flux stem:[\hat{\mathbf u}_h] (but not the flux itself, as stem:[\tau_K\ne 0]) is conservative. The accuracy of the HDG method is summarized in section <<accuracy>>.

==== Enhanced accuracy by postprocessing
The approximate solution and flux of the HDG method can be *locally* postprocessed to enhance their accuracy <<<cockburnGS2010,Cockburn 2010>>>.

- *Postprocessing of the scalar variable*: +
if we look for stem:[p_h^*:\Omega\to\mathbb R] such that stem:[p_h^*|_K\in P_{k+1}(K)] and for all stem:[K\in\Omega_h]
[stem]
++++
\begin{align}
(\nabla p_h^*, \nabla w)_K &= -(\Lambda\mathbf u_h, \nabla w)_K & &\forall\,w\in P_{k+1}(K),\\
(p^*_h, 1)_K &= (p_h, 1)_K, & &
\end{align}
++++
then it can be shown that this local postprocessed approximation has one additional order of convergence.

- *Postprocessing of the flux*: +
we can obtain a postprocessed flux stem:[\mathbf u_h^*] with better conservation properties. Although stem:[\mathbf u_h^*] converges at the same order as stem:[\mathbf u_h], it is in stem:[H(\text{div},\Omega)] and its divergence converges at one higher order than stem:[\mathbf u_h]. On each stem:[K\in\Omega_h], we take stem:[\mathbf u_h^* :=\mathbf u_h + \boldsymbol\eta_h] where stem:[\boldsymbol\eta_h] is the only element of stem:[[P_k(K)\]^n + \mathbf x P_k(K)] satisfying
[stem]
++++
\begin{align}
(\boldsymbol\eta_h,\mathbf v)_K &= 0 & &\forall\,\mathbf v\in[P_{k-1}(K)]^n,\\
\langle\boldsymbol\eta_h\cdot\mathbf n, \mu\rangle_F &= \langle(\hat{\mathbf u}_h-\mathbf u_h)\cdot\mathbf n,\mu\rangle_F & &\forall\,F\in P_k(F),\quad\forall\,F\in\partial K.
\end{align}
++++


=== Hybridization in matrix form
This section is mainly based on <<<sayas-matlab,Fu 2013>>>. As stated before, the goal of hybridization is the reduction (or static condensation) of the system stem:[(16)-(20)] to a linear system where only stem:[\hat p_h] shows up. The remaining two variables stem:[\mathbf u_h] and stem:[p_h] will be reconstructed after solving for stem:[\hat p_h], in an element-by-element fashion, easy to realize due to the fact that equations stem:[(16)] and stem:[(17)] are local or, in other words, the spaces stem:[\mathbf V_h] and stem:[W_h] are completely *discontinous*. In this section we will show how to perform static condensation on the linear system obtained by using the HDG method. This procedure can be easily adapted to other hybrid methods. Let us recall that the HDG method looks for an approximate solution stem:[(\mathbf u_h, p_h, \hat p_h)] in the space stem:[\mathbf V_h\times W_h\times M_h] satisfying the equations
[stem]
++++
\begin{align*}
&(\Lambda\mathbf u_h,\mathbf v)_{\Omega_h} & &- (p_h, \nabla\cdot\mathbf v)_{\Omega_h} & &+ \langle\hat p_h, \mathbf v\cdot\mathbf n\rangle_{\partial\Omega_h} & &= 0, & &(21)\\
&(\nabla\cdot\mathbf u_h, w)_{\Omega_h} & &+ \langle\tau p_h,w\rangle_{\partial\Omega_h}  + (d p_h, w)_{\Omega_h} & &- \langle\tau \hat p_h,w\rangle_{\partial\Omega_h} & &= (f,w)_{\Omega_h}, & &(22)\\
&\langle\mathbf u_h\cdot\mathbf n,\mu_1\rangle_{\partial\Omega_h\setminus\Gamma} & &+ \langle\tau p_h,\mu_1\rangle_{\partial\Omega_h\setminus\Gamma} & &- \langle\tau \hat p_h,\mu_1\rangle_{\partial\Omega_h\setminus\Gamma} & &= 0, & &(23)\\
&\langle\mathbf u_h\cdot\mathbf n,\mu_2\rangle_{\Gamma_N} & &+ \langle\tau p_h,\mu_2\rangle_{\Gamma_N} & &- \langle\tau \hat p_h,\mu_2\rangle_{\Gamma_N} & &= \langle h_N,\mu_2\rangle_{\Gamma_N}, & &(24)\\
& & & & &\langle\hat p_h,\mu_3\rangle_{\Gamma_D} & &= \langle h_D,\mu_3\rangle_{\Gamma_D}, & &(25)
\end{align*}
++++
for all stem:[(\mathbf v, w, \mu_1, \mu_2, \mu_3)\in\mathbf V_h\times W_h\times M_h^o\times M_h^N\times M_h^D].

==== Local solvers
Introduce the matrices related to the local bilinear forms
[stem]
++++
\begin{align}
A_{11}^K &\leftrightarrow (\Lambda\mathbf u_h,\mathbf v)_K, & &A_{12}^K\leftrightarrow- (p_h, \nabla\cdot\mathbf v)_K, & &A_{13}^K\leftrightarrow\langle\hat p_h, \mathbf v\cdot\mathbf n\rangle_{\partial K},\\
A_{21}^K &\leftrightarrow(\nabla\cdot\mathbf u_h, w)_K, & &A_{22}^K\leftrightarrow\langle\tau p_h,w\rangle_{\partial K}  + (d p_h, w)_K, & &A_{23}^K\leftrightarrow\langle\tau \hat p_h,w\rangle_{\partial K},\\
A_{31}^K &\leftrightarrow\langle\mathbf u_h\cdot\mathbf n, \mu\rangle_{\partial K}, & &A_{32}^K\leftrightarrow\langle\tau p_h,\mu\rangle_{\partial K}, & &A_{33}^K\leftrightarrow\langle\tau \hat p_h,\mu\rangle_{\partial K},\\
& & &A_f^K\leftrightarrow (f,w)_K
\end{align}
++++
If stem:[\hat p_h\in M_h] is known, equations stem:[(21), (22)] are uniquely solvable for stem:[\mathbf u_h, p_h]and can be solved element-by-element. Let us represent stem:[\mathbf u_h|_K, p_h|_K], and stem:[\hat p_h|_{\partial K}] with vectors stem:[\mathbf u_K, \mathbf p_K], and stem:[\mathbf p_{\partial K}], respectively. Also, let
[stem]
++++
\begin{align*}
A^K &=
\begin{bmatrix}
A_{11}^K & A_{12}^K\\
A_{21}^K & A_{22}^K\\
\end{bmatrix}, & B^K &=
\begin{bmatrix}
A_{13}^K\\
A_{23}^K
\end{bmatrix}, & F^K &=
\begin{bmatrix}
\mathbf 0\\
A_f^K
\end{bmatrix}.
\end{align*}
++++

Then, the *matrix representation of the local solutions* is
[stem]
++++
\begin{align}
&\begin{bmatrix}
\mathbf u_K\\
\mathbf p_K
\end{bmatrix} =
-(A^K)^{-1}B^K
\mathbf p_{\partial K} + (A^K)^{-1}F^K. & &(26)
\end{align}
++++
Let us define
[stem]
++++
C^K = \begin{bmatrix}
A_{31}^K & A_{32}^K
\end{bmatrix}.
++++

The flux prescribed by the HDG method
[stem]
++++
\mathbf u_h\cdot\mathbf n + \tau(p_h-\hat p_h)\colon\partial K\to\mathbb R
++++
creates a bilinear form
[stem]
++++
\mu\in M(\partial K)\to\langle\mathbf u_h\cdot\mathbf n + \tau (p_h-\hat p_h), \mu\rangle_{\partial K} = \langle\mathbf u_h\cdot\mathbf n + \tau p_h, \mu\rangle_{\partial K} - \langle \tau\hat p_h, \mu\rangle
++++
whose matrix representation is (using stem:[(26)])
[stem]
++++
\begin{split}
C^K\begin{bmatrix}
\mathbf u_K\\
\mathbf p_K
\end{bmatrix} - A_{33}^K\mathbf p_{\partial K} &= -C^K(A^K)^{-1}B^K
\mathbf p_{\partial K} + C^K(A^K)^{-1}F^K - A_{33}^K\mathbf p_{\partial K}\qquad(27)\\
&= D_f^K - D^K\mathbf p_{\partial K},
\end{split}
++++
with
[stem]
++++
\begin{align*}
D_f^K &=  C^K(A^K)^{-1}F^K, & D^K &= C^K(A^K)^{-1}B^K + A_{33}^K.
\end{align*}
++++

==== Boundary conditions and global solver
- *Dirichlet boundary conditions*. The discrete Dirichlet boundary conditions stem:[(25)] require finding the projection stem:[\mathbf{\hat p}_D] of the function stem:[h_D] on the space stem:[M_h|_{\Gamma_D}].
- *Neumann boundary conditions*. Neumann boundary conditions will appear in the right hand side of the global system.
- *Assemblying the global solver*. The local solvers produce matrices stem:[D^K] that need to be assembled to get a global matrix stem:[\mathbb H]. This matrix collects the fluxes stem:[(27)] from all the elements, with the result that opposing sign fluxes in internal faces (the normal vector points in different directions) are added. The matrices stem:[D^K_f] also have to be assembled to get a global vector stem:[\mathbf F]. At this point, the global system reads
[stem]
++++
\begin{equation*}
\mathbb H\,\mathbf{\hat p} = \mathbf F + \mathbf G_N,\qquad(28)
\end{equation*}
++++
where stem:[\mathbf G_N] is the vector containing the elements of stem:[\langle h_N, \mu\rangle_{\Gamma_N}, \mu\in M_h|_{\Gamma_N}] in the degrees of freedom corresponding to Neumann faces and zeros everywhere else. What is left is the elimination of Dirichlet degrees of freedom from stem:[(28)], namely, values of Dirichlet faces are taken from stem:[\mathbf{\hat p}_D] and sent to the right hand side of the system, and rows corresponding to Dirichlet degrees of freedom are ignored.

=== Orders of accuracy for RT-H, BDM-H, HDG
[[accuracy]]
The following table summarizes the effect of the local spaces and the stabilization parameter stem:[\tau] on the accuracy of the method on simplexes. We denote by stem:[\overline p_h|_K] the integral average of stem:[p_h] on stem:[K\in\Omega_h]. For the HDG method, the superconvergence of stem:[\overline p_h] is what allows to get a solution of enhanced accuracy by postprocessing.

|===
| Method | stem:[\tau] | stem:[\mathbf u_h] | stem:[p_h] | stem:[\overline p_h] | stem:[k]
| RT-H | stem:[0] | stem:[k+1] | stem:[k+1] | stem:[k+2] | stem:[\geq 0]
| BDM-H | stem:[0] | stem:[k+1] | stem:[k] | stem:[k+2] | stem:[\geq 2]
| HDG | stem:[O(h)] | stem:[k+1] | stem:[k] | stem:[k+2] | stem:[\geq 1]
| HDG | stem:[O(1)] | stem:[k+1] | stem:[k+1] | stem:[k+2] | stem:[\geq 1]
| HDG | stem:[O(1)] | stem:[1] | stem:[1] | stem:[1] | stem:[=0]
| HDG | stem:[O(1/h)] | stem:[k] | stem:[k+1] | stem:[k+1] | stem:[\geq 1]
|===


=== A class of hybridizable methods well suited for adaptivity
We introduce here a class of hybridizable methods able to use different local solvers in different elements and to easily handle nonconforming meshes. To define these methods, we need to specify the numerical fluxes, the local finite element spaces, and the space of approximate traces:

. For any simplex stem:[K\in\Omega_h], we take
[stem]
++++
\begin{equation*}
\hat{\mathbf u}_h = \mathbf u_h + \tau_K(p_h - \hat p_h)\mathbf n\quad\text{on }\partial K,
\end{equation*}
++++
the function stem:[\tau_K] is allowed to change on stem:[\partial K].
. The local space stem:[\mathbf V(K)\times W(K)] can be any of the following:

- stem:[([P_{k(K)}(K)\]^n + \mathbf x P_{k(K)}(K)) \times P_{k(K)}(K)], where stem:[k(K)\geq0] and stem:[\tau_K\geq 0] on stem:[\partial K],
- stem:[[P_{k(K)}(K)\]^n \times P_{k(K)-1}(K)], where stem:[k(K)\geq1] and stem:[\tau_K\geq 0] on stem:[\partial K],
- stem:[[P_{k(K)}(K)\]^n \times P_{k(K)}(K)], where stem:[k(K)\geq0] and stem:[\tau_K > 0] on at least one face stem:[F\in\partial K].
. The space of approximate traces is
[stem]
++++
\begin{equation*}
M_h := \{\mu\in L^2(\mathcal E_h):\mu|_F\in P_{k(F)}\quad\forall\,F\in\mathcal E_h\}.
\end{equation*}
++++

Here, if stem:[F = \partial K^\+\cap\partial K^-], we set stem:[k(F) := \max\{k(K^+), k(K^-)\}]. For each element stem:[K\in\Omega_h] and each face stem:[F\in\mathcal E_h] on stem:[\partial K], we take stem:[\tau_K|_F\in[0,\infty)]
and
[stem]
++++
\tau_K|_F\in(0,\infty)\quad\text{if }F\text{ is not a face of }K.\qquad(16)
++++
Choice stem:[(16)] allows to deal with the nonconformity of the mesh in a very natural way. Also, the choice stem:[\tau_K = \infty] could be allowed provided that the definition of the local solvers is modified as in <<<cockburn2009,Cockburn 2009>>>.

The main features of this class of methods are:

- *Variable degree approximation spaces on conforming meshes*. The RT-H, BDM-H, and HDM methods considered above use a single local solver in each of the elements stem:[K] of the conforming triangulation stem:[\Omega_h]. A variable-degree version of each of these methods is a particular case of the clas of methods presented here.
- *Automatic coupling of different methods on conforming meshes*. The class presented here allows for the use of different local solvers in different elements stem:[K\in\Omega_h], which are then automatically coupled.
- *Mortaring capabilities (for nonconforming meshes)*. This class incorporate a _mortaring_ ability thanks to the form that the numerical trace of the flux on stem:[\partial K] takes on an interior face stem:[F\in\mathcal E_h^o], and thanks to the definition of the stabilization parameter. Let us give an example. If we have a conforming mesh, we can take the first choice of local spaces (2a) and set stem:[\tau = 0]. The resulting method is nothing but the RT-H method. We can easily modify this method to handle nonconforming meshes by simply taking stem:[\tau_K\in(0,\infty)] on every stem:[F\in\mathcal E_h^o] which is not a face of stem:[K], and otherwise, taking stem:[\tau_K 0].

For other possible methods, see <<<cockburn2009,Cockburn 2009>>>.

[[biliography]]
== References

- [[[cockburn2009]]] Superconvergent discontinuous Galerkin methods for second-order elliptic problems
B Cockburn, J Guzmán, H Wang - Mathematics of Computation, 2009
- [[[ cockburnGS2010]]] The hybridizable discontinuous Galerkin methods, B Cockburn - Proceedings of the International Congress of …, 2010
- [[[boffi2013]]] Mixed finite element methods and applications, D Boffi, F Brezzi, M Fortin - 2013
- [[[sayas-matlab]]] Algorithm 949: MATLAB tools for HDG in three dimensions
Z Fu, LF Gatica, FJ Sayas - ACM Transactions on Mathematical Software (TOMS), 2015
- [[[sayas-voyage]]] From Raviart-Thomas to HDG: a personal voyage, FJ Sayas - arXiv preprint arXiv:1307.2491, 2013