[[feelpp_offerings]]
= {feelpp} Offerings in *Marketplace*

Currently the apps available in the *Marketplace* are given in the table below.

== List of Applications

.Available {feelpp} apps
[options="header,footer"]
|===
| Application            | Description        | Documentation    | Case Studies
| {feelpp} Toolbox CSM | Computational Solid Mechanics app | xref:toolboxes:csm:index.adoc[CSM Docs] | xref:cases:csm:README.adoc[CSM Case Studies]
| {feelpp} Toolbox CFD | Computational Solid Mechanics app | xref:toolboxes:cfd:index.adoc[CFD Docs]| xref:cases:cfd:README.adoc[CFD Case Studies]
| {feelpp} Toolbox Heat | Heat Transfer app | xref:toolboxes:heat:index.adoc[Heat Docs] | xref:cases:heat:README.adoc[Heat Case Studies]
| {feelpp} Toolbox Heat&Fluid | Heat Transfer and Fluid dynamics app | xref:toolboxes:heatfluid:index.adoc[Heat & Fluid Docs] | xref:cases:heatfluid:README.adoc[Heat & Fluid Case Studies]
| {feelpp} Toolbox Thermo-Electric | Thermo-Electric app | xref:toolboxes:thermo-electric:index.adoc[Thermo-Electric Docs] | xref:cases:thermo-electric:README.adoc[Thermo-Electric Case Studies]
|===

For details about settings up these apps please refer to these <<offering_setup, docs>>.
For the new user we recommend to read this guide. The impatient may go directly to the <<enduser, *EndUser*>>  and try to run the basic demonstrator.

== Synopsis of the {feelpp} Offering

The {feelpp} offering on the *Marketplace* is created by {feelpp} developers.

Any *EndUser* may purchase the offering following the <<purchase, generic procedure>>.
Then, he or she can run the purchased offering provided that some fields are filled properly as in this <<running, example>>.

Details for setup each offering will be giving in the <<offering_setup, next section>>.

Even if each offering is specific, what is going on under the hood is described here:

* deploy:
* running:
* undeploy:
