[[feelpp_offerings]]
= {feelpp} Offerings in *Marketplace*

Currently the apps available in the *Marketplace* are given in the table bellow.

== List of Offers

.Available {feelpp} apps
[options="header,footer"]
|===
| Offering            | Description        | Category    | Notes
| {feelpp} Offering | Basic demonstrator | Simulations |
|===

For details about settings up these apps please refer to these <<offering_setup, docs>>.
For the new user we recommend to read this guide. The impatient may go directly to the <<enduser, *EndUser*>>  and try to run the basic demonstrator.

== Synopsis of the {feelpp} Offering

The {feelpp} offering on the *Marketplace* is created by {feelpp} developers.

Any *EndUser* may purchase the offering following the <<purchase, generic procedure>>.
Then, he or she can run the purchased offering provided that some fields are filled properly as in this <<running, example>>.

Details for setup each offering will be giving in the <<offering_setup, next section>>.

Even if each offering is specific, what is going on under the hood is described here:

* deploy:
* running:
* undeploy:
