= Containers
:page-permalink: /user-manual/installation/containers
:page-layout: manual
:page-root: ../../
:imagesdir: ../../../images/
:sourcedir: ../../../codes/
include::../../../includes/header.adoc[]

TIP: Difficulty {easy}

For beginners, we recommend to start learning {feelpp} using containers
technologies.
The current containers solutions provided for {feelpp}:

. Docker
. Singularity

Depending on your usage and operating system, you might prefere one of these
previous solutions. The next sub-sections describes how to obtain {feelpp}
images to begin programming.

== Docker

Using {feelpp} inside
<<what-is-docker,Docker>> is the recommended and
fastest way to use {feelpp}. The
<<Docker,Docker chapter>> is dedicated to Docker
and <<feelpp-containers,{feelpp} containers chapter>> is dedicated to {feelpp} in Docker.

We strongly encourage you to follow these steps if you begin with
{feelpp} in particular as an end-user.

People who would like to develop with and in {feelpp} should
read through the remaining sections of this chapter.

== Singularity
