= Maxwell quasi static
:stem: latexmath

The divergence-free magnetic flux density vector can be described by the curl of the magnetic vector potential stem:[\boldsymbol{A},] since stem:[\nabla \cdot \nabla \times \boldsymbol{u} \equiv 0,] for any vector function stem:[\boldsymbol{u}=\boldsymbol{u}(\boldsymbol{r}),] or stem:[\boldsymbol{u}=\boldsymbol{u}(\boldsymbol{r}, t),] i.e.
[stem]
++++
\boldsymbol{B}=\nabla \times \boldsymbol{A} 
++++
This automatically enforces the satisfaction of magnetic Gauss' law. Substituting expression into Faraday's law 
[stem]
++++
\nabla \times \boldsymbol{E}=-\frac{\partial \boldsymbol{B}}{\partial t}, 
++++
results in
[stem]
++++
\nabla \times \boldsymbol{E}=-\frac{\partial}{\partial t} \nabla \times \boldsymbol{A}=-\nabla \times \frac{\partial \boldsymbol{A}}{\partial t} \quad \Rightarrow \quad \nabla \times\left(\boldsymbol{E}+\frac{\partial \boldsymbol{A}}{\partial t}\right)=\mathbf{0}
++++
because rotation (i.e. derivation by space) and derivation by time can be replaced. 
The curl-less vector field stem:[\boldsymbol{E}+\partial \boldsymbol{A} / \partial t] can be derived from the so-called electric scalar potential
stem:[V(\nabla \times \nabla \varphi \equiv 0, \text { for any scalar functions } \varphi=\varphi(\boldsymbol{r}), \text { or } \varphi=\varphi(\boldsymbol{r}, t))]
 
and the electric field intensity vector can be described by two potentials as
[stem]
++++
E=-\frac{\partial A}{\partial t}-\nabla V
++++
Substituting the relations (2.283) and (2.286) into 
[stem]
++++
\nabla \times \boldsymbol{H}=\boldsymbol{J}
++++
and using the linearized constitutive relation in 
[stem]
++++
\boldsymbol{H}=\left\{\begin{array}{ll}\nu_{0} \nu_{r} \boldsymbol{B}, & \text { in magnetically linear material, } \Omega_{c} \\ \mathscr{B}^{-1}\{\boldsymbol{B}\}=\nu_{o} \boldsymbol{B}+\boldsymbol{I}, & \text { in magnetically nonlinear medium, } \Omega_{c}\end{array}\right.
++++
leads to the partial differential equation
[stem]
++++
\nabla \times\left(\nu_{o} \nabla \times \boldsymbol{A}\right)+\sigma \frac{\partial \boldsymbol{A}}{\partial t}+\sigma \nabla V=-\nabla \times \boldsymbol{I}, \quad \text { in } \quad \Omega_{c}
++++
The charge conservation law 
[stem]
++++
\nabla \cdot \boldsymbol{J}=0
++++
with the constitutive relation 
[stem]
++++
\boldsymbol{J}=\sigma \boldsymbol{E}
++++
and with the formulation results in the second partial differential equation of this formulation,
[stem]
++++
-\nabla \cdot\left(\sigma \frac{\partial \boldsymbol{A}}{\partial t}+\sigma \nabla V\right)=0, \quad \text { in } \quad \Omega_{c}
++++
There are two unknown functions ( stem:[\boldsymbol{A}] and stem:[V] ), that is why two equations must be formulated, however, the second one is coming from taking the divergence of Ampere's 

[stem]
++++
\nabla \times \boldsymbol{H}=\boldsymbol{J}, \quad$ in stem:[\quad \Omega_{c}
++++



== Boundary conditions

We now turn to the  definition of the boundary conditions of the problem. 

=== On stem:[\Gamma_{H_{c}}]

The tangential component of the magnetic field intensity vector must vanish,
[stem]
++++
\boldsymbol{H} \times \boldsymbol{n}=\mathbf{0} \quad \Rightarrow \quad\left(\nu_{o} \nabla \times \boldsymbol{A}+\boldsymbol{I}\right) \times \boldsymbol{n}=\mathbf{0}, \quad \text { on } \quad \Gamma_{H_{c}}
++++
This is a Neumann boundary condition for stem:[\boldsymbol{A}]. The normal component of eddy currents must be equal to zero on stem:[\Gamma_{H_{c}},] which can be formulated by the Neumann boundary condition
[stem]
++++
\boldsymbol{J} \cdot \boldsymbol{n} \quad \Rightarrow \quad-\sigma \frac{\partial \boldsymbol{A}}{\partial t} \cdot \boldsymbol{n}-\sigma \nabla V \cdot \boldsymbol{n}=0, \quad \text { on } \quad \Gamma_{H_{c}}
++++

=== On the rest part of the boundary stem:[\Gamma_{E},]

The tangential component of the electric field intensity must be equal to zero, stem:[\boldsymbol{E} \times \boldsymbol{n}=\mathbf{0} \quad \Rightarrow \quad\left(-\frac{\partial \boldsymbol{A}}{\partial t}-\nabla V\right) \times \boldsymbol{n}=\mathbf{0}, \quad] on stem:[\quad \Gamma_{E}].

This boundary condition can be specified by two Dirichlet boundary conditions,
stem:[\boldsymbol{n} \times \boldsymbol{A}=\mathbf{0}, \quad] and stem:[\quad V=V_{0}, \quad] on stem:[\quad \Gamma_{E}]
because stem:[-\boldsymbol{A} \times \boldsymbol{n}=\boldsymbol{n} \times \boldsymbol{A}] and stem:[V_{0}] is constant. Here stem:[\boldsymbol{B} \cdot \boldsymbol{n}=0] satisfies explicitly, because
stem:[\boldsymbol{B} \cdot \boldsymbol{n}=(\nabla \times \boldsymbol{A}) \cdot \boldsymbol{n}=\nabla \cdot(\boldsymbol{A} \times \boldsymbol{n})]
and stem:[A \times n=0] has been prescribed yet. 

== Formulation
Finally, here is the collection of equations and boundary conditions of the ungauged stem:[A, V]-formulation, stem:[\nabla \times\left(\nu_{o} \nabla \times \boldsymbol{A}\right)+\sigma \frac{\partial \boldsymbol{A}}{\partial t}+\sigma \nabla V=-\nabla \times \boldsymbol{I}, \quad] in stem:[\quad \Omega_{c}]
[stem]
++++
\begin{array}{l}
-\nabla \cdot\left(\sigma \frac{\partial \boldsymbol{A}}{\partial t}+\sigma \nabla V\right)=0, \quad \text { in } \quad \Omega_{c} \\
\left(\nu_{o} \nabla \times \boldsymbol{A}+\boldsymbol{I}\right) \times \boldsymbol{n}=\mathbf{0}, \quad \text { on } \quad \Gamma_{H_{c}} \\
-\sigma \frac{\partial \boldsymbol{A}}{\partial t} \cdot \boldsymbol{n}-\sigma \nabla V \cdot \boldsymbol{n}=0, \quad \text { on } \quad \Gamma_{H_{c}} \\
\boldsymbol{n} \times \boldsymbol{A}=\mathbf{0}, \quad \text { on } \Gamma_{E}
\end{array}
++++
stem:[V=V_{0}, \quad] on stem:[\quad \Gamma_{E}]

IMPORTANT: The solution of the problem defined by the above equations and boundary conditions is not unique, because the divergence of the magnetic vector potential has not specified yet. The Coulomb gauge should be used in this formulation similarly to the gauge fixing method applied in stem:[A] -formulation of static magnetic field problems (see on page 34 ), i.e. stem:[\nabla \cdot \boldsymbol{A}=0] must be specified.

First, let us append the left-hand side of the partial differential equation (2.294) by the stem:[\operatorname{term}-\nabla\left(\nu_{o} \nabla \cdot \boldsymbol{A}\right)]
stem:[\nabla \times\left(\nu_{o} \nabla \times \boldsymbol{A}\right)-\nabla\left(\nu_{o} \nabla \cdot \boldsymbol{A}\right)+\sigma \frac{\partial \boldsymbol{A}}{\partial t}+\sigma \nabla V=-\nabla \times \boldsymbol{I}, \quad] in stem:[\quad \Omega_{c}]
Taking the divergence of this equation and taking the equation (2.295) into account, it results in the Laplace equation for the scalar variable stem:[\nu_{o} \nabla \cdot \boldsymbol{A}]
stem:[-\nabla \cdot \nabla\left(\nu_{o} \nabla \cdot \boldsymbol{A}\right)=0]
After taking the normal component of the equation (2.300) on the boundary segment
stem:[\Gamma_{H_{c}},] a homogeneous Neumann boundary condition can be set up automatically stem:[-\frac{\partial}{\partial n}\left(\nu_{o} \nabla \cdot \boldsymbol{A}\right)=0, \quad] on stem:[\quad \Gamma_{H_{c}}]
because the normal component of the first and the last terms in (2.300)

stem:[\left[\nabla \times\left(\nu_{o} \nabla \times \boldsymbol{A}+\boldsymbol{I}\right)\right] \cdot \boldsymbol{n}=\nabla \cdot\left[\left(\nu_{o} \nabla \times \boldsymbol{A}+\boldsymbol{I}\right) \times \boldsymbol{n}\right]]
is equal to zero according to the boundary condition (2.296) and the normal component of the sum of the last two terms in (2.300) is equal to zero, too, because of the condition (2.297)
Consequently, on the rest part of the boundary stem:[\Gamma_{E},] the following Neumann type boundary condition:
[stem]
++++
\nu_{o} \nabla \cdot \boldsymbol{A}=0, \quad \text { on } \quad \Gamma_{E}
++++
must be specified. In this way stem:[\nu_{o} \nabla \cdot \boldsymbol{A} \equiv 0] can be satisfied in the whole problem region stem:[\Omega_{c}] and on the boundary stem:[\Gamma_{H_{c}} \cup \Gamma_{E}]

== Final Formulation

Finally, the partial differential equations and the boundary conditions of an eddy current field problem, which solution is unique according to Coulomb gauge can be written as


[stem]
++++
\begin{array}{rl}
\nabla \times\left(\nu_{o} \nabla \times \boldsymbol{A}\right)-\nabla\left(\nu_{o} \nabla \cdot \boldsymbol{A}\right)+\sigma \frac{\partial \boldsymbol{A}}{\partial t}+\sigma \nabla V&=-\nabla \times \boldsymbol{I}, \quad in \quad \Omega_{c}\\
-\nabla \cdot\left(\sigma \frac{\partial \boldsymbol{A}}{\partial t}+\sigma \nabla V\right)&=0, \quad in \quad \Omega_{c}\\
\left(\nu_{o} \nabla \times \boldsymbol{A}+\boldsymbol{I}\right) \times \boldsymbol{n}&=\mathbf{0}, \quad on \quad \Gamma_{H_{c}}\\
-\left(\sigma \frac{\partial \boldsymbol{A}}{\partial t}+\sigma \nabla V\right) \cdot \boldsymbol{n}&=0, \quad on \quad \Gamma_{H_{c}}\\
\boldsymbol{A} \cdot \boldsymbol{n}&=0, \quad on \quad \Gamma_{H_{c}}\\
\boldsymbol{n} \times \boldsymbol{A}&=\mathbf{0}, \quad \Gamma_{E}\\
V&=V_{0}, \quad on \quad \Gamma_{E}\\
\nu_{o} \nabla \cdot \boldsymbol{A}&=0, \quad on \quad \Gamma_{E}\\
\end{array}
++++


Here, equation (2.309) is introduced according to the proof presented on page 38

== Variational formulation

== Discretization