== Mixed Poisson

=== Notations and units

|===
| Notation | Quantity
|stem:[k]|conductivity
|stem:[\Lambda]|resistivity
|===

=== Equations

Mixed Poisson equations are
[stem]
++++
\begin{align}
\boldsymbol{u} + k\nabla p &= \boldsymbol{f}\\
\nabla\cdot \boldsymbol{u} &= g
\end{align}
++++
completed by boundary conditions.

The conductivity stem:[k] can be non-linear. If it depends only on the primal variable stem:[p], it is already handle by the model, in other cases, one needs to provide the corresponding expression.

=== MixedPoisson Toolbox

The model is described in a json file which path is given by the option `mixedpoisson.model_json`.
The construction of this file is detailed in the following sections.

==== Models

The models are not considered for now.

[source,json]
.Model section
----
"Model": "HDG"
----

==== Materials

The definition of the conductivity stem:[k] depends on the material, it can be linear or non-linear.
In the linear case, it is given in the material we work on by the keyword `cond` and in the non-linear case, by `condNL`.

[source,json]
.Material section
----
"Materials":
{
    "<marker>":
    {
        "name": "copper",
        "cond": "1",
	"condNL": "2*p:p"
    }
}
----

The keywords `cond` and `condNL` can be changed respectively by the options `mixedpoisson.conductivity_json` and `mixedpoisson.conductivityNL_json`.

==== Boundary Conditions

All boundary conditions are described in the same way

[source,json]
.Listing : boundary conditions in json
----
"BoundaryConditions":
{
    "<field>":
    {
        "<bc_type>":
        {
            "<marker>":
            {
                "<option1>":"<value1>",
                "<option2>":"<value2>",
                // ...
            }
        }
    }
}
----

Different types of boundary condition are available.

===== Dirichlet condition

[stem]
++++
p = g_D
++++

|===
| Field | Type | Option | Value
| `potential` | `Dirichlet` | `expr` | stem:[g_D]
|===

===== Neumann condition

[stem]
++++
-k\nabla p \cdot\boldsymbol{n} = g_N
++++

|===
| Field | Type | Option | Value
| `potential` | `Neumann` | `expr` | stem:[g_DN] or stem:[-k\nabla p]
|===
The choice between stem:[g_DN] or stem:[-k\nabla p] is base on the dimension of the expression.

===== Robin condition

[stem]
++++
-k\nabla p \cdot\boldsymbol{n} + g_R^1 p = g_R^2
++++

|===
| Field | Type | Option | Value
| `potential` | `Robin` | `expr1` | stem:[g_R^1]
| `potential` | `Robin` | `expr2` | stem:[g_R^2]
|===

===== Integral boundary condition

[stem]
++++
\int_{\Gamma_I} \boldsymbol{u}\cdot\boldsymbol{n} = g_I
++++

|===
| Field | Type | Option | Value
| `flux` | `Integral` | `expr` | stem:[g_I]
|===

==== Source Terms

The source terms stem:[f] and stem:[\boldsymbol{g}] are treated as boundary condtions.

|===
| Field | Type | Option | Value
| `potential` | `SourceTerm` | `expr` | stem:[f]
| `flux` | `SourceTerm` | `expr` | stem:[\boldsymbol{g}]
|===

==== Post Process

Two fields can be exported, the potential stem:[p] and the flux stem:[\boldsymbol{u}].

[source,json]
.Post Process section
----
"PostProcess":
{
    "Fields":["potential","flux"]
}
----

=== Create applications

In order to solve linear problem, an application should contain at least

[source,cpp]
.Minimal Linear case
----
    typedef FeelModels::MixedPoisson<FEELPP_DIM,FEELPP_ORDER> mp_type;
    auto MP = mp_type::New("mixedpoisson");
    MP->init();
    MP->assembleAll();
    MP->solve();
    MP->exportResults();
----
