= CFD
:page-layout: manual 
:page-permalink: /toolbox/cfd/
:page-root: /
:title: Computational Fluid Dynamics
:doctype: book
:docinfo: shared
:imagesdir: /images/
:sources: ../../
include::../includes/header.adoc[]


= CFD Model

Benchmarks are available at link::/benchmarks/cfd[CFG Benchmarks]

== Notations and units

|===
| Notation | Quantity | Unit

|stem:[\rho_f]|fluid density|stem:[kg \cdot m^{-3}]
|stem:[\boldsymbol{u}_f]|fluid velocity|stem:[m \cdot s^{-1}]
|stem:[\boldsymbol{\sigma}_f]|fluid stress tensor|stem:[N \cdot m^{-2}]
|stem:[\boldsymbol{f}^t_f]| source term | stem:[kg \cdot m^{-3} \cdot s^{-1}]
|stem:[p_f]|pressure fields|stem:[kg \cdot m^{-1} \cdot s^{-2}]
|stem:[\mu_f]| dynamic viscosity|stem:[kg \cdot m^{-1} \cdot s^{-1}]
|stem:[\bar{U}]|characteristic inflow velocity|stem:[m \cdot s^{-1}]
|stem:[\nu]|kinematic viscosity|stem:[m^2 \cdot s^{-1}]
|stem:[L]| characteristic length|stem:[m]
|===


== Equations

Navier-Stokes model is used to model incompressible Newtonian fluid.
It can be described by these conservative laws :

[stem]
.Momentum conservation equation
++++
\rho_{f} \left. \frac{\partial\mathbf{u}_f}{\partial t} \right|_\mathrm{x}
+ \rho_{f} \left( \boldsymbol{u}_{f} \cdot \nabla_{\mathrm{x}} \right) \boldsymbol{u}_{f}
- \nabla_{\mathrm{x}} \cdot \boldsymbol{\sigma}_{f} = \boldsymbol{f}^t_f , \quad \text{ in } \Omega^t_f \times \left[t_i,t_f \right]
++++

[env.equation]
[stem]
.Mass conservation equation
++++
\nabla_{\mathrm{x}} \cdot \boldsymbol{u}_{f} = 0, \quad \text{ in } \Omega^t_f \times \left[t_i,t_f \right]
++++

we complete this set of equations with the fluid constitutive law

[env.equation]
.Material constitutive equation
--
\boldsymbol{\sigma}_{f} = -p_f \boldsymbol{I} + 2\mu_f D(\boldsymbol{u}_{f})
--

with strain tensor stem:[D(\boldsymbol{u}_{f})] defined by :

[env.equation]
.Strain tensor
--
D(\boldsymbol{u}_{f}) = \frac{1}{2} (\nabla_\mathrm{x} \boldsymbol{u}_f + (\nabla_\mathrm{x} \boldsymbol{u}_f)^T)
--

An alternative model is the Stokes model. It is valid in the case of small Reynolds number. It corresponds to the same formulation than Navier-Stokes equations but without the convective term stem:[\left( \boldsymbol{u}_{f} \cdot \nabla_{\mathrm{x}} \right) \boldsymbol{u}_{f}] .


:leveloffset: +1

include::../man/03-modeling/Fluid/README.adoc[]

:leveloffset: -1
