= Heat Benchmarks : ISO 10211:2007 Thermal bridges in building construction
// Don't put authors here! (see CONTRIBUTING)
//*******************************************
:page-layout: manual 
:page-permalink: /benchmarks/heat/toolbox/bm-1/
:page-root: ../../../../
:title: Heat Transfer Benchmark
:doctype: book
:docinfo: shared
:imagesdir: /images/
:sources: ../../../
// Keep this include header at the end! (see CONTRIBUTING)
include::../../../includes/header.adoc[]
//*******************************************

== Introduction

ISO 10211:2007 sets out the specifications for a three-dimensional and a two-dimensional geometrical model of a thermal bridge for the numerical calculation of:

 . heat flows, in order to assess the overall heat loss from a building or part of it;
 . minimum surface temperatures, in order to assess the risk of surface condensation.

These specifications include the geometrical boundaries and subdivisions of the model, the thermal boundary conditions, and the thermal values and relationships  to be used.

ISO 10211:2007 is based upon the following assumptions:

 . all physical properties are independent of temperature;
 . there are no heat sources within the building element.

ISO 10211:2007 can also be used for the derivation of linear and point thermal  transmittances and of surface temperature factors.
More information link:http://www.iso.org/iso/catalogue_detail.htm?csnumber=40967[here].

== Inputs

== Outputs

== Running the model

The configuration file is in `/usr/local/share/feelpp/testcases/Heat/Building/ThermalBridgesENISO10211/thermo2dCase2.cfg`.
The command line in feelpp-toolboxes docker or singularity reads 

.Command line to execute the torsionbar testcase
[source,sh]
----
$ mpirun -np 4 /usr/local/bin/feelpp_toolbox_heat_2d --config-file thermo2dCase2.cfg
----

== Results
