= {feelpp} for Multiphysics Modeling and Simulation

{feelpp} provides a  powerful  environment for modeling and solving various kinds of scientific and engineering problems.
The framework provides a powerful language to describe these models.
With {feelpp} toolboxes, you can extend conventional models for one type of physics into multiphysics models that solve coupled physics phenomena.
It does not require an in-depth knowledge of mathematics or numerical analysis, they are hidden with the toolboxes.
Using the xref:what-is-a-toolbox.adoc#_json_files[JSON] and xref:what-is-a-toolbox.adoc#_cfg_files[CFG], it is possible to configure and run models by defining the relevant physical quantities—such as material properties, loads, constraints, sources, and fluxes.

Using these physics interfaces, you can perform various types of studies including:

* [x] Stationary and time-dependent (transient) studies
* [x] Linear and nonlinear studies

When solving the models, {feelpp} Toolboxes uses the standard Galerkin method, eg the proven Finite element method but more advanced methods sur as HDG methods are available. The software runs the finite element analysis using a variety of numerical solvers.
The studies can make use of multiprocessor systems and cluster computing and run from a one core to thousands of cores seamlessly.
A more detailed description of this mathematical and numerical foundation is in  xref:math:ROOT:index.adoc[Mathematics of {feelpp}].
