This test case is taken from <<patera>>.

== Problem description

We consider an advection-diffusion problem in a rectangular parametrized domain $$\Omega_0(\mu) = ]0,L[\times]0,1[$$ representing a channel.
The  governing equation for the temperature T (passive-scalar field) is the advection-diffusion equation \eqref{advec-diff2D} with imposed Couette velocity $$\mathbf{u} = (y , 0)$$.
$$
    \mathbf{u} \cdot \nabla T - \frac{1}{Pe} \Delta T  = 0
$$
Note that $$Pe$$ is the Péclet number.
[source]
--
\begin{figure}[h]
  \begin{center}
    \begin{tikzpicture}
      \draw (0,0) -- node[label=below:$\Gamma_{bottom}$]{} (6,0);
      \draw (6,0) -- node[label=right:$\Gamma_{out}$]{} (6,1);
      \draw (6,1) -- node[label=above:$\Gamma_{top}$]{} (0,1);
      \draw (0,1)  -- node[label=left:$\Gamma_{in}$]{} (0,0);
      %\draw [<->] (0,-0.1) -- node [label=below:L]{} (6,-0.1);
    \end{tikzpicture}
    \caption{ \label{omega} Study domain $\Omega$ with a fixed length $L$.}
  \end{center}
\end{figure}
--

=== Boundary conditions

We set

* on $$\Gamma_{in}$$ and $$ \Gamma_{top} $$, an homogeneous Dirichlet condition
$$
  T = 0;
$$
* at $$\Gamma_{bottom}$$, a non-homogeneous Neumann condition
$$
    \nabla T \cdot \mathbf{n}  = 1
$$
* at $$\Gamma_{out}$$, an homogeneous Neumann condition
$$
    \nabla T \cdot \mathbf{n}  = 0
$$

=== Inputs

As inputs, We define the parameter set $$\mu$$  by
$$
  \mu=(L,Pe)~\in~[1~,~10] \times [0.1~,~100]
$$

=== Outputs

The output $$s(\mu)$$ is the integral of the temperature over the heated surface $$\Gamma_{\mathrm{bottom}}$$ defined by
$$
  s(\mu) = \int_{\Gamma_{bottom}} T
$$
This output depends on the solution of the advection diffusion equation above and is dependent on
the parameter set $$\mu$$.

[bibliography]
.Bibliography
 - [[[patera]]] G. Rozza, D.B.P. Huynh, A.T. Patera, _Reduced Basis Approximation and A Posteriori Error Estimation for Affinely Parametrized Elliptic Coercive Partial Differential Equations — Application to Transport
 and Continuum Mechanics_, Arch Comput Methods Eng, 2008
