= How {feelpp} works

{feelpp} is not one application, one executable, it is a set of libraries and applications.
It provides a framework to deal with each step of the pipeline for solving partial differential equations.
{feelpp} applications, however, do share commonalities: they follow necessary and optional steps that we describe below in a general manner.
More technical details are available in the xref:dev::index.adoc[Developer Manual].

Start {feelpp} environment::
When executing a {feelpp} application,  a runtime environment is started. It enables
* xref:tools:remotedata.adoc[retrieving remote data]
* creating a directory where the results of the applications are stored
* command line options and configuration files
* parallel computing: both MPI and multi-threading.
* logging support: log files are generated by the {feelpp} library. They contain information about how the applications run.
* {optional) enabling parallel solver frameworks {petsc} and {slepc}

Do some general operations::
The following steps are optional but are very common in {feelpp} applications including the {feelpptb}
* [x] Define and xref:tools:mesh_partitioner.adoc[partition] meshes
* [x] Define function spaces
* [x] Define linear and bilinear forms
* [x] Solve linear or nonlinear algebraic systems
* [x] Export data to scientific visualization data formats
* [x] xref:tools:remotedata.adoc[Upload result data to a data management system]

Exit {feelpp} environment::
When exiting a {feelpp} application, the system is properly shutdown:

* [x] all files are saved and closed.
* [x] (optional) the parallel solver frameworks are shut down
* [x] the parallel computing framework is shutdown
