= Introduction


{feelpp} is a unified {cpp} implementation of Galerkin methods (finite and
spectral element methods) in 1D, 2D and 3D to solve partial differential
equations.

{feelpp} is

. a **versatile mathematical kernel** solving easily problems using
   different techniques thus allowing testing and comparing methods, e.g. cG versus dG.
. a *small* and *manageable* library which nevertheless encompasses a wide
  range of numerical methods and techniques and in particular reduced order
  methods such as the reduced basis method.
. a software that follows closely the mathematical abstractions
  associated with partial differential equations (PDE) and in
  particular the finite element mathematical framework and
  variational formulations.
. a library that offers solving strategies that scales up to
  thousands and even tens of thousands of cores.
. a library entirely in {cpp} allowing to create {cpp} complex and typically
  non-linear multi-physics applications currently in industry, physics and
  health-care.
