= Computational Fluid Mechanics Toolbox

== Notations and units

|===
| Notation | Quantity | Unit

|stem:[\rho_f]|fluid density|$$kg.m^{-3}$$
|stem:[\boldsymbol{u}_f]|fluid velocity|$$m.s^{-1}$$
|stem:[\boldsymbol{\sigma}_f]|fluid stress tensor|$$N.m^{-2}$$
|stem:[\boldsymbol{f}^t_f]| source term | $$kg.m^{-3}.s^{-1}$$
|stem:[p_f]|pressure fields|$$kg.m^{-1}.s^{-2}$$
|stem:[\mu_f]| dynamic viscosity|$$kg.m^{-1}.s^{-1}$$
|stem:[\bar{U}]|characteristic inflow velocity|$$m.s^{-1}$$
|stem:[\nu]|kinematic viscosity|$$m^2.s^{-1}$$
|stem:[L]| characteristic length|stem:[m]
|===


== Équations

Navier-Stokes model is used to model incompressible Newtonian fluid.
It can be described by these conservative laws :

[env.equation]
.Momentum conservation equation
--
\rho_{f} \left. \frac{\partial\mathbf{u}_f}{\partial t} \right|_\mathrm{x}
+ \rho_{f} \left( \boldsymbol{u}_{f} \cdot \nabla_{\mathrm{x}} \right) \boldsymbol{u}_{f}
- \nabla_{\mathrm{x}} \cdot \boldsymbol{\sigma}_{f} = \boldsymbol{f}^t_f , \quad \text{ in } \Omega^t_f \times \left[t_i,t_f \right]
--

[stem]
.Momentum conservation equation
++++
\rho_{f} \left. \frac{\partial\mathbf{u}_f}{\partial t} \right|_\mathrm{x}
+ \rho_{f} \left( \boldsymbol{u}_{f} \cdot \nabla_{\mathrm{x}} \right) \boldsymbol{u}_{f}
- \nabla_{\mathrm{x}} \cdot \boldsymbol{\sigma}_{f} = \boldsymbol{f}^t_f , \quad \text{ in } \Omega^t_f \times \left[t_i,t_f \right]
++++

[env.equation]
.Mass conservation equation
--
\nabla_{\mathrm{x}} \cdot \boldsymbol{u}_{f} = 0, \quad \text{ in } \Omega^t_f \times \left[t_i,t_f \right]
--

we complete this set of equations with the fluid constitutive law

[env.equation]
.Material constitutive equation
--
\boldsymbol{\sigma}_{f} = -p_f \boldsymbol{I} + 2\mu_f D(\boldsymbol{u}_{f})
--

with strain tensor stem:[D(\boldsymbol{u}_{f})] defined by :

[env.equation]
.Strain tensor
--
D(\boldsymbol{u}_{f}) = \frac{1}{2} (\nabla_\mathrm{x} \boldsymbol{u}_f + (\nabla_\mathrm{x} \boldsymbol{u}_f)^T)
--

An alternative model is the Stokes model. It is valid in the case of small Reynolds number. It corresponds to the same formulation than Navier-Stokes equations but without the convective term $$\left( \boldsymbol{u}_{f} \cdot \nabla_{\mathrm{x}} \right) \boldsymbol{u}_{f}$$ .

The fluid mechanics model (`Navier-Stokes` or `Stokes`) can be selected in json file:

[source,json]
.Listing : select fluid model
-----
"Model": "Navier-Stokes"
-----

== Materials


The next step is to define the fluid material by setting its properties namely the density stem:[\rho_f] and viscosity stem:[\mu_f].
In next table, we find the correspondance between the mathematical names and the json names.

[cols="1,1", options="header"]
.Correspondance between fluid parameters and symbols in JSon files
|===
| Parameter | Symbol

| stem:[\mu_f] | `mu`
| stem:[\rho_f]  | `rho`

|===

A `Materials` section is introduced in json file in order to configure the fluid properties. For each mesh marker, we can define the material properties associated.

[source,json]
.Listing : Materials section
----
"Materials":
{
    "<marker>"
    {
        "name":"water",
        "rho":"1.0e3",
        "mu":"1.0"
    }
}
----
=== Generalised Newtonian fluid
A non newtonian fluid is characterized by a non constant viscosity, which is a function of strain rate stem:[\boldsymbol{D}\left(\boldsymbol{u}_{f}\right)]. We start by introducing a metric of the rate of deformation, denoted by stem:[\dot{\gamma}]:

[env.equation]
.Rate of deformation
--
\dot{\gamma} \equiv \sqrt{2 \ tr \left( \boldsymbol{D}\left(\boldsymbol{u}_{f}\right)^{2} \right)  }
--

We represent the viscosity stem:[\mu_f] as a function of stem:[\dot{\gamma}].  The deviatoric stress tensor stem:[\boldsymbol{\tau}] is obtained thanks to generalised Newtonian model, which takes the following form:

[env.equation]
.Deviatoric stress tensor
--
  \boldsymbol{\tau} = 2 \mu_f \left(\dot{\gamma} \right) \boldsymbol{D}\left(\boldsymbol{u}_{f}\right)
--

The simplest example of a generalised Newtonian model is the power-law fluid, which has a viscosity given by:

[env.equation]
.Power law
--
\mu_f \left(\dot{\gamma} \right) = k \dot{\gamma}^{n-1}
--

where stem:[k] and $$n < 1$$ are two parameters related to fluid properties.

[NOTE]
.Blood flow viscosity
====
In the context of blood flow modeling, an extension of the power model was proposed by Walburn and Schneck.

The parameters stem:[k] and stem:[n] are related to the hematocrit stem:[Ht] and Total Proteins Minus Albumin (TPMA) as follows

[env.equation]
--
k = C_1 e^{C_2 Ht} e^{C_4 \text{TPMA} / Ht }, \quad\quad    n = 1- C_3 H t
--
====

and stem:[C_i, i=1,..,4] are parameters to fit with experimental data.


Another family of generalised Newtonian model can be defined from a function stem:[\Phi] express by:

[env.equation]
--
  \Phi\left( \dot{\gamma}, \mu_{\infty},\mu_{0} \right)
  = \frac{\mu\left(\dot{\gamma}\right) - \mu_{\infty}}{\mu_{0}-\mu_{\infty}}
--

where stem:[\mu_0] and stem:[\mu_{\infty}] are the asymptotic viscosities at zero and infinite shear rate.


[cols="1,1", options="header"]
|===
| Viscosity law | stem:[\Phi\left( \dot{\gamma}, \mu_{\infty},\mu_{0} \right) ]
| Carreau | stem:[\left(1+\left(\lambda\dot{\gamma}\right)^{2}\right)^{(n-1)/2}]
| Carreau-Yasuda | stem:[\left(1+\left(\lambda\dot{\gamma}\right)^{a}\right)^{(n-1)/a}]
|===


The non Newtonian properties are defined in cfg file in fluid section.

The viscosity law is activated by:
[cols="1,1", options="header"]
.Viscosity law
|===
| option | values
| viscosity.law | newtonian, power_law, walburn-schneck_law, carreau_law, carreau-yasuda_law
|===

Then, each model are configured with the options reported in the following table:

[cols="1,1,1", options="header"]
|===
| Viscosity law | options | unit
| power_law |
power_law.k

power_law.n
| dimensionless

dimensionless

| walburn-schneck_law |
hematocrit

TPMA

walburn-schneck_law.C1

walburn-schneck_law.C2

walburn-schneck_law.C3

walburn-schneck_law.C4

| Percentage

g/l

dimensionless

dimensionless

dimensionless

l/g
| carreau_law |
viscosity.zero_shear

viscosity.infinite_shear

carreau_law.lambda

carreau_law.n
|

stem:[kg.m^{-1}.s^{-1}]

dimensionless

dimensionless
| carreau-yasuda_law |
viscosity.zero_shear

viscosity.infinite_shear

carreau-yasuda_law.lambda

carreau-yasuda_law.n

carreau-yasuda_law.a
|
stem:[kg/(m \times s)]

stem:[kg/(m \times s)]

dimensionless

dimensionless

dimensionless

|===





=== Boundary Conditions
We start by a listing of boundary conditions supported in fluid mechanics model.



==== Dirichlet on velocity

A Dirichlet condition on velocity field reads:
[env.equation]
.Dirichlet condition
--
\boldsymbol{u}_f = \boldsymbol{g} \quad \text{ on } \Gamma
--

or only a component of vector stem:[\boldsymbol{u}_f =(u_f^1,u_f^2 ,u_f^3 )]

[env.equation]
--
u_f^i = g \quad \text{ on } \Gamma
--

Several methods are available to enforce the boundary condition:

* elimination
* Nitsche
* Lagrange multiplier

==== Dirichlet on pressure


[env.equation]
--
\begin{eqnarray}
p &=& g \\
\boldsymbol{u}_f \times \boldsymbol{n} &=& \boldsymbol{0}
\end{eqnarray}
--

=== Neumann

[cols="1,1", options="header"]
.Neumann options
|===
| Name  | Expression
| Neumann_scalar | stem:[\boldsymbol{\sigma}_{f} \boldsymbol{n}  = g \ \boldsymbol{n} ]
| Neumann_vectorial | stem:[\boldsymbol{\sigma}_{f} \boldsymbol{n}  =   \boldsymbol{g} ]
| Neumann_tensor2 | stem:[\boldsymbol{\sigma}_{f} \boldsymbol{n}  = g \ \boldsymbol{n}]
|===

=== Slip

[env.equation]
--
\boldsymbol{u}_f \cdot \boldsymbol{n} = 0
--

=== Inlet

The boundary condition at inlets allow to define a velocity profile on a set of marked faces stem:[\Gamma_{\mathrm{inlet}}] in fluid mesh:
[env.equation]
--
\boldsymbol{u}_f = - g \ \boldsymbol{n} \quad \text{ on } \Gamma_{\mathrm{inlet}}
--

The function stem:[g] is computed from flow velocity profiles:

Constant profile::
[env.equation]
--
\text{Find } g \in C^0(\Gamma) \text{ such that } \\
\begin{eqnarray}
g &=& \beta \quad &\text{ in } \Gamma \setminus \partial\Gamma
\\
g&=&0 \quad &\text{ on } \partial\Gamma
\end{eqnarray}
--
Parabolic profile::
[env.equation]
--
\text{Find } g \in H^2(\Gamma) \text{ such that : } \\
\begin{eqnarray}
\Delta g &=& \beta \quad &\text{ in } \Gamma \\
g&=&0 \quad &\text{ on } \partial\Gamma
\end{eqnarray}
--

where stem:[\beta] is a constant determined by adding a constraint to the inflow:

velocity_max:: stem:[\max( g ) = \alpha ]

flow_rate:: stem:[\int_\Gamma ( g \ \boldsymbol{n} ) \cdot \boldsymbol{n} = \alpha]


[cols="1,1,1,1", options="header"]
.Inlet flow options
|===
| Option | Value | Default value |Description
| shape | `constant`,`parabolic` |  | select a shape profile for inflow
|constraint | `velocity_max`,`flow_rate` | | give a constraint wich controle velocity
| expr | string | | symbolic expression of constraint value
|===


=== Outlet flow

[cols="1,1,1,1", options="header"]
.Outlet flow options
|===
| Option | Value | Default value |Description
| model | free,windkessel | free | select an outlet modeling
|===







==== Free outflow

[env.equation]
--
\boldsymbol{\sigma}_{f} \boldsymbol{n} = \boldsymbol{0}
--

==== Windkessel model
We use a 3-element Windkessel model for modeling an outflow boundary condition.
We define stem:[P_l] a pressure and stem:[Q_l] the flow rate.
The outflow model is discribed by the following system of differential equations:
[env.equation]
--
\left\{
\begin{aligned}
  C_{d,l} \frac{\partial \pi_l}{\partial t} + \frac{\pi_l}{R_{d,l}} = Q_l \\
  P_l = R_{p,l} Q_l + \pi_l
\end{aligned}
\right.
--
Coefficients stem:[R_{p,l}] and stem:[R_{d,l}] represent respectively the proximal and distal resistance.
The constant stem:[C_{d,l}] is the capacitance of blood vessel.
The unknowns stem:[P_l] and stem:[\pi_l] are called proximal pressure and distal pressure.
Then we define the coupling between this outflow model and the fluid model by these two relationships:

[env.equation]
--
\begin{align}
  Q_l &= \int_{\Gamma_l} \boldsymbol{u}_f \cdot \boldsymbol{n}_f  \\
  \boldsymbol{\sigma}_f \boldsymbol{n}_f &= -P_l \boldsymbol{n}_f
\end{align}
--



[cols="1,1,1", options="header"]
.Windkessel options
|===
| Option | Value | Description
| windkessel_coupling | explicit, implicit |  coupling type with the Navier-Stokes equation
| windkessel_Rd | real | distal resistance
| windkessel_Rp | real | proximal resistance
| windkessel_Cd | real | capacitance
|===


=== Implementation of boundary conditions in json

Boundary conditions are set in the json files in the category `BoundaryConditions`.

Then `<field>` and `<bc_type>` are chosen from type of boundary condition.

The parameter `<marker>` corresponds to mesh marker where the boundary condition is applied.

Finally, we define some specific options inside a marker.

[source,json]
.Listing : boundary conditions in json
----
"BoundaryConditions":
{
    "<field>":
    {
        "<bc_type>":
        {
            "<marker>":
            {
                "<option1>":"<value1>",
                "<option2>":"<value2>",
                // ...
            }
        }
    }
}
----







=== Options summary


[cols="1,1,1,1", options="header"]
.Boundary conditions
|===
| Field | Name | Option | Entity

| velocity
| Dirichlet
| expr

 type

 number

 alemesh_bc

| faces, edges, points
| velocity_x

velocity_y

velocity_z


| Dirichlet
| expr

 type

  number

  alemesh_bc

 | faces, edges, points

| velocity

| Neumann_scalar
| expr

number

alemesh_bc
| faces
| velocity

| Neumann_vectorial
| expr

number

alemesh_bc
| faces
| velocity

| Neumann_tensor2
| expr

number

alemesh_bc
| faces

| velocity
| slip
| alemesh_bc
| faces

| pressure
| Dirichlet
| expr

number

alemesh_bc

|faces

| fluid
| outlet
| number

alemesh_bc

model

windkessel_coupling

windkessel_Rd

windkessel_Rp

windkessel_Cd

| faces

| fluid

| inlet

| expr

shape

constraint

number

alemesh_bc

| faces

|===

== Volumic forces

Body forces are also defined in `BoundaryConditions` category in json file.
[source,json]
----

"VolumicForces":
{
    "<marker>":
    {
        "expr":"{0,0,-gravityCst*7850}:gravityCst"
    }
}
----
The marker corresponds to mesh elements marked with this tag.
If the marker is an empty string, it corresponds to all elements of the mesh.


=== Post Processing

[source,json]
----
"PostProcess":
{
    "Fields":["field1","field2",...],
    "Measures":
    {
        "<measure type>":
        {
            "label":
            {
                "<range type>":"value",
                "fields":["field1","field3"]
            }
        }
    }
}
----

==== Exports for vizualisation
The fields allowed to be exported in the `Fields` section are:

- velocity
- pressure
- displacement
- vorticity
- stress or normal-stress
- wall-shear-stress
- density
- viscosity
- pid
- alemesh

==== Measures

- Points
- Force
- FlowRate
- Pressure
- VelocityDivergence


===== Points
In order to evaluate velocity or pressure at specific points and save the results in .csv file, the user must define:

- "<tag>" representing this data in the .csv file
- the coordinate of point
- the fields evaluated ("pressure" or "velocity")

[source,json]
----
"Points":
{
  "<tag>":
  {
    "coord":"{0.6,0.2,0}",
    "fields":"pressure"
  },
 "<tag>":
  {
    "coord":"{0.15,0.2,0}",
    "fields":"velocity"
  }
}
----


===== Flow rate
The flow rate can be evaluated and save on .csv file.
The user must define:

- "<tag>" representing this data in the .csv file
- "<face_marker>" representing the name of marked face
- the fluid direction ("interior_normal" or "exterior_normal") of the flow rate.

[source,json]
----
"FlowRate":
{
    "<tag>":
    {
        "markers":"<face_marker>",
        "direction":"interior_normal"
    },
    "<tag>":
    {
        "markers":"<face_marker>",
        "direction":"exterior_normal"
    }
}
----


===== Forces
compute lift and drag

[source,json]
----
"Forces":["fsi-wall","fluid-cylinder"]
----



==== Export user functions
A function defined by a symbolic expression can be represented as a finite element field thanks to nodal projection.
This function can be exported.

[source,json]
----
"Functions":
{
    "toto":{ "expr":"x*y:x:y"},
    "toto2":{ "expr":"0.5*ubar*x*y:x:y:ubar"},
    "totoV":{ "expr":"{2*x,y}:x:y"}
},
"PostProcess":
{
   "Fields":["velocity","pressure","pid","totoV","toto","toto2"],
}
----

=== Action

Let's finish with a simple example in order to show how this works.
We will interest us to a fluid flow into a cavity in 3D.

==== Feel++ code
Here is the code

First at all, we define our model type with

----
typedef FeelModels::FluidMechanics< Simplex<FEELPP_DIM,1>,
                                    Lagrange<OrderVelocity,Vectorial,Continuous,PointSetFekete>,
                                    Lagrange<OrderPressure,Scalar,Continuous,PointSetFekete> > model_type;
----

We choose here a stem:[\mathbb{P}_2] space for the velocity order and
stem:[\mathbb{P}_1] space for the pressure order. This definition allows us to
create our fluid model object FM like this

----
auto FM = model_type::New("fluid");
----

The method `New` retrieves all data from the configuration and json files and build a mesh if needed.

With this object, we can initialize our model parameters, such as velocity or
boundaries conditions. Data on our model and on the numeric solver are then
save and print on the terminal. This is made by

----
FM->init();
FM->printAndSaveInfo();
----

Now that our model is completed, we can solve the associated problem. To begin the resolution

----
FM->isStationary()
----

determine if our model is stationary or not.

If it is, then we need to solve our system only one time and export the obtained results.

----
FM->solve();
FM->exportResults();
----

If it's not, our model is time reliant, and a loop on time is necessary. Our model is then solve and the results are export at each time step.

----
 for ( ; !FM->timeStepBase()->isFinished(); FM->updateTimeStep() )
        {
            FM->solve();
            FM->exportResults();
        }
----

===== Code

[source,cpp]
----
{% include "../Examples/fluid_model.cpp" %}
----


==== Configuration file

The config file is used to define options,  linked to our case, we would have the possibility to change at will. It can be, for example, files paths as follows

----
[fluid]
geofile=$cfgdir/cavity3d.geo
filename=$cfgdir/cavity3d.json

[exporter]
directory=applications/models/fluid/cavity3d/$fluid_tag
----

It can also be resolution dependent parameters such as mesh elements size, methods used  to define our problem and solvers.

----
[fluid]
solver=Oseen #Picard,Newton

linearsystem-cst-update=false
jacobian-linear-update=false

snes-monitor=true
snes-maxit=100
snes-maxit-reuse=100
snes-ksp-maxit=1000
snes-ksp-maxit-reuse=100

pc-type=lu #gasm,lu,fieldsplit,ilu
----
In this case, we use Oseen to define our problem, we set the update of linear system constant and jacobian linear as "no update", we discretize values associated to SNES ( Scalable Nonlinear Equations Solvers ), and finally we choose LU as the preconditioner method.

===== Code

[source,cfg]
----
{% include "../Examples/cavity3d.cfg" %}
----

==== Json file

First at all, we define some general information like the name ( and short name ) and the model we would like to use

[source,json]
----
"Name": "Fluid Mechanics",
"ShortName":"Fluid",
"Model":"Navier-Stokes",
----

Then we define the link:#Material[material properties]. In our case, the fluid, define  by rho` its density in $$kg\cdot m^{-3}$$ and `mu` its dynamic viscosity in $$kg\cdot (m \cdot s)^{-1}$$, is the only material we have to define.

[source,json]
----
"Materials":
    {
        "Fluid":{
            "name":"myFluidMat",
            "rho":"1.0",
            "mu":"0.01"
        }
    },
----

The link:#Boundary_Conditions[boundary conditions] are the next aspect we define. Here, we impose on the velocity stem:[u_f] Dirichlet conditions at two specific places : `lid` and `wall`.

[source,json]
----
"BoundaryConditions":
    {
        "velocity":
        {
            "Dirichlet":
            {
                "lid":
                {
                    "expr":"{ 1,0,0}:x:y:z"
                },
                "wall":
                {
                    "expr":"{0,0,0}"
                }
            }
        }
    }
----

The link:#Post_Process[post process] aspect is the last one to define. We choose the fields we want to export ( velocity, pressure and pid ). Furthermore, we want to measure forces on `wall` and the pressure at point stem:[A].

[source,json]
----
"PostProcess":
    {
        "Fields":["velocity","pressure","pid"],
        "Measures":
        {
            "Forces":"wall",
            "Points":
            {
                "pointA":
                {
                    "coord":"{0.5,0.5,0.5}",
                    "fields":"pressure"
                }
            }
        }
    }
}
----

===== Code

[source,json]
----
{% include "../Examples/cavity3d.json" %}
----

==== Compilation/Execution

Once you've a build dir, you just have to realise the command `make` at

--------------------
{buildir}/applications/models/fluid
--------------------

This will generate executables named `feelpp_application_fluid_*`. To execute it, you need to give the path of the cfg file associated to your case, with `--config-file`.

For example

----
./feelpp_application_fluid_3d --config-file={sourcedir}/applications/models/fluid/cavity/cavity3d.cfg
----

is how to execute the case ahead.

The result files are then stored by default in

----
 feel/applications/models/fluid/{case_name}/
   {velocity_space}{pression_space}{Geometric_order}/{processor_used}
----

If we return once again at our example, the result files are in

----
 feel/applications/models/fluid/cavity3d/P2P1G1/np_1
----
