= Electrostatics toolbox

The starting point is the xref:math:maxwell/Maxwell.adoc[Maxwell equations].

== Quasi static approximation, Electrostatics

A consequence of Maxwell’s equations is that changes in time of currents and charges are not synchronized with changes of the electromagnetic fields.
There is a delay between the changes of the sources and the changes of the fields.
The electromagnetic waves propagates at finite speed.
If we ignore this effect, we obtain the electromagnetic fields by considering stationary currents at every instant.

NOTE: It is called the *quasi-static approximation* also called electrostatics and magnetostatics approximations

The approximation is valid provided that the variations in time are small or absent and that the studied geometries are considerably smaller than the wavelength.
The quasi-static approximation implies that the equation of continuity can be written as

[stem]
====
\nabla cdot \mathbf{J} = 0
====

and that the time derivative of the electric displacement stem:[\nabla D/ \nabla t] can be disregarded in Maxwell-Ampère’s law.


== Notations and Units


== Equations
