= Electrostatics toolbox

The starting point is the xref:toolboxes:maxwell/Maxwell.adoc[Maxwell equations].

== Quasi static approximation, Electrostatics

A consequence of Maxwell’s equations is that changes in time of currents and charges are not synchronized with changes of the electromagnetic fields.
There is a delay between the changes of the sources and the changes of the fields.
The electromagnetic waves propagate at finite speed.
If we ignore this effect, we obtain the electromagnetic fields by considering stationary currents at every instant.

NOTE: It is called the *quasi-static approximation* also called electrostatics and magnetostatics approximations

The approximation is valid provided that the variations in time are small or absent and that the studied geometries are considerably smaller than the wavelength.
The quasi-static approximation implies that the equation of continuity can be written as

[stem]
++++
\nabla \cdot \mathbf{j} = 0
++++

and that the time derivative of the electric displacement stem:[\partial D/ \partial t] can be disregarded in Maxwell-Ampère’s law.


== Notations and Units

|===
| Field | Notation | Unit (SI)
| Electric field | stem:[\mathbf{E}] |
| Electric potential | stem:[V] | V
| Current density | stem:[\mathbf{j}] |
| Electric conductivity | stem:[\mathbf{\sigma}]
|===

== Equations

Consider that

- we are in quasi-electrostatics approximation,
- we have stem:[N] conducting materials whose respective domains are denoted stem:[\Omega_i,i=1...N] and their electric conductivity stem:[\sigma_i].

The electric potential is solution of the following equation
[stem]
++++
- \nabla \cdot \sigma_i V = \frac{q}{\varepsilon_0}, \quad \mbox{ in } \Omega_i, i=1...N
++++
where stem:[q] is the charge density and stem:[\varepsilon_0] is the vacuum permittivity.
This relationship is a form of Poisson's equation.
In the absence of electric charge, the equation becomes Laplace's equation:

[stem]
++++
\nabla \cdot \left( \sigma_i \nabla V \right) =0, \quad \mbox{ in } \Omega_i, i=1,...,N
++++
