= Data types

== Data formats
The following table summarizes the type of data used and generated in {feelpp}:

.{feelpp} type of file
[options="header"]
|===
| Type | format(s)

| <<_geometry_and_mesh,CAO files>>
| .geo , .step

| <<_geometry_and_mesh,Mesh files>>
| HDF5+JSON, all read by GMSH

| <<_fields,Fields files>>
| HDF5, Boost serialization

| <<_configuration_files,Configuration files>>
| CFG, JSON

| <<_visualization,Visualization files>>
| Ensight, Ensight Gold, VTK, VTK.js, CSV

| <<_journal,Journal files>>
| JSON

| <<_database,{feelpp} database>>
| HDF5+JSON, Boost serialization, mongodb dump

| <<_documentation, Documentation files>>
| .adoc, .png, .jpeg, ...


|===


== {feelpp} Data

=== Simulations

==== Input data

The inputs required to run a Feel++ simulation are :

* the CAO or the mesh files
* one or several cfg files
* one or several json files

These files are given to the application by specifying :

* each file separately
* a directory containing each file
* a zip file containing each file

If the data are not available locally, they can be retrieved remotely by specifying :

** Girder : file or folder ID
** Github : relative path in the github repository

==== Output data

The simulation will produce some data:

* Visualization file
* Journal file


=== Pre-Processing

The mesh generation or the mesh partitioning can be expensive steps in time.
We recommand to prepare these kinds of data before to run the simulation.

The mesh is built from a CAO file. The partitioning is generated from the mesh file.

The mesh (eventually the partitioning) is uploaded to the grider plateform.

=== Post-Processing

After the simulation is terminated, data as vtk.js or screenshot of the visualisation can be produced through python scripts.
This data can be uploaded to the Girder plateform.
