= Data storage

We use two kind of storage, it depends of the type of data.
Mesh files, visualization files and simulation journal files are store in the Girder plateform, the others one in the Github repository.

== Girder plateform

Girder is a free and open source web-based data management platform developed by Kitware as part of the Resonant data and analytics ecosystem.
It is a complete back-end (server side) technology that can be used with other applications via its RESTful API, or it can be used via its own front-end (client side web pages and JavaScript).

=== Data organisation

Data can be stored for a particular user or in the concept of collections.
This concept allow to share the data between one or several users (Groups concept).

Data are organized in hierarchical structure with Folders and Files.
When Folders or Files are defined, an unique ID is attributed at this entities.
These IDs allow to access easily to the data.

A levels of permission can be define for a ressource :

* READ permission (can view and download resources)
* WRITE permission (includes READ permission, can edit the properties of a resource)

Collections and folder can defined with attributes :

* Public (meaning viewable even by anonymous users)
* Private (meaning viewable only by those with READ access).

=== Upload/Download data

* REST API
* Web interface
* Girder CLI
* Python Client
* JavaScript libraries

=== Authentication

NOTE: Documentation depending

== MongoDB

Several MongoDB database are used as storage. MongoDB storage
can be seen in two ways:

* static (stored local as a file, or local server)
* server (stored on external mongodb server)


== Github repository

The access to the github file can be done by :

* using raw.githubusercontent.com
* REST API
