= Data Management

== Types of data

=== Input files :

* CAO files :
** .geo : interpreted by GMSH 
** .step : interpreted by OpenCascade (and GMSH)
* Mesh files :
** .msh : the GMSH mesh format
** .h5+.json : the Feel++ mesh format
* Configuration files
** .cfg : 
** .json :
* Visualization files (ParaView) :
** Ensight format :
** Ensight Gold format :
** VTK format :
** .csv : table of values
* Feel++ database :
** .h5
* Simulation Journal files :
** .json :
* Documentation files :
** .adoc :
** .png, .jpeg, ... : images

== Data storage

We use two kind of storage, it depends of the type of data.
Mesh files, visualization files and simulation journal files are store in the Girder plateform, the others one in the Github repository.

=== Girder plateform

Girder is a free and open source web-based data management platform developed by Kitware as part of the Resonant data and analytics ecosystem.
It is a complete back-end (server side) technology that can be used with other applications via its RESTful API, or it can be used via its own front-end (client side web pages and JavaScript).

==== Data organisation

Data can be stored for a particular user or in the concept of collections.
This concept allow to share the data between one or several users (Groups concept).

Data are organized in hierarchical structure with Folders and Files.
When Folders or Files are defined, an unique ID is attributed at this entities.
These IDs allow to access easily to the data.

A levels of permission can be define for a ressource :

* READ permission (can view and download resources)
* WRITE permission (includes READ permission, can edit the properties of a resource)

Collections and folder can defined with attributes :

* Public (meaning viewable even by anonymous users)
* Private (meaning viewable only by those with READ access).

==== Upload/Download data

* REST API
* Web interface
* Girder CLI
* Python Client
* JavaScript libraries

==== Authentication

=== Github repository

The access to the github file can be done by :

* using raw.githubusercontent.com
* REST API

== How to use the datas with Feel++ 

=== Meshing/Partitioning

=== Simulations

=== Visualization

==== Paraview

ParaView is an open-source, multi-platform data analysis and visualization application.

==== Paraview-Web

ParaViewWeb, the JavaScript library, is a Web framework to build applications with interactive scientific visualization inside the Web browser. Those applications can leverage a VTK and/or ParaView backend for large data processing and rendering, but can also be used on a static Web server like Apache or NGINX. You can even build local command line tools and use your browser to interact with your application.

==== vtk.js

vtk.js is a rendering library made for Scientific Visualization on the Web. It adapts the VTK structure and expertise to bring high performance rendering into your browser.

=== Documentations



