= Data Management

== Types of data

=== Input files :

* CAO files :
 ** .geo :
 ** .step :
 * Mesh files :
 ** .msh :
 ** .h5+.json :
 * Configuration files
 ** .cfg :
 ** .json :
 * Visualization files (ParaView) :
 ** Ensight format :
 ** Ensight gold format :
 ** VTK format :
 ** .csv :
 * Simulation Journal files :
 ** .json :
 * Documentation files :
 ** .adoc :
 ** .png, .jpeg, ... :

== Where the data are stored

=== Girder

Girder is a free and open source web-based data management platform developed by Kitware as part of the Resonant data and analytics ecosystem.

=== Github


== How to use the datas with Feel++ 

=== Meshing/Partitioning

=== Simulations

=== Visualization

==== Paraview

==== Paraview-Web

ParaViewWeb, the JavaScript library, is a Web framework to build applications with interactive scientific visualization inside the Web browser. Those applications can leverage a VTK and/or ParaView backend for large data processing and rendering, but can also be used on a static Web server like Apache or NGINX. You can even build local command line tools and use your browser to interact with your application.

=== Documentations

==== Asciidoctor and Antora

==== vtk.js

vtk.js is a rendering library made for Scientific Visualization on the Web. It adapts the VTK structure and expertise to bring high performance rendering into your browser.


