= The Feel++ Book
:page-permalink: /
:page-root: /
:page-layout: default
:docinfo: shared
include::includes/header.adoc[]

.What is {feelpp}?
****
{feelpp} is a unified {cpp} implementation of Galerkin methods (finite and
spectral element methods) in 1D, 2D and 3D to solve partial differential
equations.
****

== Manuals

include::man/list.adoc[]

== The Mathematics of {feelpp}

include::math/list.adoc[]

== Modeling with {feelpp} Toolboxes

Solving PDEs with link:/toolbox[{feelpp} Toolboxes].

include::toolboxes/list.adoc[]

== Programming with {feelpp}

include::programming/list.adoc[]

[compact]
--
link:/programming[Programming {feelpp}]::
The first step into Programming with {feelpp}

link:/programming/reference[Reference]::
Reference on various Mathematical concepts in {feelpp}

link:/programming/syntax-quick-reference/[Syntax Quick Reference]::
Quick reference cards for {feelpp} expressions that you can use in
variational formulations.
--

== Supercomputers with {feelpp}

include::clusters/list.adoc[]

== {feelpp} benchmarks

Benchmarks for {feelpp} toolboxes and {feelpp} applications are available in the link:/benchmarks[benchmarks section]

[[book.contributing]]
== Contributing

In the spirit of {uri-freesoftware}[free software], _everyone_ is encouraged to help improve this project.
If you discover errors or omissions in the source code, documentation, or website content, please don't hesitate to submit an issue or open a pull request with a fix.
New contributors are always welcome!

Here are some ways *you* can contribute:

* by using develop versions
* by {uri-issues}[reporting bugs]
* by {uri-issues}[suggesting new features]
* by writing or editing documentation
* by writing specifications
* by writing code -- _No patch is too small._
** fix typos
** add comments
** write examples!
** write tests!
* by refactoring code
* by fixing {uri-issues}[issues]
* by reviewing Pull Requests

The {uri-contribute}[Contributing] guide provides information on how to create, style, and submit issues, feature requests, code, and documentation to the {feelpp} Project.

== Getting Help

The {feelpp} project is developed to help you easily do _(i)_ modelisation simulation and optimisation and _(ii)_ high performance computing.
But we can't do it without your feedback!
We encourage you to ask questions and discuss any aspects of the project on the discussion list, on Twitter or in the chat room.

Twitter:: #feelpp hashtag or @feelpp mention
Chat (Gitter):: image:https://badges.gitter.im/Join%20In.svg[Gitter, link=https://gitter.im/feelpp/feelpp]

ifdef::env-github[]
Further information and documentation about {feelpp} can be found on the project's website.

{uri-project}/[Home] | {uri-news}[News] | {uri-docs}[Docs]
endif::[]

The {feelpp} organization on GitHub hosts the project's source code, issue tracker, and sub-projects.

Source repository (git):: {uri-repo}
Issue tracker:: {uri-issues}
{feelpp} organization on GitHub:: {uri-org}

== Copyright and Licensing

Copyright (C) 2011-2017 {feelpp} Consortium.
Free use of this software is granted under the terms of the GPL License.

See the {uri-license}[LICENSE] file for details.

== Authors

{feelpp} is led by https://github.com/prudhomm[Christophe Prud'homme] and has received contributions from {uri-contributors}[many other individuals].
The project was initiated in 2006 by https://github.com/prudhomm[Christophe Prud'homme] and based initially on link:https://cmcsforge.epfl.ch/projects/lifev/[lifeV] and completely re-written since then.
