// -*- mode: adoc -*-
== Spaces and elements

You've learned how to discretize the space you want to compute on.
You now have to learn how to define and use function spaces and
elements of functions spaces. For advanced informations on this
subject, you can look in the xref:dev:reference:Spaces/functionspace.adoc[Function Space] documentation.

=== Constructing a function space

- Loading a Mesh in 2D

[source,cpp]
----
auto mesh = loadMesh(_mesh=new Mesh<Simplex<2>>);
----

- For basic function spaces, we have predetermined constructors:

[source,cpp]
----
auto Xh = Pch<2>( mesh );
----

- Defining an element

[source,c++]
----
auto u = Xh->element( "u" );
auto w = Xh->element( "w" );
----

One can also use :

- `Pdh<ORDER>(mesh)` : Polynomial Discontinuous

- `Pvh<ORDER>(mesh)` : Polynomial Continuous Vectorial

- `Pdhv<ORDER>(mesh)` : Polynomial Discontinuous Vectorial

- `Pchm<ORDER>(mesh)` : Polynomial Continuous Matrix

- `Dh<ORDER>(mesh)` : RaviartThomas function space

- `Ned1h<ORDER>(mesh)` : Nedelec function spaces

=== Implementation

The implementation reads are follows
[source,cpp]
----
include::{examplesdir}/07-myfunctionspace.cpp[tag=all]
----

and the associated config file
[source,cfg]
----
include::{examplesdir}/07-myfunctionspace.cfg[]
----
