= Debugging {feelpp}

NOTE: Discuss on a particular application

== Debug mode

To debug {feelpp} code, it is best to work within the cmake Debug environment:


[shell]
.Command line to configure {feelpp} in Debug mode
----
configure -d
----

you recompile {feelpp} or just the application you are interested in.



== Using the Address sanitizer

It is strongly advise to use the xref:https://github.com/google/sanitizers/wiki/AddressSanitizer[Address Sanitizer]
[shell]
.Command line to configure {feelpp} in Debug mode
----
configure -d --enable-asan
----

GDB can be used as usual with applications built with AddressSanitizer support.
When AddressSanitizer finds a bug you can set a breakpoint

 * right before it generates the error report by setting a breakpoint on `__asan::ReportGenericError`
 * right after the error generation by setting a breakpoint on `__asan::Die`

NOTE: you can also set the environment variable `ASAN_OPTIONS=abort_on_error=1` to
get the same effect as in the second case
