= Vector Calculus Formula
:stem: latexmath


* stem:[f] champ scalaire stem:[\Omega \subset \mathbb{R}^d \rightarrow \mathbb{R}, d=1\ldots 3]
* stem:[u=\left(u_{1}, \ldots u_{d}\right)] champ de vecteur 
* stem:[A=\left(A_{i, j}\right) \in \mathbb{R}^{d \times d}] tenseur (matrice)

== Champ de vecteurs

* stem:[\nabla u=\left(\partial_{x_{j}} u_{i}\right)_{i, j}:] gradient de stem:[u(\text { matrice jacobienne })] 
* stem:[\varepsilon(u)=\frac{1}{2}\left(\nabla u+\nabla u^{T}\right):] partie symétrique du gradient de stem:[u] 
* stem:[\Delta u=\left(\Delta u_{1}, \ldots, \Delta u_{d}\right)^{T} \in \mathbb{R}^{d}:] Laplacien du stem:[u]

=== Operateur stem:[u \cdot \nabla ]

* stem:[u \cdot \nabla f = u_i \cdot \partial_{x_i} f = \sum_{i=1}^d u_i \partial_{x_i} f ]
* stem:[u \cdot \nabla u = ( u_i \cdot \partial_{x_i} u )^T = ( \sum_{i=1}^d u_i \partial_{x_i} u_1, \ldots,  \sum_{i=1}^d u_i \partial_{x_i} u_d)^T]

=== Champ de matrice, Tenseur


* stem:[\nabla \cdot A=\left(\nabla \cdot A_{1,:}, \ldots, \nabla \cdot A_{d,:}\right)^{T} \in \mathbb{R}^{d}:] divergence d'un tenseur
* stem:[A: B=\sum_{i, j} A_{i, j} B_{i, j} \in \mathbb{R}:] produit contracté de deux tenseurs

Espace fonctionnel::
* stem:[\left(H^{1}(\Omega)\right)^{d}:] espace de Sobolev vectoriel


== Calcul intégral

*Proposition:* stem:[\Omega] ouvert régulier Lipshitz et

* *Formule de Gauss vectorielle*: stem:[ u \in\left(H^{1}(\Omega)\right)^{d}]

[stem]
++++
\int_{\Omega} \nabla \cdot u=\int_{\partial \Omega} u \cdot n
++++
* *Formule d'intégration par partie vectorielle*: stem:[A \in\left(H^{1}(\Omega)\right)^{d \times d}, v \in H^{1}(\Omega)]

[stem]
++++
-\int_{\Omega}(\nabla \cdot A) \cdot v=\int_{\Omega} A: \nabla v-\int_{\partial \Omega}(A n) \cdot v
++++

=== Calcul intégral (suite)


* *Formule de Green vectorielle* stem:[u \in\left(H^{2}(\Omega)\right)^{d}, v \in\left(H^{1}(\Omega)\right)^{d}]

[stem]
++++
-\int_{\Omega} v \cdot \Delta u=\int_{\Omega} \nabla u: \nabla v-\int_{\partial \Omega} v \cdot(\nabla u n)
++++
