name: Index

on:
    schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '0 0 */15 * *'

jobs:
  # This workflow contains a single job called "build"
  index:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.3.4

    # Runs a single command using the runners shell
    - name: Index
      run: |
          sudo docker run -i -e APPLICATION_ID=$ALGOLIA_APP_ID  -e API_KEY=$ALGOLIA_ADMIN_API_KEY  -e "CONFIG=$(cat config.json | jq -r tostring)" algolia/docsearch-scraper
      env:
        ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      
