name: Manual CI
run-name: "Build ${{ github.ref_name }}"
on: workflow_dispatch

jobs:

  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'feelpp/book.feelpp.org' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ok go

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Python Install 
      run: |
        python -m venv --system-site-packages .venv
        source .venv/bin/activate
        pip install -r requirements.txt  
    - name: Npm Install 
      run: |
        npm i 
        echo "${{ github.workspace }}/node_modules/.bin" >> $GITHUB_PATH        
    - name: Build
      run: |
        source .venv/bin/activate
        npm run antora 
      env:
        GITHUB_OAUTH: ${{ secrets.DOCS_GITHUB_KEY }}
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: build/site # The folder the action should deploy.
          