= Get {feelpp} Programming Environment
include::{partialsdir}/header-macros.adoc[]

NOTE: {lvl_advanced}

We present here the {feelpp} toolchain with both required and suggested tools to either compile {feelpp} or use with {feelpp}.

== Compilers

{feelpp} uses {cpp}14 compilers such as GCC6 and Clang (stem:[\geq 4]).

IMPORTANT: It is mandatory not only to have a {cpp}14 compiler but also {cpp}14 stantard library.

[WARNING]
====
There used to be a major compatibility issue between llvm/clang and GCC
compilers since GCC5 released the ABI tag which makes it impossible to compile
{feelpp} using llvm/clang with GCC5 or GCC6 standard libraries for a
time. Please see the following table to understand the working {cpp} compiler /
{cpp} standard library combinations.
====

.Table {cpp} compilers and standard libraries combinations
|===
| Compiler  | Standard Library

| clang (3.6, 3.7, 3.8) | libstdc{plus}{plus} 4.9
| clang  |  libc{plus}{plus} (corresponding clang version)
| clang (3.8(requires patches), 3.9)  | libstdc{plus}{plus} 6
| GCC 6 | libstdc{plus}{plus} 6

|===

CAUTION: GCC 6.2.1 seems to be problematic on debian/testing -- the tests in the testsuite fail. -- GCC 6.3.1 or GCC 6.2.0 don't have any problems.

== Required tools and libraries

Other than {cpp}14 compilers, {feelpp} requires only a few tools and libraries, namely CMake, Boost C++ libraries and an MPI implementation such as open-mpi or mpich. The table below provides information regarding the minimum and maximum version supported. A -- means it has not necessarily been tested with the latest version but we do not expect any issues. Note that for MPI, an implementation with MPI-IO support would be best.

.Table required tools to compile Feel++
|===
| Name | Minimum Version | Maximum Version | Notes

| link:https://cmake.org/[CMake] | 3.0 | -- |
| MPI   | -- | -- | link:https://www.open-mpi.org/[OpenMPI] or link:https://www.mpich.org/[MPICH]
| link:https://www.boost.org/[Boost] | 1.61 | 1.66 |
| link:https://www.python.org/[Python Interpreter] |  2 | -- | Version 3 is recommended
|===

== Recommended libraries

Here is a list of libraries that we recommend to use jointly with Feel++.

.Table optional external libraries

|===
| Library | Minimum Version | Maximum Version  | Notes

| link:https://support.hdfgroup.org/HDF5/[HDF5]  | 1.8.6  | --  | 
| link:https://www.mcs.anl.gov/petsc/[PETSc] | 3.5 | -- | We strongly recommand to install PETSc with MUMPS packages. Others packages like Suitesparse, Trilinos/ML, Boomeramg can be appreciable. Moreover, we have some troubles with versions >= 3.9, see link:https://github.com/feelpp/feelpp/issues/1166[here].
| link:http://slepc.upv.es/[SLEPc] | 3.5 | -- | Depends on PETSc
| link:http://gmsh.info/[Gmsh]  | 2.8.7 | -- | 
//| OpenTURNS | 2.0 ||
| link:https://docs.python.org/3/library/index.html[Python Libs] |  3.0 ||
| link:http://www.sympy.org/en/index.html[Python SymPy] |  1.1 || Python 3 module sympy
|===

== Recommended tools

Here is a list of tools that we recommend to use jointly with Feel++.


.Table of recommended tools
|===
| Tool | License | Notes

3+>| *Computer Aided Design*
| Gmsh  | Open Source |

3+>| *Mesh Generation*
| Gmsh  | Open Source |
| MeshGems  | Commercial |


3+>| *Post-Processing*
| Paraview | Open Source |
| Ensight | Commercial |
| Octave | Open Source |
| Gmsh  | Open Source |

3+>| *Scripting Languages*
| Python  | Open Source |  Python 3 interpreter
|===

Note that all these packages are available under Debian GNU/Linux and Ubuntu. Once you have installed those dependencies, you can go to link:#Compiling[Compiling].

== Suggested tools

Here is a list of tools that we suggest to use jointly with Feel++.

.Table of suggested tools
|===
| Tool | License | Notes

3+>| *Computer Aided Design (CAD)*
| Freecad | Open Source |
| Salome | Open Source  | HDF5 version in Debian/sid currently breaks MED format support.


3+>| *Modeling, Compilation and Simulation Environment*
| Open Modelica | Open Source  |

3+>| *Debugging and Profiling*
| Google perftools| Open Source  |
| Valgrind | Open Source |

|===

== What's next?

* Checkout the xref:install/linux.adoc[Linux] installation from sources in xref:install/linux.adoc#_ubuntu[Ubuntu] or xref:install/linux.adoc#_debian[Debian]
* Checkout the xref:install/mac.adoc[MacOsX] installation from sources using Homebrew or Macport
